'use client';
/* eslint-disable react-hooks/static-components, @next/next/no-html-link-for-pages */
import {useMemo,useState} from 'react';
import {Activity,CalendarDays,Check,ChevronRight,ClipboardList,Globe2,LayoutDashboard,MapPin,Plus,Search,Swords,CircleDot,Trophy,Users,X} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Toaster,toast} from 'sonner';
import {clubs,players,initialMatches,initialTournaments,name,clubName,stats,tally,validateMatch,pairs,type Match,type Tournament} from '@/lib/rally';
const dateLabel=(d:string)=>new Date(d+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'});
function Pick({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:{id:string;name:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="picker"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.id} value={o.id}>{o.name}</SelectItem>)}</SelectContent></Select>}
function Avatar({id,large=false}:{id:string;large?:boolean}){const p=players.find(p=>p.id===id)!;return <span className={'avatar '+(large?'large':'')} style={{background:p.color}}>{p.name.split(' ').map(s=>s[0]).join('')}</span>}
function FormMarks({form}:{form:string[]}){return <div className="form-marks">{form.map((v,i)=><span key={i} className={v==='W'?'win':'loss'}>{v}</span>)}</div>}
export default function Home(){
 const [tab,setTab]=useState('overview'),[club,setClub]=useState('all'),[matches,setMatches]=useState<Match[]>(initialMatches),[events,setEvents]=useState<Tournament[]>(initialTournaments);
 const [search,setSearch]=useState(''),[eventSearch,setEventSearch]=useState(''),[eventStatus,setEventStatus]=useState('all'),[profile,setProfile]=useState<string|null>(null),[event,setEvent]=useState<string|null>(null);
 const [record,setRecord]=useState(false),[create,setCreate]=useState(false),[about,setAbout]=useState(false),[a,setA]=useState('alex'),[b,setB]=useState('jordan'),[bestOf,setBestOf]=useState('3'),[gameInputs,setGameInputs]=useState<[string,string][]>([['',''],['','']]),[error,setError]=useState('');
 const [compareA,setCompareA]=useState('alex'),[compareB,setCompareB]=useState('jordan'),[entry,setEntry]=useState('alex');
 const [eventName,setEventName]=useState(''),[eventDate,setEventDate]=useState('2026-10-10'),[eventClub,setEventClub]=useState('harbor'),[eventFormat,setEventFormat]=useState('Single elimination'),[capacity,setCapacity]=useState('16');
 const filtered=matches.filter(m=>club==='all'||m.club===club);
 const rankings=useMemo(()=>players.filter(p=>(club==='all'||p.club===club)&&p.name.toLowerCase().includes(search.toLowerCase())).map(p=>({...p,...stats(p.id,filtered)})).sort((a,b)=>b.winRate-a.winRate||b.wins-a.wins),[club,search,matches]);
 const currentEvent=events.find(t=>t.id===event);const currentProfile=profile?stats(profile,matches):null;
 const comparison=filtered.filter(m=>m.status==='confirmed'&&((m.a===compareA&&m.b===compareB)||(m.a===compareB&&m.b===compareA)));
 const compareStatsA=stats(compareA,comparison),compareStatsB=stats(compareB,comparison);
 function openRecord(){setError('');setRecord(true)}
 function saveMatch(e:React.FormEvent){e.preventDefault();if(gameInputs.some(g=>g.some(v=>v.trim()===''))){setError('Enter both scores for every game, or remove unused games.');return;}const games=gameInputs.map(g=>g.map(Number)) as [number,number][];const err=validateMatch(a,b,games,Number(bestOf));if(err){setError(err);return;}setMatches(ms=>[{id:crypto.randomUUID(),a,b,games,date:new Date().toISOString().slice(0,10),club:club==='all'?players.find(p=>p.id===a)!.club:club,status:'pending',kind:'Club play'},...ms]);setRecord(false);setGameInputs([['',''],['','']]);setTab('matches');toast.success('Sample result added. Confirm it to update statistics.');}
 function saveEvent(e:React.FormEvent){e.preventDefault();if(!eventName.trim())return;const t:Tournament={id:crypto.randomUUID(),name:eventName.trim(),date:eventDate,club:eventClub,location:clubs.find(c=>c.id===eventClub)!.location,format:eventFormat as Tournament['format'],capacity:Number(capacity),entrants:[],status:'Registration open'};setEvents(es=>[t,...es]);setCreate(false);setEventName('');setTab('tournaments');setEvent(t.id);toast.success('Sample tournament created for this session.');}
 function MatchList({items}:{items:Match[]}){return <div className="match-list">{!items.length?<p className="empty">No matches yet.</p>:items.map(m=>{const s=tally(m.games);return <div className="match-row" key={m.id}><div className="match-people"><button onClick={()=>setProfile(m.a)}><Avatar id={m.a}/><span>{name(m.a)}</span></button><span className="versus">vs</span><button onClick={()=>setProfile(m.b)}><span>{name(m.b)}</span></button></div><div className="match-score"><strong>{s.join(' : ')}</strong><small>{m.games.map(g=>g.join('–')).join(' · ')}</small></div><div className="match-meta"><span>{dateLabel(m.date)}</span>{m.status==='confirmed'?<small className="confirmed"><Check size={13}/> Confirmed</small>:<Button size="sm" variant="outline" onClick={()=>{setMatches(ms=>ms.map(x=>x.id===m.id?{...x,status:'confirmed'}:x));toast.success('Demo confirmation applied. Statistics updated.')}}>Confirm demo</Button>}</div></div>})}</div>}
 function RankingTable({short=false}:{short?:boolean}){return <Table><TableHeader><TableRow><TableHead className="rank-col">#</TableHead><TableHead>Player</TableHead><TableHead>W–L</TableHead><TableHead>Win rate</TableHead><TableHead>Last 5</TableHead></TableRow></TableHeader><TableBody>{rankings.slice(0,short?5:undefined).map((p,i)=><TableRow key={p.id}><TableCell className="rank-col">{String(i+1).padStart(2,'0')}</TableCell><TableCell><button className="person" onClick={()=>setProfile(p.id)}><Avatar id={p.id}/><span><b>{p.name}</b><small>{clubName(p.club)}</small></span></button></TableCell><TableCell>{p.wins}<span className="muted">–{p.losses}</span></TableCell><TableCell><strong>{p.played?p.winRate+'%':'—'}</strong></TableCell><TableCell><FormMarks form={p.form}/></TableCell></TableRow>)}</TableBody></Table>}
 function EventCard({t}:{t:Tournament}){return <button className="event-card" onClick={()=>setEvent(t.id)}><div className="event-card-top"><div className="date-block"><small>{new Date(t.date+'T12:00:00').toLocaleDateString('en-US',{month:'short'})}</small><strong>{new Date(t.date+'T12:00:00').getDate()}</strong></div><span className="badge">{t.status}</span></div><h3>{t.name}</h3><p>{clubName(t.club)}</p><div className="event-info"><span><MapPin size={15}/>{t.location}</span><span><Swords size={15}/>{t.format}</span></div><div className="event-bottom"><span>{t.entrants.length} / {t.capacity} players</span><ChevronRight size={18}/></div></button>}
 return <><Toaster position="bottom-right" richColors/><header className="topbar"><a className="brand" href="/" aria-label="Rally home"><span className="brand-mark"><CircleDot size={23}/></span>rally<span className="brand-period">.</span></a><span className="brand-label">TABLE TENNIS, TOGETHER.</span><button className="preview-button" onClick={()=>setAbout(true)}>Prototype <span>v0.1</span></button></header>
 <div className="demo-note"><span><strong>Interactive preview</strong><span className="note-long"> · Fictional clubs and players. Changes reset on refresh.</span></span><button onClick={()=>setAbout(true)}>What’s working?</button></div>
 <Tabs value={tab} onValueChange={setTab} className="app-shell"><div className="nav-wrap"><TabsList className="main-nav" variant="line">{[{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'players',label:'Players',icon:Users},{id:'matches',label:'Matches',icon:CircleDot},{id:'clubs',label:'Clubs',icon:Globe2},{id:'tournaments',label:'Tournaments',icon:Trophy}].map(n=><TabsTrigger value={n.id} key={n.id}><n.icon size={17}/>{n.label}</TabsTrigger>)}</TabsList></div>
 <main><div className="page-heading"><div><p className="eyebrow">THE CLUBHOUSE</p><h1>{({overview:'Every match tells a story.',players:'Know your competition.',matches:'Keep the score.',clubs:'Find your people.',tournaments:'Bring your best game.'} as Record<string,string>)[tab]}</h1><p className="subheading">{({overview:'Your players, results, and next great matchup.',players:'Explore player records and compare matchups.',matches:'Results, game by game.',clubs:'A shared home for every club and player.',tournaments:'Explore events, draws, and the players taking part.'} as Record<string,string>)[tab]}</p></div><Button className="primary-action" onClick={tab==='tournaments'?()=>setCreate(true):openRecord}><Plus size={18}/>{tab==='tournaments'?'Create tournament':'Record match'}</Button></div>
 <TabsContent value="overview"><div className="scope-row"><span>Club overview</span><Pick label="Filter by club" value={club} onChange={setClub} options={[{id:'all',name:'All clubs'},...clubs]}/></div><div className="stat-grid"><div className="stat-card"><span>Confirmed matches <CircleDot size={18}/></span><strong>{filtered.filter(m=>m.status==='confirmed').length}</strong><small>Across the sample season</small></div><div className="stat-card"><span>Active players <Users size={18}/></span><strong>{players.filter(p=>club==='all'||p.club===club).length}</strong><small>One profile, every matchup</small></div><div className="stat-card"><span>Upcoming tournaments <Trophy size={18}/></span><strong>{events.filter(t=>(club==='all'||t.club===club)&&t.status!=='Completed').length}</strong><small>Find your next competition</small></div><div className="stat-card accent-card"><span>Games played <Activity size={18}/></span><strong>{filtered.filter(m=>m.status==='confirmed').reduce((s,m)=>s+m.games.length,0)}</strong><small>Every point counts</small></div></div>
 <div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><h2>Club standings</h2><p>By match win percentage · sample season</p></div><Button variant="ghost" onClick={()=>{setSearch('');setTab('players')}}>All players <ChevronRight size={16}/></Button></div><RankingTable short/></section><section className="matchup-panel"><p className="eyebrow">HEAD TO HEAD</p><h2>How do you stack up?</h2><div className="matchup-avatars"><Avatar id={compareA} large/><span>VS</span><Avatar id={compareB} large/></div><div className="compare-picks"><Pick label="First comparison player" value={compareA} onChange={v=>{setCompareA(v);if(v===compareB)setCompareB(players.find(p=>p.id!==v)!.id)}} options={players}/><Pick label="Second comparison player" value={compareB} onChange={setCompareB} options={players.filter(p=>p.id!==compareA)}/></div><div className="h2h-score"><strong>{compareStatsA.wins}</strong><span>MATCH WINS</span><strong>{compareStatsB.wins}</strong></div><div className="h2h-bar"><span style={{width:comparison.length?`${compareStatsA.wins/comparison.length*100}%`:'50%'}}/></div><p className="h2h-note">{comparison.length?`${comparison.length} confirmed ${comparison.length===1?'match':'matches'} · ${compareStatsA.gamesWon}–${compareStatsB.gamesWon} in games`:'No recorded meetings yet'}</p></section></div>
 <div className="dashboard-grid bottom-grid"><section className="panel"><div className="panel-heading"><h2>Recent matches</h2><Button variant="ghost" onClick={()=>setTab('matches')}>All matches <ChevronRight size={16}/></Button></div><MatchList items={filtered.slice(0,4)}/></section><section><div className="section-heading"><h2>On the calendar</h2><CalendarDays size={18}/></div>{events.filter(t=>club==='all'||t.club===club).slice(0,1).map(t=><EventCard key={t.id} t={t}/>)}</section></div></TabsContent>
 <TabsContent value="players"><div className="toolbar"><label className="searchbox"><Search size={18}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search players" aria-label="Search players"/></label><Pick label="Player club" value={club} onChange={setClub} options={[{id:'all',name:'All clubs'},...clubs]}/></div><section className="panel"><RankingTable/>{!rankings.length&&<p className="empty">No players match your search.</p>}</section><p className="footnote">Standings use confirmed results only. Select a player to see their full record.</p></TabsContent>
 <TabsContent value="matches"><div className="toolbar"><h2>{filtered.length} recorded matches</h2><Pick label="Match club" value={club} onChange={setClub} options={[{id:'all',name:'All clubs'},...clubs]}/></div><section className="panel"><MatchList items={filtered}/></section></TabsContent>
 <TabsContent value="clubs"><div className="club-grid">{clubs.map(c=><section className="club-card" key={c.id}><div className="club-banner" style={{background:c.color}}><span>{c.initials}</span><CircleDot size={70} strokeWidth={1}/></div><div className="club-body"><h2>{c.name}</h2><p><MapPin size={15}/>{c.location}</p><div className="club-totals"><span><b>{players.filter(p=>p.club===c.id).length}</b> players</span><span><b>{matches.filter(m=>m.club===c.id).length}</b> matches</span></div><Button className="w-full" variant="outline" onClick={()=>{setClub(c.id);setTab('overview');setSearch('')}}>View club</Button></div></section>)}</div><div className="next-step"><Users size={22}/><div><h3>Built around your club.</h3><p>Club creation, member invitations, and administrator permissions are the next development milestone.</p></div></div></TabsContent>
 <TabsContent value="tournaments"><div className="toolbar"><label className="searchbox"><Search size={18}/><Input value={eventSearch} onChange={e=>setEventSearch(e.target.value)} placeholder="Search events, clubs, or locations" aria-label="Search tournaments"/></label><Pick label="Tournament status" value={eventStatus} onChange={setEventStatus} options={[{id:'all',name:'All statuses'},{id:'Registration open',name:'Registration open'},{id:'Upcoming',name:'Upcoming'},{id:'Completed',name:'Completed'}]}/></div><div className="event-grid">{events.filter(t=>(eventStatus==='all'||t.status===eventStatus)&&`${t.name} ${clubName(t.club)} ${t.location}`.toLowerCase().includes(eventSearch.toLowerCase())).map(t=><EventCard key={t.id} t={t}/>)}</div>{!events.some(t=>(eventStatus==='all'||t.status===eventStatus)&&`${t.name} ${clubName(t.club)} ${t.location}`.toLowerCase().includes(eventSearch.toLowerCase()))&&<p className="empty">No tournaments match those filters.</p>}</TabsContent>
 <footer><span className="footer-brand">rally.</span><span>Made for the next match.</span><span>Sample season · September 2026</span></footer></main></Tabs>
 <Dialog open={record} onOpenChange={setRecord}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>Record a match</DialogTitle><DialogDescription>Try score entry with sample players. Results stay in this preview session.</DialogDescription></DialogHeader><form onSubmit={saveMatch} className="form-stack"><div className="form-two"><label>Player one<Pick label="Player one" value={a} onChange={setA} options={players}/></label><label>Player two<Pick label="Player two" value={b} onChange={setB} options={players}/></label></div><label>Match format<Pick label="Match format" value={bestOf} onChange={setBestOf} options={['3','5','7'].map(n=>({id:n,name:`Best of ${n}`}))}/></label><div className="game-header"><span>Game</span><span>{name(a).split(' ')[0]}</span><span>{name(b).split(' ')[0]}</span><span/></div>{gameInputs.map((g,i)=><div className="game-input" key={i}><span>{String(i+1).padStart(2,'0')}</span>{g.map((v,j)=><Input key={j} aria-label={`Game ${i+1}, ${j===0?name(a):name(b)} score`} type="number" min="0" max="999" inputMode="numeric" value={v} onChange={e=>setGameInputs(gs=>gs.map((row,k)=>k===i?row.map((s,z)=>z===j?e.target.value:s) as [string,string]:row))}/>)}<Button type="button" variant="ghost" aria-label={`Remove game ${i+1}`} onClick={()=>setGameInputs(gs=>gs.filter((_,k)=>k!==i))}><X size={16}/></Button></div>)}<Button type="button" variant="outline" disabled={gameInputs.length>=Number(bestOf)} onClick={()=>setGameInputs(gs=>[...gs,['','']])}><Plus size={16}/>Add game</Button>{error&&<p className="error" role="alert">{error}</p>}<Button type="submit" className="primary-action">Submit sample result</Button></form></DialogContent></Dialog>
 <Dialog open={create} onOpenChange={setCreate}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>Create a tournament</DialogTitle><DialogDescription>Preview an event and its draw. No invitations will be sent.</DialogDescription></DialogHeader><form onSubmit={saveEvent} className="form-stack"><label>Tournament name<Input required maxLength={80} placeholder="e.g. Saturday Singles" value={eventName} onChange={e=>setEventName(e.target.value)}/></label><label>Host club<Pick label="Host club" value={eventClub} onChange={setEventClub} options={clubs}/></label><div className="form-two"><label>Date<Input required type="date" value={eventDate} onChange={e=>setEventDate(e.target.value)}/></label><label>Player limit<Pick label="Player limit" value={capacity} onChange={setCapacity} options={['4','8','16','32'].map(n=>({id:n,name:n}))}/></label></div><label>Format<Pick label="Tournament format" value={eventFormat} onChange={setEventFormat} options={['Round robin','Single elimination','Double elimination'].map(n=>({id:n,name:n}))}/></label><Button type="submit" className="primary-action">Create sample tournament</Button></form></DialogContent></Dialog>
 <Sheet open={!!profile} onOpenChange={o=>{if(!o)setProfile(null)}}><SheetContent className="detail-sheet">{profile&&currentProfile&&<><SheetHeader><div className="profile-top"><Avatar id={profile} large/><span className="badge">Sample player</span></div><SheetTitle className="detail-title">{name(profile)}</SheetTitle><SheetDescription>{clubName(players.find(p=>p.id===profile)!.club)}</SheetDescription></SheetHeader><div className="sheet-body"><div className="profile-stats"><div><strong>{currentProfile.wins}–{currentProfile.losses}</strong><span>Match record</span></div><div><strong>{currentProfile.winRate}%</strong><span>Win rate</span></div></div><h3>Last five matches</h3><FormMarks form={currentProfile.form}/><div className="detail-row"><span>Games won / lost</span><b>{currentProfile.gamesWon} / {currentProfile.gamesLost}</b></div><div className="detail-row"><span>Points won / conceded</span><b>{currentProfile.pointsWon} / {currentProfile.pointsLost}</b></div><h3>Head-to-head records</h3>{players.filter(p=>p.id!==profile).map(p=>{const ms=matches.filter(m=>(m.a===profile&&m.b===p.id)||(m.b===profile&&m.a===p.id));const s=stats(profile,ms);return s.played?<div className="detail-row" key={p.id}><span>{p.name}</span><b>{s.wins}–{s.losses}</b></div>:null})}<p className="footnote">All clubs · confirmed sample matches</p></div></>}</SheetContent></Sheet>
 <Sheet open={!!event} onOpenChange={o=>{if(!o)setEvent(null)}}><SheetContent className="detail-sheet">{currentEvent&&<><SheetHeader><span className="badge w-fit">{currentEvent.status}</span><SheetTitle className="detail-title">{currentEvent.name}</SheetTitle><SheetDescription>{clubName(currentEvent.club)} · {dateLabel(currentEvent.date)}, {currentEvent.date.slice(0,4)}</SheetDescription></SheetHeader><div className="sheet-body"><div className="detail-row"><span>Location</span><b>{currentEvent.location}</b></div><div className="detail-row"><span>Format</span><b>{currentEvent.format}</b></div><h3>Players · {currentEvent.entrants.length}/{currentEvent.capacity}</h3><div className="entrant-list">{currentEvent.entrants.map(id=><span key={id}><Avatar id={id}/>{name(id)}</span>)}</div>{currentEvent.entrants.length<currentEvent.capacity&&players.some(p=>!currentEvent.entrants.includes(p.id))&&<div className="entry-control"><Pick label="Choose sample entrant" value={currentEvent.entrants.includes(entry)?players.find(p=>!currentEvent.entrants.includes(p.id))!.id:entry} onChange={setEntry} options={players.filter(p=>!currentEvent.entrants.includes(p.id))}/><Button onClick={()=>{const id=currentEvent.entrants.includes(entry)?players.find(p=>!currentEvent.entrants.includes(p.id))!.id:entry;setEvents(ts=>ts.map(t=>t.id===event?{...t,entrants:[...t.entrants,id]}:t));toast.success('Sample player added.');}}>Add player</Button></div>}<h3>{currentEvent.format==='Round robin'?'Matchup preview':'Opening-round preview'}</h3><p className="footnote">Based on entry order. Scheduling and score advancement are not connected yet.</p>{pairs(currentEvent.entrants,currentEvent.format).map(([x,y],i)=><div className="fixture" key={i}><small>Match {i+1}</small><div><span>{name(x)}</span><span>{y?name(y):'Bye'}</span></div></div>)}{currentEvent.entrants.length<2&&<p className="empty">Add at least two players to preview matchups.</p>}</div></>}</SheetContent></Sheet>
 <Dialog open={about} onOpenChange={setAbout}><DialogContent><DialogHeader><DialogTitle>Rally · first development milestone</DialogTitle><DialogDescription>This is an interactive prototype using fictional data.</DialogDescription></DialogHeader><div className="about-copy"><h3>Try it now</h3><p>Browse clubs and player statistics, compare opponents, enter and confirm sample scores, and create a sample tournament with a draw preview.</p><h3>Coming next</h3><p>Real accounts, shared database storage, club permissions, opponent verification, ratings, and full tournament progression.</p><p>Changes reset when you refresh. This preview is private; the future public directory will allow visitors to browse without an account.</p></div></DialogContent></Dialog>
 </>;
}
