'use client';
import {useState} from 'react';
import PhotoCropper from './photo-cropper';
import Avatar from './player-avatar';
export type AccountProfile={id:string;name:string;bio:string;rally_id:string;photo_url?:string|null};
export default function AccountProfileForm({profile,onSave,disabled=false}:{profile:AccountProfile|null;onSave:(name:string,bio:string,photo?:string|null)=>Promise<void>;disabled?:boolean}){
 const [name,setName]=useState(profile?.name??''),[bio,setBio]=useState(profile?.bio??''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 const [photo,setPhoto]=useState<string|null|undefined>(),[cropFile,setCropFile]=useState<File|null>(null);
 async function save(event:React.FormEvent){event.preventDefault();if(busy||disabled||cropFile)return;setBusy(true);setError('');setSaved(false);try{await onSave(name,bio,photo);setSaved(true);}catch(error){setError(error instanceof Error?error.message:'Could not save your profile.');}finally{setBusy(false);}}
 return <section id="profile"><h2>Edit profile</h2><dl className="rally-id"><dt>Rally ID</dt><dd>{profile?.rally_id??'Assigned when you save your player profile'}</dd></dl><p className="profile-help">Your Rally ID stays the same when you change your username.</p><form onSubmit={save}><div className="profile-photo-field"><span className="field-label">Profile photo</span><div className="profile-photo-controls"><Avatar name={name||'Player'} photoUrl={photo===undefined?profile?.photo_url:photo} large/><div className="profile-photo-actions"><label className="photo-picker">Choose photo<input type="file" aria-label="Upload profile photo" accept="image/jpeg,image/png,image/webp" disabled={busy||disabled} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)setCropFile(file);}}/></label>{(photo===undefined?profile?.photo_url:photo)&&<button type="button" disabled={busy||disabled} onClick={()=>{setPhoto(null);setSaved(false);}}>Remove photo</button>}</div></div><p className="profile-help">Upload a clear photo of your face so other players can recognize you. JPG, PNG, or WebP, up to 10 MB.</p></div><label htmlFor="account-username">Username</label><input id="account-username" value={name} onChange={e=>{setName(e.target.value);setSaved(false);}} required maxLength={60} disabled={busy||disabled} autoComplete="nickname"/><p className="profile-help">Shown on club rosters, results, and your public player profile.</p><label htmlFor="account-bio">Bio (optional)</label><textarea id="account-bio" value={bio} onChange={e=>{setBio(e.target.value);setSaved(false);}} maxLength={500} rows={4} disabled={busy||disabled}/><p className="profile-help">Shown on your public player profile. {bio.length}/500 characters.</p>{error&&<p className="error" role="alert">{error}</p>}{saved&&<p role="status">Profile saved.</p>}<button className="primary-action" disabled={busy||disabled}>{busy?'Saving...':'Save profile'}</button></form><PhotoCropper file={cropFile} onCancel={()=>setCropFile(null)} onApply={photo=>{setPhoto(photo);setCropFile(null);setSaved(false);}}/></section>;
}
