'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {Menu,Home,Globe2,LayoutDashboard,Users,CircleDot,Trophy,Bell,UserCircle,Settings,MessageSquare,Download,LogOut,LogIn,RotateCcw,ClipboardList,Pencil,FlaskConical} from 'lucide-react';
import {toast} from 'sonner';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
export default function AccountMenu({name,onProfile,demo=false,onReset,unreadCount=0,profileHref,anonymous=false}:{anonymous?:boolean;profileHref?:string;name?:string;onProfile?:()=>void;demo?:boolean;onReset?:()=>void;unreadCount?:number}){
 const [busy,setBusy]=useState(false),[open,setOpen]=useState(false),router=useRouter(),base=demo?'/demo':'/clubhouse';
 async function signOut(){setBusy(true);try{const r=await fetch('/api/auth/signout',{method:'POST'});if(!r.ok)throw new Error('Could not sign out. Try again.');setOpen(false);router.push('/login');router.refresh();}catch(e){toast.error(e instanceof Error?e.message:'Could not sign out.');}finally{setBusy(false);}}
 const navigation=[{label:'Home',href:'/',Icon:Home},{label:'Clubs',href:'/clubs',Icon:Globe2},{label:'Sample demo',href:'/demo',Icon:FlaskConical},{label:'Feedback',href:demo?'/demo/feedback':'/feedback',Icon:MessageSquare}];
 const clubhouse=[{label:'Overview',tab:'overview',Icon:LayoutDashboard},{label:'Players',tab:'players',Icon:Users},{label:'Matches',tab:'matches',Icon:CircleDot},{label:'Tournaments',tab:'tournaments',Icon:Trophy},{label:'Inbox'+(unreadCount?' ('+unreadCount+')':''),tab:'notifications',Icon:Bell}];
 return <div className="account-area">{anonymous?<a className="header-signin" href="/login">Sign in</a>:name&&<a className="account-name" href={profileHref??(demo?'/demo/account':'/account')} title={profileHref?'View public profile':'Account settings'}>{name}</a>}<button className="account-menu-trigger" aria-label="Open navigation menu" aria-expanded={open} onClick={()=>setOpen(true)} disabled={busy}><Menu size={22}/></button><Sheet open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><SheetContent className="navigation-drawer"><SheetHeader><SheetTitle>Rally menu</SheetTitle><SheetDescription>{demo?'Sample demo':anonymous?'Browse Rally or sign in to play.':name}</SheetDescription></SheetHeader><nav className="drawer-links" aria-label="Site navigation">{navigation.map(({label,href,Icon})=><a key={label} href={href} onClick={()=>setOpen(false)}><Icon size={20}/>{label}</a>)}</nav><nav className="drawer-links" aria-label="Clubhouse navigation"><h3>Clubhouse</h3>{clubhouse.map(({label,tab,Icon})=><a key={tab} href={base+'?tab='+tab} onClick={()=>setOpen(false)}><Icon size={20}/>{label}</a>)}</nav>{!anonymous&&<nav className="drawer-links" aria-label="Account actions"><h3>Account</h3>{onProfile&&<button onClick={()=>{setOpen(false);onProfile();}}><Pencil size={20}/>Edit profile</button>}{profileHref&&<a href={profileHref}><UserCircle size={20}/>View public profile</a>}<a href={demo?'/demo/account':'/account'}><Settings size={20}/>Account settings</a><a href={demo?'/demo/records':'/records'}><ClipboardList size={20}/>Records & requests</a><a href={demo?'/demo/feedback':'/feedback'}><MessageSquare size={20}/>Request a feature / report a bug</a><a href="/install"><Download size={20}/>Add to Home Screen</a>{demo?<>{onReset&&<button onClick={()=>{setOpen(false);onReset();}}><RotateCcw size={20}/>Reset sample data</button>}<a href="/login"><LogIn size={20}/>Sign in to Rally</a></>:<button disabled={busy} onClick={()=>void signOut()}><LogOut size={20}/>{busy?'Signing out…':'Sign out'}</button>}</nav>}{anonymous&&<a className="drawer-signin primary-action" href="/login"><LogIn size={20}/>Sign in / create an account</a>}</SheetContent></Sheet></div>;
}
