'use client';
/* eslint-disable react-hooks/set-state-in-effect */
import {useCallback,useEffect,useRef,useState} from 'react';
import type {Announcement} from '@/lib/announcements';
import {Button} from '@/components/ui/button';
import {TimeLabel} from './time-label';
import {AnnouncementNotice} from './announcement-banner';
export default function AnnouncementsBoard({clubId,canPublish=false}:{clubId?:string;canPublish?:boolean}){
 const operation=useRef<string|null>(null);
 const [preview,setPreview]=useState(false);
 const [items,setItems]=useState<Announcement[]>([]),[admin,setAdmin]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[title,setTitle]=useState(''),[body,setBody]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const refresh=useCallback(async()=>{const r=await fetch('/api/announcements'+(clubId?'?club='+encodeURIComponent(clubId):''),{cache:'no-store'});if(r.status===401||r.status===403){setItems([]);return;}const data=await r.json() as {announcements:Announcement[];isSiteAdmin:boolean;error?:string};if(!r.ok)throw new Error(data.error||'Could not load announcements.');setItems(data.announcements);setAdmin(data.isSiteAdmin);},[clubId]);
 useEffect(()=>{let current=true;refresh().catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setLoading(false);});const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh().catch(()=>{});},30000);return()=>{current=false;clearInterval(timer);};},[refresh]);
 async function publish(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/announcements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'publish',id:operation.current??(operation.current=crypto.randomUUID()),clubId:clubId??'',title,body})});const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Could not publish announcement.');operation.current=null;setTitle('');setBody('');setNotice('Announcement published.');await refresh();window.dispatchEvent(new Event('rally-announcements-changed'));}catch(e){setError(e instanceof Error?e.message:'Could not publish.');}finally{setBusy(false);}}
 return <><section className="panel announcements-board" id="announcements"><div className="panel-heading"><div><h2>Announcements</h2><p>{clubId?'Updates for active club members':'Updates for your account'}</p></div><Button variant="outline" disabled={busy} onClick={()=>void refresh().catch(e=>setError(e.message))}>Refresh</Button></div>{error&&<p className="auth-error" role="alert">{error}</p>}{notice&&<p className="auth-success" role="status">{notice}</p>}{(clubId?canPublish:admin)&&<form onSubmit={e=>void publish(e)} className="announcement-form"><h3>{clubId?'Post a club announcement':'Post a Rally announcement'}</h3><p>{clubId?'Visible only to active members of this club.':'Visible to every Rally user with a player account.'} It will appear once as a popup and remain in the inbox.</p><label>Title<input required maxLength={120} value={title} onChange={e=>{operation.current=null;setTitle(e.target.value);}}/></label><label>Announcement<textarea required maxLength={2000} value={body} onChange={e=>{operation.current=null;setBody(e.target.value);}}/></label><div className="club-buttons"><Button type="button" variant="outline" disabled={busy||!title.trim()||!body.trim()} onClick={()=>setPreview(true)}>Preview</Button><Button type="submit" disabled={busy||!title.trim()||!body.trim()}>{busy?'Publishing…':'Publish announcement'}</Button></div></form>}{loading?<p role="status" className="announcement-empty">Loading announcements…</p>:items.length?items.map(a=><article className="announcement-entry" key={a.id}><span className="badge">{a.clubName??'Rally'}</span><h3>{a.title}</h3><small><TimeLabel value={a.created_at}/></small><p>{a.body}</p></article>):<p className="announcement-empty">No announcements yet.</p>}</section>{preview&&<AnnouncementNotice preview announcement={{id:"preview",club_id:clubId??null,title,body,created_at:new Date().toISOString(),clubName:null,seen:false}} onClose={()=>setPreview(false)}/>}</>;
}
