'use client';
/* eslint-disable @next/next/no-img-element */
import {useRef,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {prepareProfilePhoto} from '@/lib/prepare-profile-photo';
export default function ClubAppearance({club,onClose,busy,onSave}:{club:{id:string;name:string;photo_url?:string|null;banner_url?:string|null}|null;onClose:()=>void;busy:boolean;onSave:(payload:Record<string,unknown>,message:string)=>Promise<boolean>}){
 const [preparing,setPreparing]=useState(false),[error,setError]=useState('');const generation=useRef(0);
 async function upload(file:File,kind:'photo'|'banner'){if(!club)return;const clubId=club.id,token=++generation.current;setPreparing(true);setError('');try{const image=await prepareProfilePhoto(file,kind==='banner');if(token===generation.current)await onSave({action:'set_club_media',clubId,kind,image},'Club image saved.');}catch(error){if(token===generation.current)setError(error instanceof Error?error.message:'Could not prepare this image.');}finally{if(token===generation.current)setPreparing(false);}}
 return <Dialog open={!!club} onOpenChange={open=>{if(!open&&!busy&&!preparing){generation.current++;onClose();}}}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>Club appearance</DialogTitle><DialogDescription>{club?.name}: upload a club logo or photo and a banner.</DialogDescription></DialogHeader>{club&&<div className="form-stack">{(['photo','banner'] as const).map(kind=>{const url=kind==='photo'?club.photo_url:club.banner_url;return <section className="club-image-editor" key={kind}><h3>{kind==='photo'?'Club photo':'Club banner'}</h3>{url?<img className={`club-image-preview ${kind}`} src={url} alt={`Current ${kind}`}/>:<p>No {kind} uploaded.</p>}<label className="photo-picker">Choose {kind}<input type="file" accept="image/jpeg,image/png,image/webp" aria-label={`Upload club ${kind}`} disabled={busy||preparing} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void upload(file,kind);}}/></label>{url&&<Button type="button" variant="ghost" disabled={busy||preparing} onClick={()=>void onSave({action:'set_club_media',clubId:club.id,kind,image:null},'Club image removed.')}>Remove {kind}</Button>}<p className="footnote">{kind==='photo'?'Cropped to a square.':'Cropped to a wide 3:1 banner.'}</p></section>})}<p className="footnote">JPG, PNG, or WebP, up to 10 MB. Images save when selected.</p>{preparing&&<p role="status">Preparing image...</p>}{error&&<p className="error" role="alert">{error}</p>}<Button type="button" disabled={busy||preparing} onClick={onClose}>Done</Button></div>}</DialogContent></Dialog>;
}
