'use client';
/* eslint-disable @next/next/no-img-element */
import {useEffect,useState} from 'react';
import PublicHeader from './public-header';
import AccountMenu from './account-menu';
import ClubAppearance from './club-appearance';
import Avatar from './player-avatar';
import type {Data} from './rally-app';
import {createDemoData,applyDemoAction} from '@/lib/demo-state';
import {Button} from '@/components/ui/button';
export default function ClubPage({id,initialData,demo=false}:{id:string;initialData:Data;demo?:boolean}){
 const [data,setData]=useState(initialData),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[editing,setEditing]=useState(false),[images,setImages]=useState(false),[name,setName]=useState(''),[location,setLocation]=useState(''),[bio,setBio]=useState(''),[guest,setGuest]=useState('');
 useEffect(()=>{let current=true;
  // Browser session storage is only available after hydration.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  if(demo){try{const saved=sessionStorage.getItem('rally-demo-preview');if(saved)setData(JSON.parse(saved));else setData(createDemoData());}catch{}setLoading(false);return}
  fetch('/api/rally',{cache:'no-store'}).then(async r=>{if(r.status===401)return;if(!r.ok)throw new Error('Could not load club access. Refresh to try again.');const next=await r.json() as Data;if(current)setData(next);}).catch(e=>{if(current)setError(e.message)}).finally(()=>{if(current)setLoading(false)});return()=>{current=false};
 },[demo]);
 async function act(payload:Record<string,unknown>,message:string){if(busy)return false;setBusy(true);setError('');setNotice('');try{
  if(demo){const next=applyDemoAction(data,payload);setData(next);sessionStorage.setItem('rally-demo-preview',JSON.stringify(next));}
  else{const r=await fetch('/api/rally',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Could not save changes.');const read=await fetch('/api/rally',{cache:'no-store'});if(!read.ok)throw new Error('Saved. Refresh to load updated club information.');setData(await read.json() as Data);}
  setNotice(message+(demo?' Sample data only.':''));return true;
 }catch(e){setError(e instanceof Error?e.message:'Could not save changes.');return false}finally{setBusy(false)}}
 const club=data.clubs.find(c=>c.id===id),membership=data.memberships.find(m=>m.club_id===id&&m.player_id===data.me?.id),members=data.memberships.filter(m=>m.club_id===id&&m.status==='active'),requests=data.memberships.filter(m=>m.club_id===id&&m.status==='pending'),events=data.tournaments.filter(t=>t.club_id===id),matches=data.matches.filter(m=>m.club_id===id&&m.status==='confirmed');
 const player=(pid:string)=>data.players.find(p=>p.id===pid),base=demo?'/demo':'',back=demo?'/demo?tab=clubs':'/clubs';
 return <><PublicHeader account={data.me?<AccountMenu name={data.me.name} demo={demo} onProfile={()=>window.location.assign(demo?'/demo/account':'/account')}/>:undefined}/>{demo&&<div className="demo-note">Sample club · changes reset when browser storage is cleared</div>}<main className="public-page club-detail"><a href={back}>← All clubs</a>{error&&<p className="auth-error" role="alert">{error}</p>}{notice&&<p className="auth-success" role="status">{notice}</p>}{club?<>
 <section className="panel club-detail-hero">{club.banner_url&&<img className="club-detail-banner" src={club.banner_url} alt={`${club.name} banner`}/>}<div className="club-detail-heading">{club.photo_url&&<Avatar name={club.name} photoUrl={club.photo_url} large/>}<div><h1>{club.name}</h1><p>{club.location}</p>{club.approvalStatus!=='approved'&&<span className="badge">{club.approvalStatus==='pending'?'Awaiting Rally approval':'Not approved'}</span>}</div></div><div className="club-detail-info"><h2>About the club</h2><p className="player-bio">{club.bio||'This club has not added a bio yet.'}</p><div className="club-totals"><span><b>{members.length}</b> members</span><span><b>{matches.length}</b> verified matches</span><span><b>{events.length}</b> tournaments</span></div>{!loading&&club.approvalStatus==='approved'&&(membership?<p className="badge">{membership.status==='pending'?'Membership requested':membership.status==='active'?`Your role: ${membership.role}`:'Membership request declined'}</p>:data.me?<Button disabled={busy} onClick={()=>void act({action:'request_join',clubId:id},'Membership request sent.')}>Request to join</Button>:<a href={`/login?next=${encodeURIComponent(`/clubs/${id}`)}`}>Sign in to request membership</a>)}</div></section>
 {club.canManage&&<details className="panel club-detail-section club-management"><summary>Manage club</summary><div className="club-buttons">{club.canAssignRoles&&<Button variant="outline" disabled={busy} onClick={()=>{setName(club.name);setLocation(club.location);setBio(club.bio??'');setEditing(v=>!v);}}>Edit club information</Button>}<Button variant="outline" onClick={()=>setImages(true)}>Edit club images</Button><a href={`${demo?'/demo':'/clubhouse'}?tab=tournaments`}>Manage tournaments</a></div>{editing&&<form className="club-info-form" onSubmit={async e=>{e.preventDefault();if(await act({action:'update_club',clubId:id,name,location,bio},'Club information saved.'))setEditing(false);}}><label htmlFor="club-name">Club name</label><input id="club-name" value={name} onChange={e=>setName(e.target.value)} maxLength={80} required disabled={busy}/><label htmlFor="club-location">Location</label><input id="club-location" value={location} onChange={e=>setLocation(e.target.value)} maxLength={100} required disabled={busy}/><label htmlFor="club-bio">Club bio</label><textarea id="club-bio" value={bio} onChange={e=>setBio(e.target.value)} maxLength={1200} rows={5} disabled={busy}/><div className="club-buttons"><Button disabled={busy} type="submit">Save club information</Button><Button variant="ghost" type="button" disabled={busy} onClick={()=>setEditing(false)}>Cancel</Button></div></form>}
 <h3>Member requests</h3>{requests.length?requests.map(m=><div className="request-row" key={m.player_id}><span>{player(m.player_id)?.name}</span><Button disabled={busy} onClick={()=>void act({action:'approve_member',clubId:id,playerId:m.player_id},'Member approved.')}>Approve</Button><Button variant="ghost" disabled={busy} onClick={()=>void act({action:'decline_member',clubId:id,playerId:m.player_id},'Request declined.')}>Decline</Button></div>):<p>No pending requests.</p>}<form className="club-guest-form" onSubmit={async e=>{e.preventDefault();if(await act({action:'add_guest',id:crypto.randomUUID(),clubId:id,name:guest},'Guest player added.'))setGuest('');}}><label>Guest player name<input value={guest} onChange={e=>setGuest(e.target.value)} maxLength={60} required disabled={busy}/></label><Button disabled={busy} type="submit">Add guest player</Button></form></details>}
 <section className="panel club-detail-section"><h2>Members</h2>{club.canAssignRoles&&<p>Administrators and board members can create tournaments and verify games.</p>}{members.map(m=>{const p=player(m.player_id);if(!p)return null;return <div className="club-member-row" key={m.player_id}><a className="person" href={`${base}/players/${p.id}`}><Avatar name={p.name} photoUrl={p.photo_url}/><span><b>{p.name}</b></span></a>{club.canAssignRoles&&!p.is_guest&&m.role!=='owner'?<select aria-label={`Role for ${p.name}`} value={m.role} disabled={busy} onChange={e=>void act({action:'set_member_role',clubId:id,playerId:p.id,role:e.target.value},'Club role updated.')}><option value="member">Member</option><option value="admin">Administrator</option><option value="board">Board member</option></select>:<span className="badge">{p.is_guest?'Guest':m.role==='board'?'Board member':m.role==='admin'?'Administrator':m.role==='owner'?'Owner':'Member'}</span>}</div>})}{!members.length&&<p>No members yet.</p>}</section>
 <section className="panel club-detail-section"><h2>Tournaments</h2>{events.map(t=><a className="detail-row" key={t.id} href={`${base}/tournaments/${t.id}`}><span>{t.name}<small>{t.date}</small></span><span className="badge">{t.status==='registration'?'Registration open':t.status==='active'?'In progress':'Completed'}</span></a>)}{!events.length&&<p>No tournaments yet.</p>}</section>
 </>:loading?<p role="status">Loading club…</p>:<><h1>Club not available</h1><p>This club does not exist or is not published.</p></>}</main><ClubAppearance club={images&&club?.canManage?club:null} onClose={()=>setImages(false)} busy={busy} onSave={act}/></>;
}
