'use client';
/* eslint-disable @next/next/no-img-element, react-hooks/set-state-in-effect */
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeft} from 'lucide-react';
import PublicHeader from './public-header';
import ClubSeasons from './club-seasons';
import AnnouncementsBoard from './announcements-board';
import ClubInvite from './club-invite';
import ClubRoster from './club-roster';
import ActivityPage from './activity-page';
import AccountMenu from './account-menu';
import TournamentPanel from './tournament-panel';
import ClubAppearance from './club-appearance';
import Avatar from './player-avatar';
import {registrationClosed} from '@/lib/logistics';
import {TimeLabel} from './time-label';
import type {Data} from './rally-app';
import {createDemoData,applyDemoAction} from '@/lib/demo-state';
import {Button} from '@/components/ui/button';
export default function ClubPage({id,initialData,demo=false}:{id:string;initialData:Data;demo?:boolean}){
 const [data,setData]=useState(initialData),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[editing,setEditing]=useState(false),[images,setImages]=useState(false),[name,setName]=useState(''),[location,setLocation]=useState(''),[bio,setBio]=useState(''),[guest,setGuest]=useState('');
 const [eventId,setEventId]=useState<string|null>(null);
 const busyRef=useRef(false),readVersion=useRef(0),mounted=useRef(false),reading=useRef(false),readAbort=useRef<AbortController|null>(null);
 const invalidateReads=useCallback(()=>{readVersion.current++;},[]);
 const [refreshing,setRefreshing]=useState(false);
 const refreshClub=useCallback(async(manual=false)=>{
  if(busyRef.current||reading.current)return;
  if(demo){try{const saved=sessionStorage.getItem('rally-demo-preview');if(saved)setData(JSON.parse(saved));}catch{setError('Could not refresh sample requests.');}return;}
  reading.current=true;const version=++readVersion.current,controller=new AbortController();readAbort.current=controller;
  if(manual){setRefreshing(true);setError('');}
  try{const r=await fetch('/api/rally?compact=1&clubScope='+encodeURIComponent(id),{cache:'no-store',signal:controller.signal});if(r.status===401)return;if(!r.ok)throw new Error('Could not refresh club requests. Try Refresh requests again.');const next=await r.json() as Data;if(mounted.current&&version===readVersion.current)setData(next);}
  catch(e){if(!controller.signal.aborted&&manual&&mounted.current)setError(e instanceof Error?e.message:'Could not refresh club requests.');}
  finally{if(readAbort.current===controller){readAbort.current=null;reading.current=false;if(mounted.current){setLoading(false);if(manual)setRefreshing(false);}}}
 },[demo,id]);
 const [loadedEvent,setLoadedEvent]=useState<{event:Data['tournaments'][number];entries:Data['entries'];players:Data['players'];memberships:Data['memberships']}|null>(null),[eventLoading,setEventLoading]=useState(false);
 useEffect(()=>{if(demo||!eventId)return;let current=true;setEventLoading(true);fetch('/api/rally?view=event&event='+encodeURIComponent(eventId),{cache:'no-store'}).then(async r=>{const body=await r.json() as NonNullable<typeof loadedEvent>&{error?:string};if(!r.ok)throw new Error(body.error||'Could not open this event.');if(current)setLoadedEvent(body)}).catch(e=>{if(current){setError(e.message);setEventId(null)}}).finally(()=>{if(current)setEventLoading(false)});return()=>{current=false}},[demo,eventId,data]);
 const [venue,setVenue]=useState(''),[schedule,setSchedule]=useState(''),[contact,setContact]=useState(''),[joining,setJoining]=useState('');
 useEffect(()=>{mounted.current=true;
  if(demo){try{const saved=sessionStorage.getItem('rally-demo-preview');setData(saved?JSON.parse(saved):createDemoData());}catch{}setLoading(false);return()=>{mounted.current=false;};}
  void refreshClub(true);
  const resume=()=>{if(document.visibilityState==='visible')void refreshClub();};
  const timer=window.setInterval(resume,15000);
  window.addEventListener('focus',resume);document.addEventListener('visibilitychange',resume);
  return()=>{mounted.current=false;invalidateReads();readAbort.current?.abort();readAbort.current=null;reading.current=false;window.clearInterval(timer);window.removeEventListener('focus',resume);document.removeEventListener('visibilitychange',resume);};
 },[demo,id,refreshClub,invalidateReads]);
 async function act(payload:Record<string,unknown>,message:string){if(busyRef.current)return false;busyRef.current=true;readVersion.current++;setBusy(true);setError('');setNotice('');try{
  if(demo){const next=applyDemoAction(data,payload);setData(next);sessionStorage.setItem('rally-demo-preview',JSON.stringify(next));}
  else{const r=await fetch('/api/rally',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Could not save changes.');const read=await fetch('/api/rally?compact=1&clubScope='+encodeURIComponent(id),{cache:'no-store'});if(!read.ok)throw new Error('Saved. Refresh to load updated club information.');setData(await read.json() as Data);}
  setNotice(message+(demo?' Sample data only.':''));return true;
 }catch(e){setError(e instanceof Error?e.message:'Could not save changes.');return false}finally{busyRef.current=false;setBusy(false)}}
 const club=data.clubs.find(c=>c.id===id),membership=data.memberships.find(m=>m.club_id===id&&m.player_id===data.me?.id),requests=data.memberships.filter(m=>m.club_id===id&&m.status==='pending'),events=data.tournaments.filter(t=>t.club_id===id),matches=data.matches.filter(m=>m.club_id===id&&m.status==='confirmed');
 const player=(pid:string)=>data.players.find(p=>p.id===pid),base=demo?'/demo':'',back=demo?'/demo?tab=clubs':'/clubs';
 const eventDetail=!demo&&loadedEvent?.event.id===eventId?loadedEvent.event:events.find(t=>t.id===eventId),eventEntries=eventDetail?(!demo&&loadedEvent?.event.id===eventId?loadedEvent.entries:data.entries).filter(e=>e.tournament_id===eventDetail.id).map(e=>e.player_id):[],eventCandidates=eventDetail?(!demo&&loadedEvent?.event.id===eventId?loadedEvent.players:data.players).filter(p=>!eventEntries.includes(p.id)&&(!demo&&loadedEvent?.event.id===eventId?loadedEvent.memberships:data.memberships).some(m=>m.club_id===id&&m.player_id===p.id&&m.status==='active')):[];
 function eventCards(list:typeof events){return list.map(t=>{const entrants=data.entries.filter(e=>e.tournament_id===t.id),registered=entrants.some(e=>e.player_id===data.me?.id),count=t.entry_count??entrants.length,full=count>=t.capacity,closed=registrationClosed(t);return <article className="club-tournament-card" key={t.id}><div><a href={`${base}/tournaments/${t.id}`}><h3>{t.name}</h3></a><p>{t.date} · {t.format} · {count}/{t.capacity} players</p>{t.starts_at&&<p>Starts <TimeLabel value={t.starts_at}/></p>}{t.registration_closes_at&&<p>Registration closes <TimeLabel value={t.registration_closes_at}/></p>}<span className="badge">{t.status==='registration'?(closed?'Registration closed':full?'Registration full':'Registration open'):t.status==='active'?'In progress':'Completed'}</span>{registered&&<span className="badge">You’re registered</span>}</div><div className="club-buttons">{t.status==='registration'&&!loading&&(registered?<Button variant="outline" disabled={busy} onClick={()=>setEventId(t.id)}>Manage my entry</Button>:closed?<span>Registration deadline passed</span>:full?<span>Player limit reached</span>:membership?.status==='active'&&data.me?<Button disabled={busy} onClick={()=>void act({action:'enter_tournament',id:t.id,revision:t.revision,operationId:crypto.randomUUID(),playerId:data.me!.id},'You are registered.')}>Register</Button>:data.me?<a href="#club-membership">{membership?.status==='pending'?'Club approval needed to register':'Join this club to register'}</a>:<a href={`/login?next=${encodeURIComponent('/clubs/'+id)}`}>Sign in to register</a>)}{club?.canManage&&<Button variant="outline" onClick={()=>setEventId(t.id)}>{t.status==='registration'?'Manage registration':'Manage tournament'}</Button>}</div></article>})}
 return <><PublicHeader account={data.me?<AccountMenu profileHref={`${demo?'/demo':''}/players/${data.me.id}`} name={data.me.name} demo={demo} unreadCount={data.notifications?.filter(n=>!n.read).length??0} onProfile={()=>window.location.assign(demo?'/demo/account':'/account')}/>:undefined}/>{demo&&<div className="demo-note">Sample club · changes reset when browser storage is cleared</div>}<main className="public-page club-detail"><a className="club-back-link" href={back}><ArrowLeft size={20}/>All clubs</a>{error&&<p className="auth-error" role="alert">{error}</p>}{notice&&<p className="auth-success" role="status">{notice}</p>}{club?<>
 <section className="panel club-detail-hero">{club.banner_url&&<img className="club-detail-banner" src={club.banner_url} alt={`${club.name} banner`}/>}<div className="club-detail-heading">{club.photo_url&&<Avatar name={club.name} photoUrl={club.photo_url} large/>}<div><h1>{club.name}</h1><p>{club.location}</p>{club.approvalStatus!=='approved'&&<span className="badge">{club.approvalStatus==='pending'?'Awaiting Rally approval':'Not approved'}</span>}</div></div>{club.approvalStatus==='approved'&&<ClubInvite id={id} name={club.name} demo={demo}/>}<div className="club-detail-info" id="club-membership"><h2>About the club</h2><p className="player-bio">{club.bio||'This club has not added a bio yet.'}</p><dl className="club-practical">{[['Venue / address',club.venue],['Meeting times',club.meeting_schedule],['Contact',club.contact],['How to join',club.joining_info]].filter(([,value])=>value).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="club-totals"><span><b>{club.activeMemberCount}</b> members</span><span><b>{data.summaries?.[id]?.confirmed??matches.length}</b> verified matches</span><span><b>{data.eventCounts?.[id]??events.length}</b> tournaments</span></div>{!loading&&club.approvalStatus==='approved'&&(membership?<p className="badge">{membership.status==='pending'?'Membership requested':membership.status==='active'?`Your role: ${membership.role}`:'Membership request declined'}</p>:data.me?<Button disabled={busy} onClick={()=>void act({action:'request_join',clubId:id},'Membership request sent.')}>Request to join</Button>:<a href={`/login?next=${encodeURIComponent(`/clubs/${id}`)}`}>Sign in to request membership</a>)}</div></section>
 {!demo&&membership?.status==='active'&&<AnnouncementsBoard clubId={id} canPublish={club.canManage}/>} 
 {club.canManage&&<section className="panel club-detail-section club-request-panel"><div className="club-request-heading"><h2>Member requests ({requests.length})</h2><Button variant="outline" disabled={busy||refreshing} onClick={()=>void refreshClub(true)}>{refreshing?'Refreshing…':'Refresh requests'}</Button></div><p className="profile-help">Updates automatically while this page is open.</p>{requests.length?requests.map(m=>{const applicant=player(m.player_id);return <article className="club-request-row" key={m.player_id}><a className="person" href={`${base}/players/${m.player_id}`}><Avatar name={applicant?.name??'Player'} photoUrl={applicant?.photo_url}/><span><strong>{applicant?.name??'Player profile unavailable'}</strong><small>Requested to join this club</small></span></a><div className="club-request-actions"><Button disabled={busy||!applicant} aria-label={`Approve ${applicant?.name??'member'}`} onClick={()=>void act({action:'approve_member',clubId:id,playerId:m.player_id},'Member approved.')}>Approve</Button><Button variant="outline" disabled={busy||!applicant} aria-label={`Decline ${applicant?.name??'member'}`} onClick={()=>void act({action:'decline_member',clubId:id,playerId:m.player_id},'Request declined.')}>Decline</Button></div></article>;}):<p>No pending requests.</p>}</section>}
 {club.canManage&&<details className="panel club-detail-section club-management"><summary>Manage club</summary><div className="club-buttons">{club.canAssignRoles&&<Button variant="outline" disabled={busy} onClick={()=>{setName(club.name);setLocation(club.location);setBio(club.bio??'');setVenue(club.venue??'');setSchedule(club.meeting_schedule??'');setContact(club.contact??'');setJoining(club.joining_info??'');setEditing(v=>!v);}}>Edit club information</Button>}<Button variant="outline" onClick={()=>setImages(true)}>Edit club images</Button><a href={`${demo?'/demo':'/clubhouse'}?tab=tournaments`}>Manage tournaments</a></div>{editing&&<form className="club-info-form" onSubmit={async e=>{e.preventDefault();if(await act({action:'update_club',clubId:id,name,location,bio,venue,meeting_schedule:schedule,contact,joining_info:joining},'Club information saved.'))setEditing(false);}}><label htmlFor="club-name">Club name</label><input id="club-name" value={name} onChange={e=>setName(e.target.value)} maxLength={80} required disabled={busy}/><label htmlFor="club-location">Location</label><input id="club-location" value={location} onChange={e=>setLocation(e.target.value)} maxLength={100} required disabled={busy}/><label htmlFor="club-bio">Club bio</label><textarea id="club-bio" value={bio} onChange={e=>setBio(e.target.value)} maxLength={1200} rows={5} disabled={busy}/><label htmlFor="club-venue">Venue / address</label><input id="club-venue" value={venue} onChange={e=>setVenue(e.target.value)} maxLength={300} disabled={busy}/><label htmlFor="club-schedule">Meeting times</label><textarea id="club-schedule" value={schedule} onChange={e=>setSchedule(e.target.value)} maxLength={500} rows={3} disabled={busy}/><label htmlFor="club-contact">Public contact details</label><input id="club-contact" value={contact} onChange={e=>setContact(e.target.value)} maxLength={300} disabled={busy}/><label htmlFor="club-joining">Joining instructions</label><textarea id="club-joining" value={joining} onChange={e=>setJoining(e.target.value)} maxLength={800} rows={3} disabled={busy}/><p>These details are visible on the club page.</p><div className="club-buttons"><Button disabled={busy} type="submit">Save club information</Button><Button variant="ghost" type="button" disabled={busy} onClick={()=>setEditing(false)}>Cancel</Button></div></form>}
 <form className="club-guest-form" onSubmit={async e=>{e.preventDefault();if(await act({action:'add_guest',id:crypto.randomUUID(),clubId:id,name:guest},'Guest player added.'))setGuest('');}}><label>Guest player name<input value={guest} onChange={e=>setGuest(e.target.value)} maxLength={60} required disabled={busy}/></label><Button disabled={busy} type="submit">Add guest player</Button></form></details>}
 <ClubSeasons clubId={id} data={data} demo={demo} busy={busy} act={act}/><ClubRoster id={id} data={data} demo={demo} owner={!!club.canAssignRoles} busy={busy} act={act}/>

 <section className="panel club-detail-section"><h2>Upcoming tournaments</h2><ActivityPage<Data['tournaments'][number]> view="tournaments" query={new URLSearchParams({club:id,status:'upcoming'}).toString()} demo={demo} demoItems={events.filter(t=>t.status!=='completed').sort((a,b)=>a.date.localeCompare(b.date))} refreshKey={data} render={eventCards}/></section>{<details className="panel club-detail-section club-management"><summary>Past tournaments</summary><ActivityPage<Data['tournaments'][number]> view="tournaments" query={new URLSearchParams({club:id,status:'completed'}).toString()} demo={demo} demoItems={events.filter(t=>t.status==='completed').sort((a,b)=>b.date.localeCompare(a.date))} refreshKey={data} render={eventCards}/></details>}
 </>:loading?<p role="status">Loading club…</p>:<><h1>Club not available</h1><p>This club does not exist or is not published.</p></>}</main><TournamentPanel publicBase={`${base}/tournaments`} event={eventDetail??null} onClose={()=>setEventId(null)} players={!demo&&loadedEvent?.event.id===eventId?loadedEvent.players:data.players} entries={eventEntries} candidates={eventCandidates} admin={!!club?.canManage} me={data.me?.id??null} clubName={club?.name??''} busy={busy||eventLoading} act={act}/><ClubAppearance club={images&&club?.canManage?club:null} onClose={()=>setImages(false)} busy={busy} onSave={act}/></>;
}
