'use client';
import CleanSelect from './clean-select';
/* eslint-disable react-hooks/set-state-in-effect */
import {useEffect,useState} from 'react';
import ActivityPage from './activity-page';
import Avatar from './player-avatar';
import InitialRatingEditor from './initial-rating-editor';
import type {Data} from './rally-app';
type Member={initial_rating?:number|null;initial_rating_revision?:number;id:string;name:string;role:string;is_guest:number;photo_url?:string|null};
export default function ClubRoster({id,data,demo,owner,busy,act}:{id:string;data:Data;demo:boolean;owner:boolean;busy:boolean;act:(p:Record<string,unknown>,message:string)=>Promise<boolean>}){
 const club=data.clubs.find(c=>c.id===id),canEstimate=club?.approvalStatus==='approved'&&(club.canManage||data.isSiteAdmin);
 const [search,setSearch]=useState(''),[role,setRole]=useState('all'),[editing,setEditing]=useState<string|null>(null);
 useEffect(()=>{const query=new URLSearchParams(window.location.search);setSearch(query.get('memberSearch')??'');setRole(query.get('memberRole')??'all');},[]);
 const members=data.memberships.filter(m=>m.club_id===id&&m.status==='active').flatMap(m=>{const p=data.players.find(p=>p.id===m.player_id);return p?[{...p,role:m.role}]:[]}).filter(p=>p.name.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())&&(role==='all'||(p.is_guest?'guest':p.role)===role)).sort((a,b)=>Number(b.role==='owner')-Number(a.role==='owner')||a.name.localeCompare(b.name));
 return <section className="panel club-detail-section"><h2>Members</h2>{owner&&<p>Administrators and board members can create tournaments and verify games.</p>}<div className="club-member-filters"><div><label htmlFor="club-member-search">Search members</label><input id="club-member-search" type="search" placeholder="Player name" value={search} onChange={e=>setSearch(e.target.value)}/></div><div><label htmlFor="club-member-role">Member role</label><CleanSelect id="club-member-role" value={role} onChange={e=>setRole(e.target.value)}><option value="all">All roles</option><option value="owner">Owner</option><option value="admin">Administrators</option><option value="board">Board members</option><option value="member">Members</option><option value="guest">Guests</option></CleanSelect></div></div><ActivityPage<Member> view="members" query={new URLSearchParams({club:id,search,role}).toString()} demo={demo} demoItems={members} refreshKey={data} render={rows=>rows.map(p=><div className="club-member-entry" key={p.id}><div className="club-member-row"><a className="person" href={`${demo?'/demo':''}/players/${p.id}?from=${encodeURIComponent((demo?'/demo':'')+'/clubs/'+id+'?'+new URLSearchParams({section:'members',memberSearch:search,memberRole:role}).toString())}`}><Avatar name={p.name} photoUrl={p.photo_url}/><span><b>{p.name}</b></span></a><div className="member-role-actions"><span className="badge">{p.is_guest?'Guest':p.role==='board'?'Board member':p.role==='admin'?'Administrator':p.role==='owner'?'Owner':'Member'}</span>{((owner&&!p.is_guest&&p.role!=='owner')||canEstimate)&&<button className="member-edit-button" aria-label={`${editing===p.id?'Done editing':'Edit'} ${p.name}`} aria-expanded={editing===p.id} aria-controls={`member-edit-${p.id}`} onClick={()=>setEditing(editing===p.id?null:p.id)}>{editing===p.id?'Done':'Edit'}</button>}</div></div>{editing===p.id&&((owner&&!p.is_guest&&p.role!=='owner')||canEstimate)&&<div className="member-action-menu" id={`member-edit-${p.id}`}><div>{owner&&!p.is_guest&&p.role!=='owner'&&<label>Club role<CleanSelect aria-label={`Role for ${p.name}`} value={p.role} disabled={busy} onChange={async e=>{if(await act({action:'set_member_role',clubId:id,playerId:p.id,role:e.target.value},'Club role updated.'))setEditing(null);}}><option value="member">Member</option><option value="admin">Administrator</option><option value="board">Board member</option></CleanSelect></label>}{canEstimate&&<InitialRatingEditor player={p} clubId={id} siteAdmin={data.isSiteAdmin} busy={busy} act={act}/>}</div></div>}</div>)}/>{(search||role!=='all')&&<button className="standings-expand" onClick={()=>{setSearch('');setRole('all')}}>Clear filters</button>}</section>;
}
