'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import type {Tournament} from './tournament-panel';
import {localInput,utcInput,TimeLabel} from './time-label';
export default function EventLogistics({event:t,admin,busy,act}:{event:Tournament;admin:boolean;busy:boolean;act:(payload:Record<string,unknown>,message:string)=>Promise<boolean>}){
 const [editing,setEditing]=useState(false),[deadline,setDeadline]=useState(''),[start,setStart]=useState(''),[checkIn,setCheckIn]=useState(false);
 return <section className="event-logistics"><h3>Event details</h3>{t.starts_at&&<p><b>Starts:</b> <TimeLabel value={t.starts_at}/></p>}{t.registration_closes_at&&<p><b>Registration closes:</b> <TimeLabel value={t.registration_closes_at}/></p>}<p>Check-in {t.check_in_open&&t.status!=='completed'?'open':'closed'} · {t.checkedIn?.length??0} checked in</p>{t.status==='registration'&&<p>{t.allow_visitors?'Open to visiting players':'Host-club members only'}</p>}{admin&&t.status==='registration'&&<label className="check-in-toggle"><input type="checkbox" checked={!!t.allow_visitors} disabled={busy} onChange={e=>void act({action:'set_registration_policy',id:t.id,revision:t.revision,operationId:crypto.randomUUID(),allowVisitors:e.target.checked},'Registration policy saved.')}/>Allow visiting players without host-club membership</label>}{admin&&t.status!=='completed'&&<Button variant="outline" disabled={busy} onClick={()=>{setDeadline(localInput(t.registration_closes_at));setStart(localInput(t.starts_at));setCheckIn(!!t.check_in_open);setEditing(v=>!v)}}>Edit event details</Button>}{editing&&<form className="logistics-form" onSubmit={async e=>{e.preventDefault();const fields=new FormData(e.currentTarget);if(await act({action:'set_event_logistics',id:t.id,revision:t.revision,operationId:crypto.randomUUID(),registrationClosesAt:utcInput(String(fields.get('deadline')??'')),startsAt:utcInput(String(fields.get('start')??'')),checkInOpen:fields.has('checkIn')},'Event details saved.'))setEditing(false)}}><label htmlFor="event-start">Start time</label><input id="event-start" name="start" type="datetime-local" defaultValue={start} disabled={busy}/><label htmlFor="event-deadline">Registration deadline</label><input id="event-deadline" name="deadline" type="datetime-local" defaultValue={deadline} disabled={busy}/><p>Enter times in your device’s time zone. Leave blank if undecided. Registration closes at the deadline or when the draw starts.</p><label className="check-in-toggle"><input type="checkbox" name="checkIn" defaultChecked={checkIn} disabled={busy}/>Open player check-in</label><div className="club-buttons"><Button type="submit" disabled={busy}>Save event details</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>setEditing(false)}>Cancel</Button></div></form>}</section>;
}
