'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {addLivePoint,newLiveScore,undoLivePoint,gameWins,type LiveScore} from '@/lib/live-score';
export default function LivePointsTracker({names,bestOf,onChange,disabled=false,initialState,initialSwapped=false}:{names:[string,string];bestOf:number;onChange:(state:LiveScore,swapped:boolean)=>void;disabled?:boolean;initialState?:LiveScore;initialSwapped?:boolean}){
 const [state,setState]=useState(()=>initialState??newLiveScore()),[swapped,setSwapped]=useState(initialSwapped),[error,setError]=useState(''),[resetting,setResetting]=useState(false);
 function change(next:LiveScore){setState(next);onChange(next,swapped);setError('');setResetting(false);}
 function point(side:0|1){try{change(addLivePoint(state,side,bestOf));}catch(error){setError(error instanceof Error?error.message:'Could not add a point.');}}
 const wins=gameWins(state.games),sides: (0|1)[]=swapped?[1,0]:[0,1];
 return <section className="live-scoreboard" aria-label="Live points tracker"><div className="live-score-heading"><strong>{state.complete?'Match complete':`Game ${state.games.length+1}`}</strong><span>Games {wins[0]} - {wins[1]}</span></div><div className="live-score-sides">{sides.map(side=><button className={`live-score-side live-side-${side}`} type="button" key={side} disabled={disabled||state.complete} onClick={()=>point(side)} aria-label={`Add point for ${names[side]}`}><span>{names[side]}</span><strong>{state.points[side]}</strong><small>{state.complete?'Final game':'Tap to add a point'}</small></button>)}</div><p className="live-score-announcement" role="status" aria-live="polite">{state.complete?`${names[wins[0]>wins[1]?0:1]} wins ${Math.max(...wins)} - ${Math.min(...wins)}. Review and save the result.`:`${names[0]} ${state.points[0]}, ${names[1]} ${state.points[1]}. Play to 11, win by two.`}</p><div className="live-score-tools"><Button type="button" variant="outline" disabled={disabled||!state.history.length} onClick={()=>change(undoLivePoint(state))}>Undo point</Button><Button type="button" variant="outline" disabled={disabled} onClick={()=>{setSwapped(!swapped);onChange(state,!swapped)}}>Switch sides</Button><Button type="button" variant="ghost" disabled={disabled||!state.history.length} onClick={()=>setResetting(true)}>Reset</Button></div>{resetting&&<div className="live-reset-confirm"><p>Clear all points and completed games?</p><Button type="button" disabled={disabled} onClick={()=>change(newLiveScore())}>Clear score</Button><Button type="button" variant="ghost" onClick={()=>setResetting(false)}>Keep score</Button></div>}{state.games.length>0&&<div className="live-game-history" aria-label="Completed games">{state.games.map((game,index)=><span key={index}>G{index+1}: {game[0]} - {game[1]}</span>)}</div>}{error&&<p role="alert" className="error">{error}</p>}</section>;
}
