'use client';
import {useState} from 'react';
import {TimeLabel} from './time-label';
import {Button} from '@/components/ui/button';
import {CheckCheck,RefreshCw} from 'lucide-react';
import type {RallyNotification} from '@/lib/notifications';
function actionLabel(n:RallyNotification){if(n.kind==='reminder')return n.id.startsWith('remind-session-')?'View session':n.id.startsWith('remind-verification-')?'Verify match':'View tournament';if(n.id.startsWith('checkin-'))return 'Check in';if(n.id.startsWith('fixture-'))return 'View match';if(n.id.startsWith('claim-'))return n.actionNeeded?'Review claim':'View claim';if(n.id.startsWith('review-'))return n.actionNeeded?'Review dispute':'View review';return ({match:'Verify match',registration:n.actionNeeded?'View registration':'View tournament',tournament:'View tournament',record:'View record',feedback:'View feedback',announcement:'Read announcement',reminder:'View reminder'})[n.kind];}
export default function NotificationInbox({notifications,busy,act,onRefresh,demo=false}:{demo?:boolean;notifications:RallyNotification[];busy:boolean;onRefresh?:()=>Promise<void>;act:(payload:Record<string,unknown>,message:string)=>Promise<boolean>}){
 const [filter,setFilter]=useState('all'),[limit,setLimit]=useState(20);const unread=notifications.filter(n=>!n.read).length,needed=notifications.filter(n=>n.actionNeeded).length;
 const filtered=notifications.filter(n=>filter==='unread'?!n.read:filter==='action'?n.actionNeeded:true),visible=filtered.slice(0,limit);
 return <section className="panel notification-inbox"><div className="panel-heading"><p>{unread} unread · {needed} need action</p><div className="club-buttons">{onRefresh&&<Button variant="outline" size="icon" aria-label="Refresh" title="Refresh" disabled={busy} onClick={()=>void onRefresh()}><RefreshCw size={16}/></Button>}<Button variant="outline" size="icon" aria-label="Mark all as read" title="Mark all as read" disabled={busy||!unread} onClick={()=>void act({action:'mark_notifications_read'},'Inbox marked as read.')}><CheckCheck size={18}/></Button></div></div><div className="inbox-filters" aria-label="Inbox filters">{[['all','All'],['unread','Unread'],['action','Action needed']].map(([value,label])=><Button key={value} variant={filter===value?'default':'outline'} aria-pressed={filter===value} onClick={()=>{setFilter(value);setLimit(20)}}>{label}</Button>)}</div>{visible.length?['action','updates'].map(group=>{const rows=visible.filter(n=>group==='action'?n.actionNeeded:!n.actionNeeded);return rows.length?<section key={group} aria-label={group==='action'?'Action needed':'Updates'}><h2 className="inbox-group-title">{group==='action'?'Action needed':'Updates'}</h2>{rows.map(n=><article className={`notification-row ${n.read?'is-read':'is-unread'}`} key={n.id}><div><span className="badge">{n.read?'Read':'Unread'}</span><h3>{n.title}</h3>{n.date&&<small><TimeLabel value={n.date}/></small>}<p>{n.detail}</p></div><div className="club-buttons"><Button disabled={busy} variant="outline" onClick={async()=>{if(n.read||await act({action:'mark_notification_read',id:n.id},'Notification marked as read.'))window.location.assign(n.href);}}>{actionLabel(n)}</Button>{!n.read&&<Button variant="ghost" disabled={busy} onClick={()=>void act({action:'mark_notification_read',id:n.id},'Notification marked as read.')}>Mark as read</Button>}</div></article>)}</section>:null}):<div className="empty"><h2>{filter==='action'?'No action needed':filter==='unread'?'No unread updates':'You’re caught up'}</h2><p>{filter==='action'?'Reading a notice does not resolve its task. Completed requests disappear when activity refreshes.':'Match requests and club updates will appear here.'}</p></div>}{filtered.length>limit&&<Button className="inbox-more" variant="outline" onClick={()=>setLimit(n=>n+20)}>Show more ({filtered.length-limit})</Button>}<p className="footnote inbox-note"><a href={demo?'/demo/account':'/account'}>Notification preferences</a> · Read status follows your account. This inbox does not send email or push notifications.</p></section>;
}
