'use client';
import {useState} from 'react';
import {defaultPreferences,type NotificationPreferences} from '@/lib/notification-preferences';
import PushSettings from './push-settings';
export default function NotificationSettings({initial,onSave,disabled=false,live=false}:{initial?:NotificationPreferences|null;onSave:(p:NotificationPreferences)=>Promise<void>;disabled?:boolean;live?:boolean}){
 const [values,setValues]=useState({...defaultPreferences,...initial}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 return <section className="notification-settings"><h2>Notifications</h2><p>Choose which updates appear in your Rally inbox. These preferences follow your account.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');try{await onSave(values);setMessage('Notification preferences saved.');}catch(e){setError(e instanceof Error?e.message:'Could not save preferences.');}finally{setBusy(false);}}}>{([['match_updates','Match verification'],['registration_updates','Registration & waitlists'],['tournament_updates','Tournament matches & results'],['record_updates','Guest claims & match reviews'],['feedback_updates','Feature requests & bug reports'],['session_reminders','Remind me about sessions I RSVP to (within 24 hours)'],['tournament_reminders','Remind me about tournament starts and registration deadlines (within 24 hours)'],['verification_reminders','Remind me about verification waiting more than 24 hours'],['email_delivery','Email: verification requests, tournament call-ups and session reminders'],['push_delivery','Web push: verification requests, tournament call-ups and session reminders']] as const).map(([key,label])=><label className="notification-choice" key={key}><input type="checkbox" checked={values[key]} disabled={busy||disabled} onChange={e=>setValues({...values,[key]:e.target.checked})}/>{label}</label>)}<p className="profile-help">Turning an update off hides it from the inbox; it does not remove requests or your ability to review them. Email and push follow those same inbox rules and default to off. Session reminders also require the session reminder preference.</p><button className="primary-action" disabled={busy||disabled}>{busy?'Saving…':'Save notification preferences'}</button>{message&&<p role="status">{message}</p>}{error&&<p className="auth-error" role="alert">{error}</p>}</form>{live&&!disabled&&<PushSettings/>}</section>;
}

