import CleanSelect from './clean-select';
import {LayoutDashboard} from 'lucide-react';
import {env} from 'cloudflare:workers';
import Link from 'next/link';
import {redirect} from 'next/navigation';
import {getAuthenticatedUser} from '@/lib/auth';
import PublicHeader from './public-header';
import PlayerAvatar from './player-avatar';
import {getPublicDirectory} from '@/lib/public-rally';
import {getPublicLeaderboard} from '@/lib/public-leaderboard';
import {ESTABLISHED_MATCHES} from '@/lib/seeding';
import {tally} from '@/lib/rally';

export const dynamic='force-dynamic';
type Params={view?:string;q?:string;page?:string;club?:string;sort?:string;est?:string};
const dateLabel=(date:string)=>new Date(date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
export default async function Home({searchParams,publicBrowse=false}:{searchParams:Promise<Params>;publicBrowse?:boolean}){
 if(!publicBrowse&&env.SUPABASE_URL?.trim()&&env.SUPABASE_PUBLISHABLE_KEY?.trim()&&await getAuthenticatedUser())redirect('/clubhouse');
 const params=await searchParams,view=params.view==='players'?'players':params.view==='matches'?'matches':'tournaments',search=(params.q??'').slice(0,80),page=Math.max(1,Math.min(1000,Number.parseInt(params.page??'1')||1));
 const board=env.DB&&view==='players'?await getPublicLeaderboard(env.DB,{search,club:params.club,sort:params.sort,established:params.est==='1',page}):null,data=env.DB&&view!=='players'?await getPublicDirectory(env.DB,view,search,page):null;
 const ready=view==='players'?!!board:!!data,hasMore=view==='players'?!!board?.hasMore:!!data?.hasMore,isEmpty=view==='players'?!board?.players.length:!data?.[view].length;
 const filterParams=view==='players'&&board?{...(board.club!=='all'?{club:board.club}:{}),...(board.sort!=='rating'?{sort:board.sort}:{}),...(board.established?{est:'1'}:{})}:{};
 const base=publicBrowse?'/explore':'/';
 const url=(nextView:string,nextPage=1)=>base+'?'+new URLSearchParams({view:nextView,...(search?{q:search}:{}),...(nextView==='players'?filterParams:{}),...(nextPage>1?{page:String(nextPage)}:{})}).toString();
 const labels={tournaments:'Tournaments',players:'Players',matches:'Matches'};
 return <><PublicHeader/><main className="public-page public-directory">{!params.view&&!search&&page===1&&<section className="rally-intro"><div><p className="eyebrow">TABLE TENNIS CLUBS & COMPETITION</p><h1>Table tennis for clubs and players</h1><p>Rally brings club players, verified results and tournaments together. Record a match, follow your progress, or organize the next club event.</p><div className="intro-actions"><a className="primary-action" href="/login">Sign in / create an account</a><a className="intro-secondary" href="/demo">Try the sample demo</a><Link href="/clubs">Find a club</Link></div></div><div className="intro-features"><article><h2>Play & track</h2><p>Live point tracking, player profiles and opponent-weighted Rally ratings.</p></article><article><h2>Run club events</h2><p>Brackets, visiting-player registration, waitlists and club season ladders.</p></article><article><h2>Browse freely</h2><p>View public clubs, players, tournaments and verified matches without signing in.</p></article></div><p className="intro-install">Use Rally in your browser or <a href="/install">add it to your Home Screen</a>. Rally ratings are separate from USATT ratings.</p></section>}<div className="directory-heading"><div>{!params.view&&!search&&page===1?<h2>Public clubhouse</h2>:<h1>Public clubhouse</h1>}<p>Browse tournaments, players and verified matches.</p></div><a className="member-clubhouse-icon" href="/clubhouse" aria-label="Member clubhouse" title="Member clubhouse"><LayoutDashboard size={22}/></a></div>
  <nav className="directory-tabs" aria-label="Browse Rally">{(['tournaments','players','matches'] as const).map(v=><a key={v} href={url(v)} aria-current={v===view?'page':undefined}>{labels[v]}</a>)}</nav>
  <form className="directory-search" action={base}><input type="hidden" name="view" value={view}/>{Object.entries(filterParams).map(([k,v])=><input type="hidden" name={k} value={v} key={k}/>)}<label htmlFor="public-search">Search {view}</label><div><input id="public-search" name="q" defaultValue={search} maxLength={80} placeholder={view==='tournaments'?'Tournament or club name':view==='players'?'Player name':'Player or club name'}/><button className="primary-action" type="submit">Search</button>{search&&<a href={base+'?view='+view}>Clear</a>}</div></form>
  <section aria-label={labels[view]}><h2>{labels[view]}</h2>{!ready?<p role="status">Public records are temporarily unavailable. Please try again.</p>:<>
   {view==='tournaments'&&<div className="directory-grid">{(data?.tournaments??[]).map(t=><a className="directory-card" href={'/tournaments/'+t.id} key={t.id}><span className="badge">{t.status==='active'?'In progress':t.status==='completed'?'Completed':'Registration open'}</span><h3>{t.name}</h3><p>{t.clubName}</p><small>{dateLabel(t.date)} · {t.format} · {t.entrants} players</small><span className="directory-view">View tournament →</span></a>)}</div>}
   {view==='players'&&board&&<><form className="leaderboard-filters" action={base}><input type="hidden" name="view" value="players"/>{search&&<input type="hidden" name="q" value={search}/>}<label>Club<CleanSelect name="club" defaultValue={board.club}><option value="all">All clubs</option>{board.clubs.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</CleanSelect></label><label>Sort by<CleanSelect name="sort" defaultValue={board.sort}><option value="rating">Rating (rank)</option><option value="name">Name</option><option value="matches">Most matches</option><option value="winrate">Win rate</option></CleanSelect></label><label className="notification-choice"><input type="checkbox" name="est" value="1" defaultChecked={board.established}/>Established players only ({ESTABLISHED_MATCHES}+ verified matches)</label><div className="leaderboard-actions"><button className="primary-action" type="submit">Apply</button>{Object.keys(filterParams).length>0&&<a href={base+'?'+new URLSearchParams({view:'players',...(search?{q:search}:{})}).toString()}>Reset filters</a>}</div></form><p className="leaderboard-note">{board.total} {board.total===1?'player':'players'}{board.club!=='all'?' in '+(board.clubs.find(c=>c.id===board.club)?.name??'this club'):''}. Ratings use confirmed results from approved clubs{board.club!=='all'?' in this club only':''}; established players rank first. Rally ratings are not USATT ratings. <a href="/ratings">How ratings work</a></p><ol className="leaderboard-list">{board.players.map(p=><li key={p.id}><a className="leaderboard-row" href={'/players/'+p.id}><span className="leaderboard-rank" aria-label={p.rank?'Rank '+p.rank:'Unranked'}>{p.rank??'\u2013'}</span><PlayerAvatar name={p.name} photoUrl={p.photoUrl} publicProfile/><span className="leaderboard-name"><strong>{p.name}</strong><small>{p.played?`${p.wins}\u2013${p.losses} \u00b7 ${p.played} verified ${p.played===1?'match':'matches'}`:'No verified matches yet'}{p.rating!==null&&` \u00b7 ${p.established?'Established':`Provisional ${p.ratedMatches}/${ESTABLISHED_MATCHES}`}`}</small></span><span className="leaderboard-rating"><strong>{p.rating??'\u2014'}</strong><small>Rally rating</small></span></a></li>)}</ol></>}
   {view==='matches'&&<div className="directory-matches">{(data?.matches??[]).map(m=><article className="directory-card" key={m.id}><div className="directory-match-players"><a href={'/players/'+m.a}>{m.aName}</a><span>vs</span><a href={'/players/'+m.b}>{m.bName}</a></div><strong className="directory-score">{tally(m.games).join(' – ')}</strong><p>{m.games.map(g=>g.join('–')).join(' · ')}</p><small>{m.clubName} · {dateLabel(m.playedOn)} · Verified</small><a className="directory-view" href={'/matches/'+m.id}>View result {'\u2192'}</a>{m.tournamentId&&<a className="directory-view" href={'/tournaments/'+m.tournamentId}>View tournament →</a>}</article>)}</div>}
   {isEmpty&&<div className="directory-empty"><p>{search?'No '+view+' match your search.':'No public '+view+' yet.'}</p>{!search&&<a href="/demo">Explore the sample demo</a>}</div>}
   <nav className="directory-pagination" aria-label="Results pages">{page>1&&<a href={url(view,page-1)}>← Previous</a>}{(page>1||hasMore)&&<span>Page {page}</span>}{hasMore&&page<1000&&<a href={url(view,page+1)}>Next →</a>}</nav>
  </>}</section>
 </main></>;
}
