'use client';
/* eslint-disable @next/next/no-img-element */
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {photoCrop} from '@/lib/photo-crop';
export default function PhotoCropper({file,onCancel,onApply}:{file:File|null;onCancel:()=>void;onApply:(photo:string)=>void}){
 const [image,setImage]=useState<HTMLImageElement|null>(null),[zoom,setZoom]=useState(1),[x,setX]=useState(50),[y,setY]=useState(50),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const drag=useRef<{id:number;px:number;py:number;x:number;y:number;size:number}|null>(null);
 useEffect(()=>{if(!file)return;let active=true,url='';
  // Reset the crop when a new browser-selected image is loaded.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  setImage(null);setZoom(1);setX(50);setY(50);setError('');
  async function load(){try{if(!['image/jpeg','image/png','image/webp'].includes(file!.type))throw new Error('Choose a JPG, PNG, or WebP photo.');if(file!.size>10*1024*1024)throw new Error('Choose a photo smaller than 10 MB.');url=URL.createObjectURL(file!);const img=new Image();img.src=url;await img.decode();if(active)setImage(img);}catch(e){if(active)setError(e instanceof Error&&e.name!=='EncodingError'?e.message:'Could not read this photo. Choose another image.');}}
  void load();return()=>{active=false;if(url)URL.revokeObjectURL(url)};
 },[file]);
 const crop=image?photoCrop(image.naturalWidth,image.naturalHeight,zoom,x,y):null;
 function apply(){if(!image||!crop)return;setBusy(true);setError('');try{const canvas=document.createElement('canvas');canvas.width=320;canvas.height=320;const context=canvas.getContext('2d');if(!context)throw new Error('Could not prepare the photo. Try another browser.');context.fillStyle='#fff';context.fillRect(0,0,320,320);context.drawImage(image,crop.x,crop.y,crop.side,crop.side,0,0,320,320);let photo=canvas.toDataURL('image/jpeg',.85);for(const quality of [.7,.55,.4]){if(photo.length<=240023)break;photo=canvas.toDataURL('image/jpeg',quality);}if(photo.length>240023)throw new Error('This photo is too detailed. Choose another photo.');onApply(photo);}catch(e){setError(e instanceof Error?e.message:'Could not crop this photo.');}finally{setBusy(false)}}
 return <Dialog open={!!file} onOpenChange={open=>{if(!open&&!busy)onCancel();}}><DialogContent className="photo-crop-dialog"><DialogHeader><DialogTitle>Crop profile photo</DialogTitle><DialogDescription>Center your face in the circle. Drag to move the photo, or use the sliders.</DialogDescription></DialogHeader>{image&&crop?<><div className="photo-crop-preview" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={id:e.pointerId,px:e.clientX,py:e.clientY,x,y,size:e.currentTarget.getBoundingClientRect().width};}} onPointerMove={e=>{const d=drag.current;if(!d||d.id!==e.pointerId)return;const scale=d.size/crop.side;setX(Math.max(0,Math.min(100,d.x-(e.clientX-d.px)/scale/Math.max(1,image.naturalWidth-crop.side)*100)));setY(Math.max(0,Math.min(100,d.y-(e.clientY-d.py)/scale/Math.max(1,image.naturalHeight-crop.side)*100)));}} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}><img src={image.src} draggable={false} alt="Profile photo crop preview" style={{width:`${image.naturalWidth/crop.side*100}%`,height:`${image.naturalHeight/crop.side*100}%`,left:`${-crop.x/crop.side*100}%`,top:`${-crop.y/crop.side*100}%`}}/><span className="photo-crop-circle"/></div><label className="crop-slider">Zoom<input aria-label="Photo zoom" type="range" min={1} max={3} step={.05} value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><label className="crop-slider">Horizontal position<input aria-label="Photo horizontal position" type="range" min={0} max={100} value={x} onChange={e=>setX(Number(e.target.value))} disabled={image.naturalWidth===crop.side}/></label><label className="crop-slider">Vertical position<input aria-label="Photo vertical position" type="range" min={0} max={100} value={y} onChange={e=>setY(Number(e.target.value))} disabled={image.naturalHeight===crop.side}/></label><p className="footnote">The circular preview shows how your photo appears beside your name. Save your profile after applying the crop.</p></>:!error&&<p role="status">Loading photo…</p>}{error&&<p className="error" role="alert">{error}</p>}<div className="club-buttons"><Button variant="ghost" disabled={busy} onClick={onCancel}>Cancel crop</Button><Button disabled={busy||!image} onClick={apply}>Use cropped photo</Button></div></DialogContent></Dialog>;
}
