'use client';
/* eslint-disable @next/next/no-img-element */
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Minus,Plus,RotateCcw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {photoCrop,repositionCrop} from '@/lib/photo-crop';
export default function PhotoCropper({file,onCancel,onApply}:{file:File|null;onCancel:()=>void;onApply:(photo:string)=>void}){
 const [image,setImage]=useState<HTMLImageElement|null>(null),[zoom,setZoom]=useState(1),[x,setX]=useState(50),[y,setY]=useState(50),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const points=useRef(new Map<number,{x:number;y:number}>());
 const geometry=useRef({zoom:1,x:50,y:50});
 const gesture=useRef<{distance:number;zoom:number;source:{x:number;y:number};rect:DOMRect}|null>(null);
 function change(next:{zoom:number;x:number;y:number}){geometry.current=next;setZoom(next.zoom);setX(next.x);setY(next.y);}
 function begin(element:HTMLDivElement){if(!image)return;const ps=[...points.current.values()];if(!ps.length){gesture.current=null;return;}const rect=element.getBoundingClientRect(),center=ps.length>1?{x:(ps[0].x+ps[1].x)/2,y:(ps[0].y+ps[1].y)/2}:ps[0],g=geometry.current,c=photoCrop(image.naturalWidth,image.naturalHeight,g.zoom,g.x,g.y);gesture.current={rect,zoom:g.zoom,distance:ps.length>1?Math.max(1,Math.hypot(ps[1].x-ps[0].x,ps[1].y-ps[0].y)):0,source:{x:c.x+(center.x-rect.left)/rect.width*c.side,y:c.y+(center.y-rect.top)/rect.width*c.side}};}
 function move(){if(!image||!gesture.current)return;const ps=[...points.current.values()],g=gesture.current;if(!ps.length)return;const center=ps.length>1?{x:(ps[0].x+ps[1].x)/2,y:(ps[0].y+ps[1].y)/2}:ps[0],z=ps.length>1&&g.distance?g.zoom*Math.hypot(ps[1].x-ps[0].x,ps[1].y-ps[0].y)/g.distance:g.zoom;change(repositionCrop(image.naturalWidth,image.naturalHeight,z,g.source,{x:(center.x-g.rect.left)/g.rect.width,y:(center.y-g.rect.top)/g.rect.width}));}
 function scale(value:number){if(!image)return;const g=geometry.current,c=photoCrop(image.naturalWidth,image.naturalHeight,g.zoom,g.x,g.y);change(repositionCrop(image.naturalWidth,image.naturalHeight,value,{x:c.x+c.side/2,y:c.y+c.side/2},{x:.5,y:.5}));}
 useEffect(()=>{if(!file)return;let active=true,url='';
  // Reset the crop when a new browser-selected image is loaded.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  setImage(null);setZoom(1);setX(50);setY(50);geometry.current={zoom:1,x:50,y:50};points.current.clear();gesture.current=null;setError('');
  async function load(){try{if(!['image/jpeg','image/png','image/webp'].includes(file!.type))throw new Error('Choose a JPG, PNG, or WebP photo.');if(file!.size>10*1024*1024)throw new Error('Choose a photo smaller than 10 MB.');url=URL.createObjectURL(file!);const img=new Image();img.src=url;await img.decode();if(active)setImage(img);}catch(e){if(active)setError(e instanceof Error&&e.name!=='EncodingError'?e.message:'Could not read this photo. Choose another image.');}}
  void load();return()=>{active=false;if(url)URL.revokeObjectURL(url)};
 },[file]);
 const crop=image?photoCrop(image.naturalWidth,image.naturalHeight,zoom,x,y):null;
 function apply(){if(!image||!crop)return;setBusy(true);setError('');try{const canvas=document.createElement('canvas');canvas.width=320;canvas.height=320;const context=canvas.getContext('2d');if(!context)throw new Error('Could not prepare the photo. Try another browser.');context.fillStyle='#fff';context.fillRect(0,0,320,320);context.drawImage(image,crop.x,crop.y,crop.side,crop.side,0,0,320,320);let photo=canvas.toDataURL('image/jpeg',.85);for(const quality of [.7,.55,.4]){if(photo.length<=240023)break;photo=canvas.toDataURL('image/jpeg',quality);}if(photo.length>240023)throw new Error('This photo is too detailed. Choose another photo.');onApply(photo);}catch(e){setError(e instanceof Error?e.message:'Could not crop this photo.');}finally{setBusy(false)}}
 return <Dialog open={!!file} onOpenChange={open=>{if(!open&&!busy)onCancel();}}><DialogContent className="photo-crop-dialog"><DialogHeader><DialogTitle>Crop profile photo</DialogTitle><DialogDescription>Center your face in the circle. Drag to move. Pinch or use the zoom control to resize.</DialogDescription></DialogHeader>{image&&crop?<><div className="photo-crop-preview" tabIndex={0} role="group" aria-label="Photo position. Use arrow keys to move, plus and minus to zoom." onKeyDown={e=>{const g=geometry.current;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','='].includes(e.key)){e.preventDefault();if(e.key==='+'||e.key==='=')scale(g.zoom+.05);else if(e.key==='-')scale(g.zoom-.05);else change({...g,x:Math.max(0,Math.min(100,g.x+(e.key==='ArrowLeft'?-2:e.key==='ArrowRight'?2:0))),y:Math.max(0,Math.min(100,g.y+(e.key==='ArrowUp'?-2:e.key==='ArrowDown'?2:0)))});}}} onPointerDown={e=>{if(points.current.size>=2)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});begin(e.currentTarget);}} onPointerMove={e=>{if(!points.current.has(e.pointerId))return;points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});move();}} onPointerUp={e=>{points.current.delete(e.pointerId);begin(e.currentTarget);}} onPointerCancel={e=>{points.current.delete(e.pointerId);begin(e.currentTarget);}} onLostPointerCapture={e=>{points.current.delete(e.pointerId);begin(e.currentTarget);}} onWheel={e=>scale(geometry.current.zoom*Math.exp(-e.deltaY*.002))}><img src={image.src} draggable={false} alt="Profile photo crop preview" style={{width:`${image.naturalWidth/crop.side*100}%`,height:`${image.naturalHeight/crop.side*100}%`,left:`${-crop.x/crop.side*100}%`,top:`${-crop.y/crop.side*100}%`}}/><span className="photo-crop-circle"/></div><div className="crop-zoom-row"><Button variant="ghost" aria-label="Zoom photo out" disabled={zoom<=1} onClick={()=>scale(zoom-.1)}><Minus size={18}/></Button><input aria-label="Photo zoom" type="range" min={1} max={3} step="any" value={zoom} onChange={e=>scale(Number(e.target.value))}/><Button variant="ghost" aria-label="Zoom photo in" disabled={zoom>=3} onClick={()=>scale(zoom+.1)}><Plus size={22}/></Button></div><Button variant="ghost" onClick={()=>change({zoom:1,x:50,y:50})}><RotateCcw size={16}/>Reset crop</Button><p className="footnote">The circular preview shows how your photo appears beside your name. Save your profile after applying the crop.</p></>:!error&&<p role="status">Loading photo…</p>}{error&&<p className="error" role="alert">{error}</p>}<div className="club-buttons"><Button variant="ghost" disabled={busy} onClick={onCancel}>Cancel crop</Button><Button disabled={busy||!image} onClick={apply}>Use cropped photo</Button></div></DialogContent></Dialog>;
}
