'use client';
import {useEffect,useId,useRef,useState} from 'react';
import {Check,ChevronsUpDown,Search} from 'lucide-react';
import {useIsMobile} from '@/hooks/use-mobile';
import {Popover,PopoverContent,PopoverTrigger} from '@/components/ui/popover';
import {Command,CommandInput,CommandList,CommandEmpty,CommandGroup,CommandItem} from '@/components/ui/command';
export default function PlayerSearchPicker({value,onChange,options,label,onSearchChange,selectedName,allowClear=false,loading=false,clearLabel="No comparison",placeholder}:{value:string;onChange:(id:string)=>void;options:{id:string;name:string}[];label:string;onSearchChange?:(search:string)=>void;selectedName?:string;allowClear?:boolean;loading?:boolean;clearLabel?:string;placeholder?:string}){
 const [open,setOpen]=useState(false);const listId=useId(),selected=options.find(p=>p.id===value),mobile=useIsMobile(),container=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null);
 const changeOpen=(next:boolean)=>{setOpen(next);if(next)onSearchChange?.('');};
 const choose=(id:string)=>{onChange(id);setOpen(false);trigger.current?.focus({preventScroll:true});};
 useEffect(()=>{if(!mobile||!open)return;const outside=(event:PointerEvent)=>{if(!container.current?.contains(event.target as Node))setOpen(false);};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside);},[mobile,open]);
 const triggerButton=<button ref={trigger} type="button" className="player-search-trigger" role="combobox" aria-label={label} aria-expanded={open} aria-controls={listId} onClick={mobile?()=>changeOpen(!open):undefined}><Search size={16}/><span>{selectedName??selected?.name??placeholder??(allowClear?'Search players…':'Choose player')}</span><ChevronsUpDown size={14}/></button>;
 const choices=<Command shouldFilter={!onSearchChange} filter={(value,search,keywords)=>((keywords?.join(" ")??value).toLowerCase().includes(search.trim().toLowerCase())?1:0)}><CommandInput aria-label={`Search ${label.toLowerCase()}`} placeholder="Search players..." onValueChange={onSearchChange}/><CommandList id={listId}>{loading&&<p className="player-search-status" role="status">Searching players…</p>}<CommandEmpty>{loading?'Searching players…':'No players found.'}</CommandEmpty><CommandGroup>{allowClear&&<CommandItem value="no-comparison" onSelect={()=>choose('')}>{clearLabel}{!value&&<Check size={16}/>}</CommandItem>}{options.map(player=><CommandItem key={player.id} value={player.id} keywords={[player.name]} onSelect={()=>choose(player.id)}><span>{player.name}</span>{value===player.id&&<Check size={16}/>}</CommandItem>)}{allowClear&&!loading&&!options.length&&<p className="player-search-status">No players found.</p>}</CommandGroup></CommandList></Command>;
 if(mobile)return <div ref={container} className="player-search-inline" onKeyDown={event=>{if(event.key==='Escape'){event.stopPropagation();setOpen(false);trigger.current?.focus({preventScroll:true});}}}>{triggerButton}{open&&<div className="player-search-options" onClick={event=>{if((event.target as Element).closest("[cmdk-item]"))event.preventDefault();}}>{choices}</div>}</div>;
 return <Popover open={open} onOpenChange={changeOpen}><PopoverTrigger asChild>{triggerButton}</PopoverTrigger><PopoverContent className="player-search-popover" align="start">{choices}</PopoverContent></Popover>;
}
