'use client';
import {useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Button} from '@/components/ui/button';
import type {PublicPlayer} from '@/lib/public-rally';
import {tally} from '@/lib/rally';
import {ratingChangesByMatch,ratingHistory,type SeedMatch} from '@/lib/seeding';
import {RatingDelta} from './rating-delta';
import PlayerHighlightBadges from './player-highlights';
import ShareLinkButton from './share-link-button';
import PlayerBio from './player-bio';
import {playerHighlights} from '@/lib/player-highlights';
import Avatar from './player-avatar';
import PlayerSearchPicker from './player-search-picker';
import PlayerPerformance from './player-performance';
import RatingHistory from './rating-history';
import DoublesProfileCard from './doubles-profile';
import PlayerContextLink from './player-context-link';
const dateLabel=(date:string)=>new Date(date+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'});
export default function PlayerProfile({player:p,demo=false,demoMatches,players}:{player:PublicPlayer;demo?:boolean;demoMatches?:SeedMatch[];players?:{id:string;name:string}[]}){
 const [tab,setTab]=useState('summary'),[search,setSearch]=useState(''),[opponent,setOpponent]=useState(''),[shown,setShown]=useState(20);
 const base=demo?'/demo':'',demoChanges=demo&&demoMatches?ratingChangesByMatch(demoMatches):null,highlights=p.highlights??(demo&&demoMatches?playerHighlights(ratingHistory(demoMatches,p.id).changes):undefined),results=p.matches.map(m=>{const score=tally(m.games);return {...m,ratingChange:m.ratingChange??demoChanges?.[m.id]?.[p.id],score,won:score[m.playerSide]>score[1-m.playerSide]};}),wins=results.filter(m=>m.won).length,losses=results.length-wins;
 const totals=results.reduce((s,m)=>{s.gamesWon+=m.score[m.playerSide];s.gamesLost+=m.score[1-m.playerSide];for(const g of m.games){s.pointsWon+=g[m.playerSide];s.pointsLost+=g[1-m.playerSide];}return s;},{gamesWon:0,gamesLost:0,pointsWon:0,pointsLost:0});
 const opponents=Array.from(new Set(results.map(m=>m.opponentId))).map(id=>{const meetings=results.filter(m=>m.opponentId===id),won=meetings.filter(m=>m.won).length;return {id,name:meetings[0].opponentName,played:meetings.length,wins:won,losses:meetings.length-won};}).sort((a,b)=>b.played-a.played||a.name.localeCompare(b.name));
 const names=new Map(opponents.map(o=>[o.id,o.name])),filtered=results.filter(m=>!opponent||m.opponentId===opponent),matching=opponents.filter(o=>o.name.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
 const resultCards=(list:typeof results)=>list.map(m=><article className="public-result" key={m.id}><span className={m.won?'result-win':'result-loss'}>{m.won?'W':'L'}</span><div><strong><a href={`${base}/players/${m.opponentId}`}>{m.opponentName}</a></strong><small>{m.clubName} · {dateLabel(m.playedOn)}</small></div><div className="public-score"><b>{m.score[m.playerSide]}–{m.score[1-m.playerSide]}</b><small>{m.games.map(g=>`${g[m.playerSide]}–${g[1-m.playerSide]}`).join(' · ')}</small><RatingDelta value={m.ratingChange}/>{!demo&&<a href={`/matches/${m.id}`}>Result card</a>}{m.tournamentId&&<a href={`${base}/tournaments/${m.tournamentId}`}>View tournament</a>}</div></article>);
 return <div className="player-profile"><PlayerContextLink demo={demo}/><section className="public-hero"><Avatar name={p.name} photoUrl={p.photoUrl} publicProfile/><div className="public-hero-body"><div className="hero-title-row"><h1>{p.name}</h1>{!demo&&<ShareLinkButton iconOnly title={`${p.name} on Rally`} label="Share this profile"/>}</div><p className="hero-sub">{p.isGuest?'Guest player':'Rally player'}</p>{p.bio&&<PlayerBio text={p.bio}/>}</div></section>{p.isGuest&&<p><a className="dashboard-link" href={`${base}/records?guest=${encodeURIComponent(p.id)}`}>Request ownership of this guest record</a></p>}
 <Tabs value={tab} onValueChange={setTab}><TabsList className="section-tabs" aria-label="Player sections"><TabsTrigger value="summary">Summary</TabsTrigger><TabsTrigger value="progress">Stats</TabsTrigger><TabsTrigger value="matches">Matches</TabsTrigger><TabsTrigger value="head-to-head">Head-to-head</TabsTrigger></TabsList>
 <TabsContent value="summary"><PlayerHighlightBadges highlights={highlights} name={id=>names.get(id)??players?.find(x=>x.id===id)?.name??'Player'}/><div className="public-stat-grid"><article><strong>{results.length}</strong><span>Confirmed matches</span></article><article><strong>{wins}–{losses}</strong><span>Match record</span></article><article><strong>{results.length?Math.round(wins/results.length*100)+'%':'—'}</strong><span>Win rate</span></article><article><strong>{totals.gamesWon}–{totals.gamesLost}</strong><span>Games won–lost</span></article></div><div className="public-layout"><section className="panel"><div className="panel-heading"><h2>Recent results</h2><Button variant="ghost" onClick={()=>setTab('matches')}>All matches</Button></div>{results.length?resultCards(results.slice(0,5)):<p className="empty">No confirmed matches yet.</p>}</section><aside className="public-aside"><h2>Clubs</h2>{p.clubs.length?p.clubs.map(c=><a className="player-club-link" key={c.id} href={`${base}/clubs/${c.id}`}><strong>{c.name}</strong><span>{c.location}</span></a>):<p>No active public club memberships.</p>}</aside></div></TabsContent>
 <TabsContent value="progress"><PlayerPerformance playerId={p.id} playerName={p.name} demoMatches={demoMatches} players={players} pointTotals={{won:totals.pointsWon,lost:totals.pointsLost}}/><section className="panel profile-rating-panel"><RatingHistory matches={demoMatches??[]} playerId={p.id} name={id=>names.get(id)??players?.find(p=>p.id===id)?.name??'Player'} clubs={p.clubs} demo={demo} publicView initialClub="all"/></section>{!demo&&<DoublesProfileCard playerId={p.id}/>}</TabsContent>
 <TabsContent value="matches"><section className="panel"><div className="profile-section-heading"><h2>Confirmed matches</h2><div className="profile-opponent-picker"><span className="field-label">Opponent</span><PlayerSearchPicker label="Match opponent" value={opponent} onChange={id=>{setOpponent(id);setShown(20);}} options={opponents} allowClear clearLabel="All opponents"/></div></div>{filtered.length?resultCards(filtered.slice(0,shown)):<p className="empty">No confirmed matches in this view.</p>}{filtered.length>shown&&<Button className="standings-expand" variant="outline" onClick={()=>setShown(n=>n+20)}>Show more matches ({filtered.length-shown} remaining)</Button>}</section></TabsContent>
 <TabsContent value="head-to-head"><section className="panel"><div className="profile-section-heading"><h2>Head-to-head records</h2><label>Search opponents<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Player name"/></label></div>{matching.length?matching.map(o=><article className="opponent-record" key={o.id}><a href={`${base}/players/${o.id}`}>{o.name}</a><span><b>{o.wins}–{o.losses}</b> · {o.played} {o.played===1?'match':'matches'}</span><Button variant="ghost" onClick={()=>{setOpponent(o.id);setShown(20);setTab('matches');}}>View meetings</Button><a className="dashboard-link" href={`${base}/head-to-head/${p.id}/${o.id}`}>Share {p.name.split(' ')[0]} vs {o.name.split(' ')[0]}</a></article>):<p className="empty">{search?'No opponents match your search.':'No confirmed meetings yet.'}</p>}</section></TabsContent></Tabs><p className="public-note">Public statistics include confirmed results from approved clubs. Pending and voided results stay in member match history.</p></div>;
}
