'use client';
import {useId,useState} from 'react';
import {Check,ChevronsUpDown,Search} from 'lucide-react';
import {Popover,PopoverContent,PopoverTrigger} from '@/components/ui/popover';
import {Command,CommandInput,CommandList,CommandEmpty,CommandGroup,CommandItem} from '@/components/ui/command';
export default function PlayerSearchPicker({value,onChange,options,label,onSearchChange,selectedName,allowClear=false,loading=false}:{value:string;onChange:(id:string)=>void;options:{id:string;name:string}[];label:string;onSearchChange?:(search:string)=>void;selectedName?:string;allowClear?:boolean;loading?:boolean}){
 const [open,setOpen]=useState(false);const listId=useId(),selected=options.find(p=>p.id===value);
 return <Popover open={open} onOpenChange={next=>{setOpen(next);if(next)onSearchChange?.('');}}><PopoverTrigger asChild><button type="button" className="player-search-trigger" role="combobox" aria-label={label} aria-expanded={open} aria-controls={listId}><Search size={16}/><span>{selectedName??selected?.name??(allowClear?'Search players…':'Choose player')}</span><ChevronsUpDown size={14}/></button></PopoverTrigger><PopoverContent className="player-search-popover" align="start"><Command shouldFilter={!onSearchChange}><CommandInput aria-label={`Search ${label.toLowerCase()}`} placeholder="Search players..." onValueChange={onSearchChange}/><CommandList id={listId}>{loading&&<p className="player-search-status" role="status">Searching players…</p>}<CommandEmpty>{loading?'Searching players…':'No players found.'}</CommandEmpty><CommandGroup>{allowClear&&<CommandItem value="no-comparison" onSelect={()=>{onChange('');setOpen(false);}}>No comparison{!value&&<Check size={16}/>}</CommandItem>}{options.map(player=><CommandItem key={player.id} value={player.id} keywords={[player.name]} onSelect={()=>{onChange(player.id);setOpen(false);}}><span>{player.name}</span>{value===player.id&&<Check size={16}/>}</CommandItem>)}{allowClear&&!loading&&!options.length&&<p className="player-search-status">No players found.</p>}</CommandGroup></CommandList></Command></PopoverContent></Popover>;
}
