'use client';
import {useEffect,useState} from 'react';
export default function PushSettings(){
 const [enabled,setEnabled]=useState(false),[key,setKey]=useState<string|null>(null),[supported,setSupported]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let alive=true;fetch('/api/push',{cache:'no-store'}).then(async r=>{const d=await r.json() as {error?:string;enabled:boolean;publicKey:string|null};if(!r.ok)throw new Error(d.error);if(alive){setSupported('serviceWorker'in navigator&&'PushManager'in window);setEnabled(d.enabled);setKey(d.publicKey);}}).catch(()=>{if(alive)setError('Could not load this device’s notification settings.');});return ()=>{alive=false};},[]);
 async function change(){setBusy(true);setError('');try{
  if(enabled){const r=await fetch('/api/push',{method:'DELETE'});if(!r.ok)throw new Error('Could not disable push. Try again.');const registration=await navigator.serviceWorker.getRegistration();await (await registration?.pushManager.getSubscription())?.unsubscribe();setEnabled(false);}
  else{if(!key)throw new Error('Push is not configured yet.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Allow notifications in your phone or browser settings to enable push.');const registration=await navigator.serviceWorker.ready;const bytes=Uint8Array.from(atob(key.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));let subscription=await registration.pushManager.getSubscription();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});const r=await fetch('/api/push',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(subscription.toJSON())});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error??'Could not enable push.');setEnabled(true);}
 }catch(e){setError(e instanceof Error?e.message:'Could not update push notifications.');}finally{setBusy(false);}}
 return <div><p>On iPhone, open Rally from your Home Screen to enable push. Android supports installed web apps too. Enable “Web push” above and save, then enable this device.</p><button type="button" onClick={change} disabled={busy||!supported||!enabled&&!key}>{busy?'Updating…':enabled?'Disable push on this device':'Enable push on this device'}</button>{!supported&&<p>Push is unavailable in this browser. Try your Home Screen app.</p>}{supported&&!key&&<p>Push delivery has not been configured yet.</p>}{error&&<p role="alert" className="auth-error">{error}</p>}</div>;
}
