'use client';
/* eslint-disable @next/next/no-img-element, react-hooks/static-components, react-hooks/set-state-in-effect, @next/next/no-html-link-for-pages */
import {useCallback,useEffect,useRef,useState} from 'react';
import {Activity,CalendarDays,CheckCircle2,ChevronRight,CircleDot,Globe2,LayoutDashboard,Plus,Search,ShieldCheck,Trophy,Users,X} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Toaster,toast} from 'sonner';
import {calculateRatings,compareRatedPlayers,ESTABLISHED_MATCHES} from '@/lib/seeding';
import {stats,tally,type Match} from '@/lib/rally';
import TournamentPanel,{type Tournament} from './tournament-panel';
import PublicHeader from './public-header';
import AccountMenu from './account-menu';
import Avatar from './player-avatar';
import LivePointsTracker from './live-points-tracker';
import PlayerSearchPicker from './player-search-picker';
import type {Feedback} from '@/lib/feedback-types';
import PhotoCropper from './photo-cropper';
import {createDemoData,applyDemoAction} from '@/lib/demo-state';
type Player={id:string;name:string;is_guest:number;photo_url?:string|null;bio?:string;rally_id?:string};
type Club={id:string;name:string;location:string;bio?:string;canManage:boolean;canAssignRoles?:boolean;photo_url?:string|null;banner_url?:string|null;approvalStatus:'pending'|'approved'|'rejected';activeMemberCount:number};
type Member={club_id:string;player_id:string;role:string;status:string};
type Result={id:string;club_id:string;a:string;b:string;games:[number,number][];best_of:number;played_on:string;status:string;submitted_by:string;confirmed_by:string|null;canConfirm:boolean;canVoid:boolean;tournament_id:string|null;tournament_weight?:number};
type Event=Tournament;
export type Data={feedback?:Feedback[];me:{id:string;name:string}|null;account:{email:string;displayName:string;emailVerified:boolean}|null;isSiteAdmin:boolean;signedIn:boolean;deletedPlayers?:{id:string;name:string}[];players:Player[];clubs:Club[];memberships:Member[];matches:Result[];tournaments:Event[];entries:{tournament_id:string;player_id:string}[]};
const initial:Data={me:null,account:null,isSiteAdmin:false,signedIn:false,players:[],clubs:[],memberships:[],matches:[],tournaments:[],entries:[]};
function Pick({value,onChange,options,label,disabled=false}:{value:string;onChange:(s:string)=>void;options:{id:string;name:string}[];label:string;disabled?:boolean}){return <Select disabled={disabled} value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="picker"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem value={o.id} key={o.id}>{o.name}</SelectItem>)}</SelectContent></Select>}
const dateLabel=(date:string)=>new Date(date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
export function RallyApp({demo=false}:{demo?:boolean}={}){
 const [data,setData]=useState<Data>(()=>demo?createDemoData():initial),[loading,setLoading]=useState(!demo),[loadError,setLoadError]=useState(''),[requiresSignIn,setRequiresSignIn]=useState(false),[busy,setBusy]=useState(false);
 const [tab,setTab]=useState('overview'),[club,setClub]=useState('all'),[search,setSearch]=useState(''),[modal,setModal]=useState(''),[profile,setProfile]=useState<string|null>(null),[event,setEvent]=useState<string|null>(null),[voidId,setVoidId]=useState<string|null>(null);
 const [formName,setFormName]=useState(''),[location,setLocation]=useState(''),[selectedClub,setSelectedClub]=useState(''),[a,setA]=useState(''),[b,setB]=useState(''),[format,setFormat]=useState('3'),[date,setDate]=useState(''),[games,setGames]=useState<[string,string][]>([['',''],['','']]),[error,setError]=useState(''),[eventFormat,setEventFormat]=useState('Single elimination'),[capacity,setCapacity]=useState('16'),[eventStatus,setEventStatus]=useState('all'),[compareA,setCompareA]=useState(''),[compareB,setCompareB]=useState('');
 const [photo,setPhoto]=useState<string|null|undefined>(undefined),[photoBusy,setPhotoBusy]=useState(false);
 const [cropFile,setCropFile]=useState<File|null>(null);
 const [matchMode,setMatchMode]=useState<'manual'|'live'>('manual'),[liveComplete,setLiveComplete]=useState(false),[liveDirty,setLiveDirty]=useState(false);
 useEffect(()=>{const requested=new URLSearchParams(window.location.search).get('tab');if(requested&&['overview','players','matches','clubs','tournaments'].includes(requested))setTab(requested)},[]);
 const [standingsExpanded,setStandingsExpanded]=useState(false),[demoLoaded,setDemoLoaded]=useState(!demo);
 useEffect(()=>{setStandingsExpanded(false)},[club,search,tab]);
 useEffect(()=>{if(demo){try{const saved=sessionStorage.getItem('rally-demo-preview');if(saved)setData(JSON.parse(saved));}catch{}setDemoLoaded(true)}},[demo]);
 const liveGamesRef=useRef<[number,number][]|null>(null);
 const requestId=useRef('');
 const refresh=useCallback(async()=>{if(demo){setLoading(false);return;}setLoadError('');try{const r=await fetch('/api/rally',{cache:'no-store'});const body=await r.json() as Data & {error?:string};if(r.status===401){setRequiresSignIn(true);return}if(!r.ok)throw new Error(body.error||'Could not load your data.');setRequiresSignIn(false);setData(body);}catch(e){setLoadError(e instanceof Error?e.message:'Could not load your data.');}finally{setLoading(false)}},[demo]);
 useEffect(()=>{void refresh()},[refresh]);
 useEffect(()=>{if(demo&&demoLoaded){try{sessionStorage.setItem('rally-demo-preview',JSON.stringify(data));}catch{/* The demo still works without browser storage. */}}},[demo,data,demoLoaded]);
 const pname=(id:string)=>data.players.find(p=>p.id===id)?.name??data.deletedPlayers?.find(p=>p.id===id)?.name??'Unknown player';
 const photoUrl=(id:string)=>data.players.find(p=>p.id===id)?.photo_url;
 const cname=(id:string)=>data.clubs.find(c=>c.id===id)?.name??'Unknown club';
 const adminClubs=data.clubs.filter(c=>c.canManage),myClubs=data.clubs.filter(c=>data.memberships.some(m=>m.club_id===c.id&&m.player_id===data.me?.id&&m.status==='active'));
 const pendingClubs=data.clubs.filter(c=>c.approvalStatus==='pending');
 const ownsClub=data.memberships.some(m=>m.player_id===data.me?.id&&m.role==='owner'&&m.status==='active'),canCreateClub=!!data.me&&!!data.account?.emailVerified&&!ownsClub;
 const eligible=data.players.filter(p=>data.memberships.some(m=>m.club_id===selectedClub&&m.player_id===p.id&&m.status==='active'));
 const filtered=data.matches.filter(m=>club==='all'||m.club_id===club),statMatches=toMatches(filtered);
 const ratings=calculateRatings(filtered);
 const rankings=data.players.filter(p=>(club==='all'||data.memberships.some(m=>m.player_id===p.id&&m.club_id===club&&m.status==='active'))&&p.name.toLowerCase().includes(search.toLowerCase())).map(p=>({...p,...stats(p.id,statMatches),rating:ratings.get(p.id)?.rating??1000,ratedMatches:ratings.get(p.id)?.played??0,ratedWins:ratings.get(p.id)?.wins??0})).sort((a,b)=>compareRatedPlayers({rating:a.rating,played:a.ratedMatches,wins:a.ratedWins},{rating:b.rating,played:b.ratedMatches,wins:b.ratedWins})||a.name.localeCompare(b.name));
 const eventDetail=data.tournaments.find(t=>t.id===event),selectedPlayer=data.players.find(p=>p.id===profile);
 const ca=compareA||data.players[0]?.id||'',cb=compareB||data.players.find(p=>p.id!==ca)?.id||'';
 const comparison=statMatches.filter(m=>(m.a===ca&&m.b===cb)||(m.a===cb&&m.b===ca)),csA=stats(ca,comparison),csB=stats(cb,comparison);
 const eventPlayers=eventDetail?data.entries.filter(e=>e.tournament_id===eventDetail.id).map(e=>e.player_id):[];
 const candidates=eventDetail?data.players.filter(p=>!eventPlayers.includes(p.id)&&data.memberships.some(m=>m.club_id===eventDetail.club_id&&m.player_id===p.id&&m.status==='active')):[];
 async function act(payload:Record<string,unknown>,message:string){if(busy)return false;setBusy(true);setError('');try{if(demo){setData(applyDemoAction(data,payload));toast.success(message+' Sample data only.');return true;}const r=await fetch('/api/rally',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const b=await r.json() as {error?:string};if(!r.ok){if(r.status===409)await refresh();throw new Error(b.error||'Could not save your changes.');}toast.success(message);await refresh();return true}catch(e){const text=e instanceof Error?e.message:'Could not save. Try again.';setError(text);toast.error(text);return false}finally{setBusy(false)}}
 function open(type:string,cid?:string){liveGamesRef.current=null;setMatchMode('manual');setLiveComplete(false);setLiveDirty(false);setCropFile(null);setPhoto(undefined);setPhotoBusy(false);setError('');setFormName(type==='profile'?data.me?.name??data.account?.displayName??'':'');setLocation('');setGames([['',''],['','']]);setA('');setB('');setFormat('3');setDate(new Date().toLocaleDateString('en-CA'));setSelectedClub(cid??(type==='event'||type==='guest'?adminClubs[0]?.id:myClubs[0]?.id)??'');requestId.current=crypto.randomUUID();setModal(type)}
 async function submit(e:React.FormEvent){e.preventDefault();let payload:Record<string,unknown>={};let message='Saved.';
  if(modal==='profile'){if(photoBusy)return;payload={action:'save_profile',name:formName,...(photo!==undefined?{photo}:{})};message='Player profile saved.'}
  if(modal==='club'){payload={action:'create_club',id:requestId.current,name:formName,location};message='Club submitted for Rally approval.'}
  if(modal==='guest'){payload={action:'add_guest',id:requestId.current,clubId:selectedClub,name:formName};message='Guest player added.'}
  if(modal==='match'){if(matchMode==='live'&&!liveComplete){setError('Finish the match before saving the result.');return;}if(games.some(g=>g.some(v=>!v.trim()))){setError('Enter both scores for each game, or remove unused games.');return;}payload={action:'record_match',id:requestId.current,clubId:selectedClub,a,b,games:games.map(g=>g.map(Number)),bestOf:Number(format),date};message='Match saved.'}
  if(modal==='event'){payload={action:'create_tournament',id:requestId.current,clubId:selectedClub,name:formName,date,format:eventFormat,capacity:Number(capacity)};message='Tournament saved.'}
  if(await act(payload,message))setModal('');
 }
 function MatchList({items}:{items:Result[]}){return <div>{!items.length?<div className="empty"><CircleDot size={26}/><h3>No matches yet</h3><p>Record your first result to start building player statistics.</p></div>:items.map(m=><div className="saved-match" key={m.id}><div className="match-row"><div className="match-people"><button onClick={()=>setProfile(m.a)}><Avatar name={pname(m.a)} photoUrl={photoUrl(m.a)}/><span>{pname(m.a)}</span></button><span className="versus">vs</span><button onClick={()=>setProfile(m.b)}>{pname(m.b)}</button></div><div className="match-score"><strong>{tally(m.games).join(' : ')}</strong><small>{m.games.map(g=>g.join('–')).join(' · ')}</small></div><div className="match-meta"><span>{dateLabel(m.played_on)}</span><small className={'status-'+m.status}>{m.status==='confirmed'?'Confirmed':m.status==='voided'?'Voided':'Awaiting confirmation'}</small></div></div><div className="match-actions"><span>{cname(m.club_id)}{m.confirmed_by?` · Verified by ${pname(m.confirmed_by)}`:''}{m.tournament_id?' · Tournament':''}</span>{m.canConfirm&&<Button disabled={busy} size="sm" onClick={()=>act({action:'confirm_match',id:m.id},'Result confirmed. Statistics updated.')}>Confirm result</Button>}{m.canVoid&&<Button disabled={busy} size="sm" variant="ghost" onClick={()=>setVoidId(m.id)}>Void result</Button>}</div></div>)}</div>}
 function Standings({limited=false}:{limited?:boolean}={}){return <><Table className="club-standings"><TableHeader><TableRow><TableHead className="rank-col">#</TableHead><TableHead>Player</TableHead><TableHead>Rally rating</TableHead><TableHead>W–L</TableHead><TableHead>Win rate</TableHead><TableHead>Last 5</TableHead></TableRow></TableHeader><TableBody>{(limited&&!standingsExpanded?rankings.slice(0,10):rankings).map((p,i)=><TableRow key={p.id}><TableCell className="rank-col">{i+1}</TableCell><TableCell><button className="person" onClick={()=>setProfile(p.id)}><Avatar name={p.name} photoUrl={p.photo_url}/><span><b>{p.name}</b><small>{p.ratedMatches<ESTABLISHED_MATCHES?`Provisional · ${p.ratedMatches}/${ESTABLISHED_MATCHES} matches`:p.is_guest?'Guest player':p.id===data.me?.id?'You':'Player'}</small></span></button></TableCell><TableCell className="elo-cell">{p.ratedMatches?Math.round(p.rating):'—'}</TableCell><TableCell>{p.wins}–{p.losses}</TableCell><TableCell>{p.played?`${p.winRate}%`:'—'}</TableCell><TableCell><div className="form-marks">{p.form.map((f,i)=><span className={f==='W'?'win':'loss'} key={i}>{f}</span>)}</div></TableCell></TableRow>)}</TableBody></Table>{limited&&rankings.length>10&&<button className="standings-expand" aria-expanded={standingsExpanded} onClick={()=>setStandingsExpanded(v=>!v)}>{standingsExpanded?'Show top 10 ▴':`Show all ${rankings.length} players ▾`}</button>}</>}
 if(!loading&&requiresSignIn)return <><PublicHeader/><main className="access-gate"><div className="brand-mark"><CircleDot size={28}/></div><h1>Sign in to Rally</h1><p>Sign in to manage profiles, clubs, matches, and tournaments. Shared player profiles and tournament pages remain open to everyone.</p><a className="primary-action access-signin" href="/login">Sign in or create an account</a><a className="ios-install-link" href="/demo">Try the sample demo</a></main></>;
 return <><Toaster position="bottom-right" richColors/><header className="topbar"><a className="brand" href="/"><span className="brand-mark"><CircleDot size={24}/></span>rally<span className="brand-period">.</span></a><>{data.signedIn?<AccountMenu name={data.me?.name??'Set up profile'} onProfile={()=>open('profile')} demo={demo} onReset={()=>{setData(createDemoData());setEvent(null);setProfile(null);setModal('');toast.success('Sample data reset.');}}/>:<div className="account-area"><a href="/login">Sign in</a></div>}</></header>
 <div className="demo-note">{demo?<><span>Sample data · saved for this browser session</span><a href="/">Back to Rally</a></>:<><span>Sample demo</span><a href="/demo">Try all features</a></>}</div>
 {loading?<main><div className="empty" role="status">Loading your clubhouse…</div></main>:<Tabs value={tab} onValueChange={v=>{setTab(v);setSearch('')}} className="app-shell"><div className="nav-wrap"><TabsList className="main-nav" variant="line">{[{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'players',label:'Players',icon:Users},{id:'matches',label:'Matches',icon:CircleDot},{id:'clubs',label:'Clubs',icon:Globe2},{id:'tournaments',label:'Tournaments',icon:Trophy}].map(n=><TabsTrigger key={n.id} value={n.id}><n.icon size={17}/>{n.label}</TabsTrigger>)}</TabsList></div><main>
 {loadError&&<div className="load-error" role="alert"><p>{loadError} {data.players.length>0?'The last loaded records are shown.':''}</p><Button variant="outline" onClick={refresh}>Retry loading</Button></div>}
 {!loadError&&data.signedIn&&!data.me&&<div className="welcome-panel"><div><h2>Create your player profile</h2><p>Create your player profile, then start a club or request to join one.</p></div><Button className="primary-action" onClick={()=>open('profile')}>Create player profile</Button></div>}
 <div className="page-heading"><div><h1>{({overview:'Overview',players:'Players',matches:'Matches',clubs:'Clubs',tournaments:'Tournaments'} as Record<string,string>)[tab]}</h1></div>{data.me&&<Button disabled={busy||(tab==='clubs'&&!canCreateClub)||(tab==='tournaments'&&!adminClubs.length)||(tab!=='clubs'&&tab!=='tournaments'&&!myClubs.length)} className="primary-action" onClick={()=>open(tab==='clubs'?'club':tab==='tournaments'?'event':'match')}><Plus size={18}/>{tab==='clubs'?(ownsClub?'Club created':'Create club'):tab==='tournaments'?'Create tournament':'Record match'}</Button>}</div>
 <TabsContent value="overview"><div className="scope-row"><span>Club overview</span><Pick label="Filter by club" value={club} onChange={setClub} options={[{id:'all',name:'All clubs'},...data.clubs]}/></div><div className="stat-grid">{[{label:'Confirmed matches',value:filtered.filter(m=>m.status==='confirmed').length,note:'Verified results only',icon:CircleDot},{label:'Players',value:rankings.length,note:'Individual and guest profiles',icon:Users},{label:'Tournaments',value:data.tournaments.filter(t=>club==='all'||t.club_id===club).length,note:'Saved club events',icon:Trophy},{label:'Games played',value:filtered.filter(m=>m.status==='confirmed').reduce((s,m)=>s+m.games.length,0),note:'Confirmed results',icon:Activity}].map((s,i)=><div className={'stat-card '+(i===3?'accent-card':'')} key={s.label}><span>{s.label}<s.icon size={18}/></span><strong>{s.value}</strong></div>)}</div>
 {!data.clubs.length&&!loadError&&<div className="welcome-panel"><div><h2>Create a club</h2><p>A verified account may create one club. Create a club to add players and begin recording results.</p></div><Button disabled={!canCreateClub||busy} onClick={()=>open('club')}>{data.account?.emailVerified?'Create your club':'Verify your email to create a club'}</Button></div>}
 <p className="elo-help">Single-club tournaments count 2×; cross-club tournaments count 3×. Results have full weight for 12 months, half weight for the next 12, then expire. <a href="/ratings">How Rally ratings work</a> · Separate from USATT ratings.</p><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><h2>Club standings</h2><p>Time-weighted Elo · established players first</p></div></div>{rankings.length?<Standings limited/>:<div className="empty">Your players will appear here.</div>}</section><section className="matchup-panel"><h2>Head-to-head</h2>{data.players.length>=2?<><div className="matchup-avatars"><Avatar name={pname(ca)} photoUrl={photoUrl(ca)} large/><span>VS</span><Avatar name={pname(cb)} photoUrl={photoUrl(cb)} large/></div><div className="compare-picks"><PlayerSearchPicker label="First player" value={ca} onChange={v=>{setCompareA(v);if(v===cb)setCompareB(data.players.find(p=>p.id!==v)!.id)}} options={data.players}/><PlayerSearchPicker label="Second player" value={cb} onChange={setCompareB} options={data.players.filter(p=>p.id!==ca)}/></div><div className="h2h-score"><strong>{csA.wins}</strong><span>MATCH WINS</span><strong>{csB.wins}</strong></div><p className="h2h-note">{csA.played} confirmed meetings · {csA.gamesWon}–{csB.gamesWon} in games</p></>:<p className="h2h-note">Add at least two players to compare their records.</p>}</section></div><section className="panel"><div className="panel-heading"><h2>Recent results</h2><Button variant="ghost" onClick={()=>setTab('matches')}>All matches <ChevronRight size={16}/></Button></div><MatchList items={filtered.slice(0,5)}/></section></TabsContent>
 <TabsContent value="players"><div className="toolbar"><label className="searchbox"><Search size={18}/><Input placeholder="Search players" aria-label="Search players" value={search} onChange={e=>setSearch(e.target.value)}/></label><Pick label="Player club" value={club} onChange={setClub} options={[{id:'all',name:'All clubs'},...data.clubs]}/>{adminClubs.length>0&&<Button onClick={()=>open('guest')}><Plus size={16}/>Add guest player</Button>}</div><section className="panel">{rankings.length?<Standings/>:<p className="empty">No players found.</p>}</section><p className="footnote">Rally Elo starts at 1000, adjusts for opponent strength and weights single-club tournaments 2× and cross-club tournaments 3×. Five verified matches in the last 24 months establish a player. <a href="/ratings">How ratings work</a> · Not a USATT rating. Select a player, then open their public profile to share confirmed statistics. Guest profiles have no login.</p></TabsContent>
 <TabsContent value="matches"><div className="toolbar"><h2>{filtered.length} recorded matches</h2><Pick label="Match club" value={club} onChange={setClub} options={[{id:'all',name:'All clubs'},...data.clubs]}/></div><section className="panel"><MatchList items={filtered}/></section><p className="footnote">Pending and voided results are excluded from statistics. To correct a verified score, an administrator can void it and record the replacement.</p></TabsContent>
 <TabsContent value="clubs">{data.isSiteAdmin&&<section className="panel approval-panel"><div className="approval-heading"><span className="approval-icon"><ShieldCheck size={21}/></span><div><p className="eyebrow">SITE ADMIN</p><h2>Club approval</h2><p>Review new clubs before they appear publicly.</p></div><span className="approval-count">{pendingClubs.length} pending</span></div>{pendingClubs.length?<div className="approval-list">{pendingClubs.map(c=><div className="approval-row" key={c.id}><div className="approval-club"><strong>{c.name}</strong><span>{c.location} · {c.activeMemberCount} active member{c.activeMemberCount===1?'':'s'}</span></div><div className="approval-actions"><Button disabled={busy} size="sm" onClick={()=>act({action:'approve_club',clubId:c.id},'Club approved and published.')}>Approve</Button><Button disabled={busy} size="sm" variant="ghost" onClick={()=>act({action:'decline_club',clubId:c.id},'Club declined.')}>Decline</Button></div></div>)}</div>:<div className="approval-empty"><span><CheckCircle2 size={20}/></span><div><strong>All caught up</strong><p>No clubs are waiting for review.</p></div></div>}</section>}<div className="club-grid">{data.clubs.map((c,i)=><a className="club-card club-directory-link" key={c.id} href={`${demo?'/demo':''}/clubs/${c.id}`}><div className="club-banner" style={{background:i%2?'#bdd7ff':'#d9ed64'}}><span>{c.name.split(' ').slice(0,2).map(s=>s[0]).join('')}</span>{c.banner_url&&<img className="club-banner-image" src={c.banner_url} alt={`${c.name} banner`}/>}<Globe2 size={62} strokeWidth={1}/></div><div className="club-body">{c.photo_url&&<Avatar name={c.name} photoUrl={c.photo_url} large/>}<h2>{c.name}</h2><p>{c.location}</p>{c.bio&&<p className="club-summary">{c.bio}</p>}{c.approvalStatus!=='approved'&&<span className="badge">{c.approvalStatus==='pending'?'Awaiting Rally approval':'Not approved'}</span>}<div className="club-totals"><span><b>{c.activeMemberCount}</b> players</span><span><b>{data.matches.filter(m=>m.club_id===c.id&&m.status==='confirmed').length}</b> confirmed matches</span></div><span className="directory-view">View club →</span></div></a>)}</div>{!data.clubs.length&&<p className="empty">No approved clubs yet. Create one for review.</p>}<p className="footnote">New clubs appear publicly after Rally approval.</p></TabsContent>
 <TabsContent value="tournaments"><div className="toolbar"><label className="searchbox"><Search size={18}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search events, clubs, or locations" aria-label="Search tournaments"/></label><Pick label="Tournament status" value={eventStatus} onChange={setEventStatus} options={[{id:'all',name:'All tournaments'},{id:'registration',name:'Registration open'},{id:'active',name:'In progress'},{id:'completed',name:'Past tournaments'}]}/></div><div className="event-grid">{data.tournaments.filter(t=>(eventStatus==='all'||t.status===eventStatus)&&`${t.name} ${cname(t.club_id)} ${data.clubs.find(c=>c.id===t.club_id)?.location}`.toLowerCase().includes(search.toLowerCase())).map(t=><button className="event-card" key={t.id} onClick={()=>{setEvent(t.id)}}><div className="event-card-top"><CalendarDays size={30}/><span className="badge">{t.status==='registration'?'Registration open':t.status==='active'?'In progress':'Completed'}</span></div><h3>{t.name}</h3><p>{cname(t.club_id)}</p><div className="event-info"><span>{dateLabel(t.date)}</span><span>{t.format}</span></div><div className="event-bottom"><span>{data.entries.filter(e=>e.tournament_id===t.id).length} / {t.capacity} players</span><ChevronRight size={18}/></div></button>)}</div>{!data.tournaments.some(t=>(eventStatus==='all'||t.status===eventStatus)&&`${t.name} ${cname(t.club_id)} ${data.clubs.find(c=>c.id===t.club_id)?.location}`.toLowerCase().includes(search.toLowerCase()))&&<p className="empty">No tournaments found.</p>}<p className="footnote">Organizers lock the draw, record official results, and manage withdrawals. Tournament match results also update player statistics.</p></TabsContent>
 </main></Tabs>}
 <Dialog open={!!modal} onOpenChange={o=>{if(!o&&!busy&&!cropFile){if(modal==='match'&&matchMode==='live'&&liveDirty&&!window.confirm('Discard this live score? It has not been saved.'))return;setModal('');}}}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{({profile:'Your player profile',club:'Create a club',guest:'Add a guest player',match:'Record a match',event:'Create a tournament'} as Record<string,string>)[modal]}</DialogTitle><DialogDescription>{modal==='match'?'Games to 11, win by two.':modal==='profile'?'Choose the name shown on club rosters and results. Your account email is not displayed.':modal==='club'?'Verified accounts may submit one club. It remains private until a Rally app administrator approves it.':modal==='guest'?'For a player who has not signed in. This creates a roster entry, not a login account.':'Changes are saved to your clubhouse.'}</DialogDescription></DialogHeader><form className="form-stack" onSubmit={submit}>
 {modal==='profile'&&<div className="profile-photo-field"><span className="field-label">Profile photo (optional)</span><div className="profile-photo-controls"><Avatar name={formName||'Player'} photoUrl={photo===undefined?(data.me?photoUrl(data.me.id):null):photo} large/><div><label className="photo-picker">Choose photo<input type="file" accept="image/jpeg,image/png,image/webp" aria-label="Upload profile photo" disabled={busy||photoBusy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)setCropFile(file);}}/></label>{(photo===undefined?(data.me?photoUrl(data.me.id):null):photo)&&<Button type="button" variant="ghost" disabled={busy||photoBusy} onClick={()=>setPhoto(null)}>Remove photo</Button>}</div></div><p>Upload a clear photo of your face so other players can recognize you.</p><small>Shown on your public player profile. JPG, PNG, or WebP, up to 10 MB. Choose your crop before saving.</small>{photoBusy&&<p role="status">Preparing photo...</p>}</div>}
 {['profile','club','guest','event'].includes(modal)&&<label>{modal==='profile'||modal==='guest'?'Display name':modal==='club'?'Club name':'Tournament name'}<Input required maxLength={modal==='profile'||modal==='guest'?60:80} value={formName} onChange={e=>setFormName(e.target.value)}/></label>}
 {modal==='club'&&<label>City or location<Input required maxLength={100} value={location} onChange={e=>setLocation(e.target.value)} placeholder="e.g. Baltimore, MD"/></label>}
 {(['guest','event'].includes(modal)||(modal==='match'&&matchMode==='manual'))&&<label>Club<Pick label="Club" value={selectedClub} onChange={v=>{setSelectedClub(v);setA('');setB('')}} options={modal==='match'?myClubs:adminClubs}/></label>}
 {modal==='match'&&<><div className="score-mode" aria-label="Scoring method"><Button type="button" variant={matchMode==='manual'?'default':'outline'} aria-pressed={matchMode==='manual'} onClick={()=>{if(matchMode==='manual')return;if(matchMode==='live'&&liveDirty&&!window.confirm('Discard the live score and enter scores manually?'))return;setMatchMode('manual');setGames([['',''],['','']]);setLiveDirty(false);setLiveComplete(false);}}>Enter scores</Button><Button type="button" variant={matchMode==='live'?'default':'outline'} aria-pressed={matchMode==='live'} disabled={!a||!b} onClick={()=>{if(matchMode==='live')return;if(games.some(g=>g.some(v=>v.trim()))&&!window.confirm('Clear the entered scores and start live scoring?'))return;liveGamesRef.current=null;setMatchMode('live');setGames([]);setLiveDirty(false);setLiveComplete(false);}}>Live points</Button></div>{matchMode==='manual'?<><div className="form-two"><label>Player one<Pick label="Player one" value={a} onChange={v=>{setA(v);if(v===b)setB('');}} options={eligible}/></label><label>Player two<Pick label="Player two" value={b} onChange={setB} options={eligible.filter(p=>p.id!==a)}/></label></div>{eligible.length<2&&<p className="footnote">Your club needs two players. An administrator can add guests from the Players tab.</p>}<label>Match format<Pick label="Match format" value={format} onChange={setFormat} options={['3','5','7'].map(n=>({id:n,name:`Best of ${n}`}))}/></label><div className="game-header"><span>Game</span><span>Player 1</span><span>Player 2</span><span/></div>{games.map((g,i)=><div className="game-input" key={i}><span>{i+1}</span>{g.map((v,j)=><Input key={j} aria-label={`Game ${i+1}, player ${j+1} score`} type="number" inputMode="numeric" min="0" max="999" value={v} onChange={e=>setGames(gs=>gs.map((row,k)=>k===i?row.map((s,z)=>z===j?e.target.value:s) as [string,string]:row))}/>)}<Button type="button" variant="ghost" aria-label={`Remove game ${i+1}`} onClick={()=>setGames(gs=>gs.filter((_,k)=>k!==i))}><X size={16}/></Button></div>)}<Button type="button" variant="outline" disabled={games.length>=Number(format)} onClick={()=>setGames(gs=>[...gs,['','']])}>Add game</Button></>:<><p className="live-match-context">{cname(selectedClub)} · Best of {format} · {dateLabel(date)}</p><LivePointsTracker names={[pname(a),pname(b)]} bestOf={Number(format)} disabled={busy} onChange={state=>{if(liveGamesRef.current!==state.games){liveGamesRef.current=state.games;setGames(state.games.map(g=>g.map(String) as [string,string]));}setLiveComplete(state.complete);setLiveDirty(state.history.length>0);}}/><p className="footnote">Save result after the match to add it to your club history.</p></>}<p className="footnote">{data.clubs.find(c=>c.id===selectedClub)?.canManage?'As an administrator, your result is verified immediately.':'Your opponent or an administrator must confirm this result.'}</p></>}

 {((modal==='match'&&matchMode==='manual')||modal==='event')&&<label>Date<Input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>}
 {modal==='event'&&<><label>Format<Pick label="Event format" value={eventFormat} onChange={setEventFormat} options={['Single elimination','Double elimination','Round robin'].map(s=>({id:s,name:s}))}/></label><label>Maximum players<Input aria-label="Maximum players" type="number" min="2" step="1" required inputMode="numeric" value={capacity} onChange={e=>setCapacity(e.target.value)}/><small>Any whole number of 2 or more. The actual field determines the draw; uneven fields receive byes.</small></label></>}
 {error&&<p className="error" role="alert">{error}</p>}<Button className="primary-action" type="submit" disabled={busy||photoBusy||!!cropFile||!data.signedIn||(modal==='club'&&!canCreateClub)||(modal==='match'&&(!a||!b||(matchMode==='live'&&!liveComplete)))}>{busy?'Saving…':modal==='match'?'Save result':'Save'}</Button></form></DialogContent></Dialog>
 <Sheet open={!!profile} onOpenChange={o=>{if(!o)setProfile(null)}}><SheetContent className="detail-sheet">{selectedPlayer&&<><SheetHeader><Avatar name={selectedPlayer.name} photoUrl={selectedPlayer.photo_url} large/><SheetTitle className="detail-title">{selectedPlayer.name}</SheetTitle><SheetDescription>{selectedPlayer.is_guest?'Guest player':'Player profile'} · All clubs</SheetDescription><a className="public-page-link" href={`${demo?'/demo':''}/players/${selectedPlayer.id}`}>Open public profile</a></SheetHeader><div className="sheet-body">{(()=>{const s=stats(selectedPlayer.id,toMatches(data.matches));return <><div className="profile-stats"><div><strong>{s.wins}–{s.losses}</strong><span>Match record</span></div><div><strong>{s.played?s.winRate+'%':'—'}</strong><span>Win rate</span></div></div><div className="detail-row"><span>Games won / lost</span><b>{s.gamesWon} / {s.gamesLost}</b></div><div className="detail-row"><span>Points won / conceded</span><b>{s.pointsWon} / {s.pointsLost}</b></div><h3>Head-to-head records</h3>{data.players.filter(p=>p.id!==selectedPlayer.id).map(p=>{const h=stats(selectedPlayer.id,toMatches(data.matches.filter(m=>(m.a===p.id&&m.b===selectedPlayer.id)||(m.b===p.id&&m.a===selectedPlayer.id))));return h.played?<div className="detail-row" key={p.id}><span>{p.name}</span><b>{h.wins}–{h.losses}</b></div>:null})}{!s.played&&<p className="empty">No confirmed matches yet.</p>}<h3>Clubs</h3>{data.memberships.filter(m=>m.player_id===selectedPlayer.id&&m.status==='active').map(m=><div className="detail-row" key={m.club_id}>{cname(m.club_id)}<span>{m.role}</span></div>)}</>})()}</div></>}</SheetContent></Sheet>
 <PhotoCropper file={cropFile} onCancel={()=>setCropFile(null)} onApply={photo=>{setPhoto(photo);setCropFile(null);}}/>
 <TournamentPanel publicBase={demo?'/demo/tournaments':'/tournaments'} event={eventDetail??null} onClose={()=>setEvent(null)} players={data.players} entries={eventPlayers} candidates={candidates} admin={!!eventDetail&&!!data.clubs.find(c=>c.id===eventDetail.club_id)?.canManage} me={data.me?.id??null} clubName={eventDetail?cname(eventDetail.club_id):''} busy={busy} act={act}/>
 <AlertDialog open={!!voidId} onOpenChange={o=>{if(!o)setVoidId(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Void this result?</AlertDialogTitle><AlertDialogDescription>The match stays in the history, but its scores stop contributing to player statistics. Record a new match if you need to replace an incorrect score.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();if(await act({action:'void_match',id:voidId},'Result voided. Statistics updated.'))setVoidId(null)}}>Void result</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>;
}
function toMatches(ms:Result[]):Match[]{return ms.filter(m=>m.status==='confirmed').map(m=>({id:m.id,a:m.a,b:m.b,games:m.games,date:m.played_on,club:m.club_id,status:'confirmed',kind:m.tournament_id?'Tournament':'Club play'}))}
