'use client';
import CleanSelect from './clean-select';
/* eslint-disable react-hooks/set-state-in-effect */
import RatingTrend from './rating-trend';
import {useEffect,useState} from 'react';
import {ratingHistory,type SeedMatch,ESTABLISHED_MATCHES,DEFAULT_INITIAL_RATING} from '@/lib/seeding';
const points=(n:number)=>`${n>0?'+':''}${n.toFixed(1)}`;
export default function RatingHistory({matches,playerId,name,clubs=[],initialClub='all',demo=false,publicView=false}:{matches:(SeedMatch&{club_id?:string})[];demo?:boolean;publicView?:boolean;clubs?:{id:string;name:string}[];initialClub?:string;playerId:string;name:(id:string)=>string}){
 const [expanded,setExpanded]=useState(false),[scope,setScope]=useState(initialClub);
 const [snapshot,setSnapshot]=useState<ReturnType<typeof ratingHistory>|null>(null),[loading,setLoading]=useState(!demo),[error,setError]=useState('');
 useEffect(()=>{if(demo)return;let current=true;setLoading(true);setError('');fetch('/api/rally?view='+(publicView?'performance':'rating')+'&'+new URLSearchParams({player:playerId,club:scope}).toString(),{cache:'no-store'}).then(async r=>{const body=await r.json() as ReturnType<typeof ratingHistory>&{error?:string};if(!r.ok)throw new Error(body.error||'Could not load rating history.');if(current)setSnapshot(publicView?(body as unknown as {history:ReturnType<typeof ratingHistory>}).history:body);}).catch(e=>{if(current)setError(e.message)}).finally(()=>{if(current)setLoading(false)});return()=>{current=false}},[demo,playerId,scope,matches,publicView]);
 const history=demo?ratingHistory(scope==='all'?matches:matches.filter(m=>m.club_id===scope),playerId):snapshot??{rating:DEFAULT_INITIAL_RATING,distinctOpponents:0,played:0,changes:[],asOf:new Date().toISOString().slice(0,10)};const scopeName=scope==='all'?(publicView?'Approved clubs':'All clubs visible to you'):clubs.find(c=>c.id===scope)?.name??'Selected club';
 return <section className="rating-history"><h3>Rally rating history</h3>{clubs.length>0&&<div className="rating-scope"><label htmlFor="rating-club">Rating scope</label><CleanSelect id="rating-club" value={scope} onChange={e=>{setScope(e.target.value);setExpanded(false)}}><option value="all">All clubs</option>{clubs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</CleanSelect></div>}{error&&<p role="alert">{error}</p>}{loading?<p role="status">Loading rating history…</p>:<><div className="rating-summary"><strong>{history.changes.length?Math.round(history.rating):'Unrated'}</strong><span>{history.played<ESTABLISHED_MATCHES?`Provisional · ${history.played}/${ESTABLISHED_MATCHES} recent matches`:`Established · ${history.played} recent matches`}</span><span>{history.distinctOpponents} distinct {history.distinctOpponents===1?'opponent':'opponents'} · last 24 months</span></div><RatingTrend key={scope} name={name} changes={history.changes} rating={history.rating} asOf={history.asOf}/><p>{scopeName} · as of {history.asOf}. Separate from USATT ratings. <a href="/ratings">How ratings work</a></p><p>USATT-style points use both players’ ratings at the start of the event day. Its contribution today is full for 12 months, half for the next 12, then zero. Aging can change your total without a new match.</p>{history.changes.length? <><ol className="rating-change-list">{(expanded?history.changes:history.changes.slice(0,10)).map((c,index)=><li key={c.matchId}><details open={index===0}><summary className="rating-change-heading"><b>{c.won?'Win':'Loss'} vs {name(c.opponentId)}</b><span>{c.date} · {points(c.delta)}</span></summary><dl><div><dt>Rating before → after</dt><dd>{c.before.toFixed(1)} → {c.after.toFixed(1)}</dd></div><div><dt>Opponent rating before</dt><dd>{c.opponentRating.toFixed(1)}</dd></div><div><dt>Base point exchange</dt><dd>{c.pointExchange??'—'}</dd></div>{!!c.adjustment&&<div><dt>Underrated-player adjustment</dt><dd>{points(c.adjustment)} before this event · ages with results</dd></div>}<div><dt>Match weight</dt><dd>{c.eventWeight===3?'Cross-club tournament · 3×':c.eventWeight===2?'Tournament · 2×':'Regular match · 1×'}</dd></div><div><dt>Match format weight</dt><dd>{Math.round((c.formatWeight??1)*100)}%{c.formatWeight===.33?' · Single game':''}</dd></div><div><dt>Repeated-opponent weight</dt><dd>{Math.round(c.repeatWeight*100)}% · match {c.pairMatchNumber} against this opponent in 30 days</dd></div><div><dt>Original change</dt><dd>{points(c.delta)}</dd></div><div><dt>Match + adjustment today</dt><dd>{points(c.currentContribution)} · {c.ageWeight===0?'Expired':c.ageWeight===.5?'Half weight':'Full weight'}</dd></div></dl></details></li>)}</ol>{history.changes.length>10&&<button className="standings-expand" aria-expanded={expanded} onClick={()=>setExpanded(v=>!v)}>{expanded?'Show recent 10':`Show all ${history.changes.length} rated matches`}</button>}</>:<p>No rated matches yet. Confirmed results will appear here.</p>}</>}</section>;
}
