'use client';
import {useState} from 'react';
import type {RatingChange} from '@/lib/seeding';
import {Button} from '@/components/ui/button';
const signed=(value:number)=>`${value>0?'+':''}${value.toFixed(1)}`;
export default function RatingTrend({changes,rating,asOf,name}:{changes:RatingChange[];rating:number;asOf:string;name:(id:string)=>string}){
 const recent=changes.slice(0,20).reverse();
 const samples=[...(recent.length?[{id:'baseline',date:recent[0].date,value:recent[0].before,change:null,label:'Before first plotted match'},...recent.map(c=>({id:c.matchId,date:c.date,value:c.after,change:c,label:`${c.date} · ${c.won?'Win':'Loss'} vs ${name(c.opponentId)}`}))]:[]),{id:'today',date:asOf,value:rating,change:null,label:'Today’s rating'}];
 const [selectedId,setSelectedId]=useState('today');if(!recent.length)return null;
 const index=Math.max(0,samples.findIndex(s=>s.id===selectedId)),selected=samples[index],values=samples.map(p=>p.value),min=Math.floor(Math.min(...values)/25)*25-25,max=Math.ceil(Math.max(...values)/25)*25+25,first=Date.parse(samples[0].date),last=Date.parse(asOf),x=(date:string)=>40+(Date.parse(date)-first)/Math.max(last-first,86400000)*290,y=(value:number)=>110-(value-min)/(max-min)*90;
 return <figure className="rating-trend"><svg viewBox="0 0 360 150" role="group" aria-label="Interactive Rally rating trend"><text x="2" y="24">{max}</text><text x="2" y="112">{min}</text><line x1="40" x2="330" y1="110" y2="110" stroke="currentColor" opacity=".25"/><polyline points={samples.map(p=>`${x(p.date)},${y(p.value)}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="2.5"/>{samples.map(p=><g key={p.id} role="button" tabIndex={0} aria-label={`${p.label}: ${p.value.toFixed(1)}`} aria-pressed={selected.id===p.id} onClick={()=>setSelectedId(p.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelectedId(p.id)}}}><circle cx={x(p.date)} cy={y(p.value)} r="13" fill="transparent"/><circle cx={x(p.date)} cy={y(p.value)} r={selected.id===p.id?5:3} fill="currentColor" pointerEvents="none"/></g>)}<text x="40" y="139">{samples[0].date}</text><text x="330" y="139" textAnchor="end">Today</text></svg><label>Inspect rating point<select aria-label="Inspect rating point" value={selected.id} onChange={e=>setSelectedId(e.target.value)}>{samples.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><div className="rating-point-controls"><Button size="sm" variant="outline" disabled={index===0} onClick={()=>setSelectedId(samples[index-1].id)}>Previous point</Button><Button size="sm" variant="outline" disabled={index===samples.length-1} onClick={()=>setSelectedId(samples[index+1].id)}>Next point</Button></div><div className="rating-point-detail" role="status" aria-live="polite"><b>{selected.label}</b><p>{selected.date} · Rating {selected.value.toFixed(1)}</p>{selected.change?<><p>Original change {signed(selected.change.delta)} · {selected.change.before.toFixed(1)} → {selected.change.after.toFixed(1)}</p><p>{selected.change.eventWeight===3?'Cross-club tournament':selected.change.eventWeight===2?'Tournament':'Club match'} · Contribution today {signed(selected.change.currentContribution)}</p></>:<p>{selected.id==='today'?'Includes today’s time weighting.':'Historical rating before the first match shown.'}</p>}</div><figcaption>Tap a point, or use the selector when matches share a date. Last {recent.length} match updates and today’s rating; aging is reflected at the next plotted update.</figcaption></figure>;
}
