'use client';
/* eslint-disable react-hooks/set-state-in-effect, @next/next/no-location-assign-relative-destination */
import {useCallback,useEffect,useRef,useState} from 'react';
import PublicHeader from './public-header';
import AccountMenu from './account-menu';
import TournamentPanel from './tournament-panel';
import {createDemoData,applyDemoAction} from '@/lib/demo-state';
import type {Data} from './rally-app';
import {Button} from '@/components/ui/button';
type Detail={event:Data['tournaments'][number];players:Data['players'];entries:Data['entries'];memberships:Data['memberships']};
export default function TournamentWorkspace({id,demo=false}:{id:string;demo?:boolean}){
 const [data,setData]=useState<Data|null>(demo?createDemoData():null),[detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[fixture,setFixture]=useState<string|undefined>();
 const reading=useRef<AbortController|null>(null),mutating=useRef(false),version=useRef(0),mounted=useRef(false);
 const invalidate=useCallback(()=>{version.current++;reading.current?.abort();},[]);
 const refresh=useCallback(async(force=false)=>{if(demo||mutating.current||(!force&&reading.current))return;reading.current?.abort();const controller=new AbortController();reading.current=controller;const revision=++version.current;try{const r=await fetch('/api/rally?view=event&event='+encodeURIComponent(id),{cache:'no-store',signal:controller.signal});if(r.status===401){window.location.assign('/login?next='+encodeURIComponent('/tournaments/'+id+'/manage'));return;}const event=await r.json() as Detail&{error?:string};if(!r.ok)throw new Error(event.error||'Could not load tournament.');const result=await fetch('/api/rally?compact=1&clubScope='+encodeURIComponent(event.event.club_id),{cache:'no-store',signal:controller.signal});if(!result.ok)throw new Error('Could not load your tournament permissions.');const next=await result.json() as Data;if(mounted.current&&revision===version.current){setData(next);setDetail(event);setError('');}}catch(e){if(!controller.signal.aborted&&mounted.current&&revision===version.current)setError(e instanceof Error?e.message:'Could not load tournament.');}finally{if(reading.current===controller)reading.current=null;if(mounted.current&&revision===version.current)setLoading(false);}},[demo,id]);
 useEffect(()=>{mounted.current=true;setFixture(new URLSearchParams(window.location.search).get('fixture')??undefined);if(demo){try{const saved=sessionStorage.getItem('rally-demo-preview');setData(saved?JSON.parse(saved):createDemoData());}catch{}setLoading(false);}else void refresh(true);const resume=()=>{if(document.visibilityState==='visible')void refresh();},timer=setInterval(resume,15000);window.addEventListener('focus',resume);return()=>{mounted.current=false;invalidate();clearInterval(timer);window.removeEventListener('focus',resume);};},[demo,refresh,invalidate]);
 async function act(payload:Record<string,unknown>,message:string){if(mutating.current)return false;mutating.current=true;version.current++;reading.current?.abort();setBusy(true);setError('');setNotice('');try{if(demo&&data){const next=applyDemoAction(data,payload);sessionStorage.setItem('rally-demo-preview',JSON.stringify(next));setData(next);}else{const r=await fetch('/api/rally',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Could not save tournament.');}setNotice(message+(demo?' Sample data only.':''));if(payload.action==='delete_tournament'){window.location.assign((demo?'/demo':'/clubhouse')+'?tab=tournaments');return true;}mutating.current=false;await refresh(true);return true;}catch(e){setError(e instanceof Error?e.message:'Could not save tournament.');return false;}finally{mutating.current=false;setBusy(false);}}
 const event=demo?data?.tournaments.find(t=>t.id===id):detail?.event,people=demo?data?.players??[]:detail?.players??[],members=demo?data?.memberships??[]:detail?.memberships??[],entries=(demo?data?.entries??[]:detail?.entries??[]).filter(e=>e.tournament_id===id).map(e=>e.player_id),club=data?.clubs.find(c=>c.id===event?.club_id),candidates=people.filter(p=>!entries.includes(p.id)&&members.some(m=>m.player_id===p.id&&m.club_id===event?.club_id&&m.status==='active'));
 return <><PublicHeader account={demo&&data?.me?<AccountMenu demo name={data.me.name} profileHref={'/demo/players/'+data.me.id}/>:undefined}/>{demo&&<div className="demo-note">Sample tournament · changes stay in this browser session</div>}<main className="public-page tournament-page"><a className="club-back-link" href={(demo?'/demo':'/clubhouse')+'?tab=tournaments'}>All tournaments</a><div className="tournament-live-status"><span>{demo?'Sample data':'Auto refresh · every 15 seconds'}</span>{!demo&&<Button variant="outline" disabled={busy} onClick={()=>void refresh()}>Refresh tournament</Button>}</div>{error&&<p className="auth-error" role="alert">{error}</p>}{notice&&<p className="auth-success" role="status">{notice}</p>}{loading?<p role="status">Loading tournament…</p>:event?<TournamentPanel fullPage event={event} initialFixture={fixture} publicBase={demo?'/demo/tournaments':'/tournaments'} onClose={()=>window.location.assign((demo?'/demo':'/clubhouse')+'?tab=tournaments')} players={people} entries={entries} candidates={candidates} admin={!!club?.canManage} me={data?.me?.id??null} clubName={club?.name??''} busy={busy} act={act}/>:<p>Tournament unavailable.</p>}</main></>;
}
