'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import PlayerSearchPicker from './player-search-picker';
import {TimeLabel,localInput,utcInput} from './time-label';
import type {Tournament} from './tournament-panel';
type Props={event:Tournament;busy:boolean;act:(payload:Record<string,unknown>,message:string)=>Promise<boolean>};
export function ScorekeeperSettings({event:t,busy,act,players}:{players:{id:string;name:string}[]} & Props){
 const [player,setPlayer]=useState(''),available=players.filter(p=>!t.scorekeepers?.includes(p.id));
 return <section className="event-logistics"><h3>Scorekeepers</h3><p>Scorekeepers enter played results for this tournament. They cannot change registration, scheduling, seeds, forfeits or results already recorded.</p>{(t.scorekeepers??[]).map(id=><div className="entrant-row" key={id}><span>{players.find(p=>p.id===id)?.name??'Player'}</span><span className="badge">Scorekeeper</span><Button disabled={busy} variant="ghost" onClick={()=>void act({action:'set_scorekeeper',id:t.id,revision:t.revision,operationId:crypto.randomUUID(),playerId:id,enabled:false},'Scorekeeper access removed.')}>Remove</Button></div>)}{!!available.length&&<div className="entry-control"><PlayerSearchPicker label="Scorekeeper" value={player} onChange={setPlayer} options={available}/><Button disabled={busy||!available.some(p=>p.id===player)} onClick={async()=>{if(await act({action:'set_scorekeeper',id:t.id,revision:t.revision,operationId:crypto.randomUUID(),playerId:player,enabled:true},'Scorekeeper appointed.'))setPlayer('')}}>Appoint scorekeeper</Button></div>}</section>;
}
export function AutomaticSchedule({event:t,busy,act}:Props){
 return <section className="event-logistics"><h3>Table schedule</h3>{t.estimated_ends_at&&<p>Estimated finish: <TimeLabel value={t.estimated_ends_at}/></p>}<p>Estimates allow for bracket dependencies and players’ other matches. Called matches keep their table. Rebuild after delays; a reset final is included if it may be needed.</p><form className="session-form" onSubmit={e=>{e.preventDefault();const fields=new FormData(e.currentTarget);if(window.confirm('Replace the remaining estimated table/time assignments? Called matches stay assigned.'))void act({action:'schedule_tournament',id:t.id,revision:t.revision,operationId:crypto.randomUUID(),tableCount:Number(fields.get('tables')),matchMinutes:Number(fields.get('minutes')),startsAt:utcInput(String(fields.get('start')??''))},'Table schedule and finish estimate updated.');}}><div className="form-two"><label>Tables<input name="tables" type="number" min={1} max={64} step={1} required defaultValue={t.table_count??1}/></label><label>Minutes per match<input name="minutes" type="number" min={5} max={120} step={1} required defaultValue={t.estimated_match_minutes??20}/></label></div><label>Schedule from (your time zone)<input name="start" type="datetime-local" defaultValue={localInput(t.starts_at)}/></label><Button type="submit" disabled={busy}>Generate table schedule</Button></form></section>;
}
