'use client';
import {TimeLabel} from './time-label';
import {Button} from '@/components/ui/button';
import type {Tournament} from './tournament-panel';
import {registrationClosed} from '@/lib/logistics';
export default function TournamentRegistration({event:t,me,entered,hostMember,admin,name,busy,act}:{event:Tournament;me:string|null;entered:boolean;hostMember:boolean;admin:boolean;name:(id:string)=>string;busy:boolean;act:(payload:Record<string,unknown>,message:string)=>Promise<boolean>}){
 const closed=registrationClosed(t),waiting=t.waitlist?.find(w=>w.player_id===me),full=(t.entry_count??0)>=t.capacity||!!t.waitlist_count,eligible=!!me&&(hostMember||!!t.allow_visitors);
 const action=(type:string,playerId=me)=>void act({action:type,id:t.id,revision:t.revision,operationId:crypto.randomUUID(),playerId},type==='join_waitlist'?'Added to the waitlist.':type==='leave_waitlist'?'Left the waitlist.':'You are registered.');
 return <section className="registration-options"><p>{t.allow_visitors?'Visiting players welcome. Host-club membership is not required.':'Registration is for active host-club members.'}</p>{!me&&<p>Create your player profile in Account settings before registering.</p>}{waiting?<div className="dashboard-callout"><p>You are #{waiting.position} on the waitlist. Places are offered in joining order while registration is open.</p>{waiting.claim_expires_at&&<><p>Your place is reserved until <TimeLabel value={waiting.claim_expires_at}/>.</p><Button disabled={busy} onClick={()=>action('claim_waitlist_place')}>Claim place</Button></>}<Button variant="outline" disabled={busy} onClick={()=>action('leave_waitlist')}>Leave waitlist</Button></div>:!entered&&!closed&&eligible&&<Button disabled={busy} onClick={()=>action(full?'join_waitlist':'enter_tournament')}>{full?'Join waitlist':'Register yourself'}</Button>}{!entered&&!eligible&&me&&!closed&&<p>Join the host club to enter this members-only event.</p>}{!!t.waitlist_count&&<p>{t.waitlist_count} waiting · places are reserved with a claim deadline when an entrant leaves or the limit increases before registration closes. Remaining waitlist entries close when the draw starts.</p>}{admin&&!!t.waitlist?.length&&<details><summary>Manage waitlist ({t.waitlist_count})</summary>{t.waitlist.map(w=><div className="entrant-row" key={w.player_id}><span>#{w.position}</span><span>{name(w.player_id)}{w.claim_expires_at&&<small>Claim by <TimeLabel value={w.claim_expires_at}/></small>}</span>{w.claim_expires_at&&<Button disabled={busy} onClick={()=>action('claim_waitlist_place',w.player_id)}>Confirm attendance</Button>}<Button variant="ghost" disabled={busy} onClick={()=>action('leave_waitlist',w.player_id)}>Remove from waitlist</Button></div>)}</details>}</section>;
}
