import {AppError} from './rally-errors';
import {calculateRatings,compareRatedPlayers,initialRating,type SeedMatch} from './seeding';
export type ClubSeason={id:string;club_id:string;name:string;starts_on:string;ends_on:string;closed_at:string|null;created_by:string|null;revision:number;created_at:string};
export type SeasonPlayer={player_id:string;name:string;status:string;rating:number;played:number;wins:number;rank:number|null};
export type SeasonView=ClubSeason&{players:SeasonPlayer[];canManage:boolean;canJoin:boolean;me:string|null;asOf:string};
export function seasonStandings(season:ClubSeason,roster:{player_id:string;name:string;status:string;initial_rating?:number|null}[],matches:SeedMatch[],today=new Date().toISOString().slice(0,10)){
 const asOf=[today,season.ends_on,...(season.closed_at?[season.closed_at.slice(0,10)]:[])].sort()[0],ids=new Set(roster.map(p=>p.player_id));
 const ratings=calculateRatings(matches.filter(m=>m.played_on>=season.starts_on&&m.played_on<=asOf&&ids.has(m.a)&&ids.has(m.b)),asOf,Object.fromEntries(roster.filter(p=>p.initial_rating!=null).map(p=>[p.player_id,p.initial_rating!])));
 let rank=0;const players=roster.map(p=>({...p,...(ratings.get(p.player_id)??{rating:initialRating(p.initial_rating),played:0,wins:0})})).sort((a,b)=>Number(b.status==='active')-Number(a.status==='active')||compareRatedPlayers(a,b)||a.name.localeCompare(b.name)||a.player_id.localeCompare(b.player_id)).map(p=>({...p,rating:Math.round(p.rating),rank:p.status==='active'?++rank:null}));return {players,asOf};
}
export async function seasonViews(db:D1Database,club:string,me:string|null){
 const membership=me?await db.prepare("SELECT role FROM memberships WHERE club_id=? AND player_id=? AND status='active'").bind(club,me).first<{role:string}>():null,canManage=!!membership&&['owner','admin','board'].includes(membership.role);
 const visible=await db.prepare("SELECT 1 FROM clubs WHERE id=? AND (approval_status='approved' OR ?=1)").bind(club,membership?1:0).first();if(!visible)throw new AppError(404,'Club unavailable.');
 const seasons=(await db.prepare('SELECT * FROM club_seasons WHERE club_id=? ORDER BY starts_on DESC,id').bind(club).all<ClubSeason>()).results;
 const matches=(await db.prepare("SELECT m.*,t.rating_weight tournament_weight,pa.initial_rating a_initial_rating,pb.initial_rating b_initial_rating FROM matches m LEFT JOIN profiles pa ON pa.id=m.a LEFT JOIN profiles pb ON pb.id=m.b LEFT JOIN tournaments t ON t.id=m.tournament_id WHERE m.club_id=? AND m.status='confirmed' AND t.deleted_at IS NULL ORDER BY m.played_on DESC,m.created_at DESC").bind(club).all<SeedMatch>()).results;
 return await Promise.all(seasons.map(async s=>{const roster=(await db.prepare('SELECT sp.player_id,p.name,sp.status,p.initial_rating FROM season_players sp JOIN profiles p ON p.id=sp.player_id WHERE sp.season_id=?').bind(s.id).all<{player_id:string;name:string;status:string;initial_rating:number|null}>()).results;return {...s,...seasonStandings(s,roster,matches),me,canManage,canJoin:!!membership&&!s.closed_at&&s.ends_on>=new Date().toISOString().slice(0,10)&&!roster.some(p=>p.player_id===me&&p.status==='active')} satisfies SeasonView;}));
}
function identifier(value:unknown){if(typeof value!=='string'||!/^[a-zA-Z0-9_-]{1,80}$/.test(value))throw new AppError(400,'Invalid identifier.');return value;}
function date(value:unknown){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(Date.parse(value))||new Date(value).toISOString().slice(0,10)!==value)throw new AppError(400,'Choose valid season dates.');return value;}
export async function seasonAction(db:D1Database,user:string,body:Record<string,unknown>){
 const action=String(body.action),id=identifier(body.id),now=new Date().toISOString(),q=(sql:string,...args:unknown[])=>db.prepare(sql).bind(...args);
 const club=action==='create_season'?identifier(body.clubId):(await q('SELECT club_id FROM club_seasons WHERE id=?',id).first<{club_id:string}>())?.club_id;if(!club)throw new AppError(404,'Season unavailable.');
 const member=await q("SELECT role FROM memberships WHERE club_id=? AND player_id=? AND status='active'",club,user).first<{role:string}>(),admin=!!member&&['owner','admin','board'].includes(member.role);
 const leader="EXISTS(SELECT 1 FROM memberships WHERE club_id=? AND player_id=? AND status='active' AND role IN ('owner','admin','board'))";
 if(action==='create_season'){
  if(!admin)throw new AppError(403,'Only club organizers can create seasons.');const start=date(body.startsOn),end=date(body.endsOn);if(end<start||end<now.slice(0,10))throw new AppError(400,'The season must end on or after today and its start date.');if(typeof body.name!=='string'||!body.name.trim()||body.name.trim().length>80)throw new AppError(400,'Enter a season name of 1–80 characters.');
  const old=await q('SELECT * FROM club_seasons WHERE id=?',id).first<ClubSeason>();if(old){if(old.created_by===user&&old.club_id===club&&old.name===body.name.trim()&&old.starts_on===start&&old.ends_on===end)return {ok:true};throw new AppError(409,'This season ID is already used.');}
  try{await db.batch([q(`INSERT INTO club_seasons(id,club_id,name,starts_on,ends_on,created_by,created_at) SELECT ?,?,?,?,?,?,? WHERE ${leader}`,id,club,body.name.trim(),start,end,user,now,club,user),q('INSERT INTO account_change_guards(changed) VALUES(changes())'),q("INSERT INTO season_players(season_id,player_id,created_at) SELECT ?,p.id,? FROM memberships m JOIN profiles p ON p.id=m.player_id WHERE m.club_id=? AND m.status='active' AND p.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM account_deletions d WHERE d.auth_id=p.auth_id)",id,now,club)]);}catch{throw new AppError(409,'Club access changed. Refresh before creating the season.');}return {ok:true};
 }
 const season=(await q('SELECT * FROM club_seasons WHERE id=?',id).first<ClubSeason>())!;if(body.revision!==season.revision)throw new AppError(409,'The season changed. Refresh and try again.');if(season.closed_at||season.ends_on<now.slice(0,10))throw new AppError(409,'This season is finished.');
 if(action==='close_season'){
  if(!admin)throw new AppError(403,'Only a club organizer can close the season.');if(body.confirmation!=='CLOSE')throw new AppError(400,'Confirm closing the season.');
  const result=await q(`UPDATE club_seasons SET closed_at=?,revision=revision+1 WHERE id=? AND revision=? AND closed_at IS NULL AND ${leader}`,now,id,season.revision,club,user).run();if(result.meta.changes!==1)throw new AppError(409,'Season or access changed.');return {ok:true};
 }
 if(action!=='join_season'&&action!=='withdraw_season')throw new AppError(400,'Unknown season action.');const player=identifier(body.playerId);if(player!==user&&!admin)throw new AppError(403,'Only organizers can manage other ladder players.');
 if(action==='join_season'&&!await q("SELECT 1 FROM memberships m JOIN profiles p ON p.id=m.player_id WHERE m.club_id=? AND m.player_id=? AND m.status='active' AND p.deleted_at IS NULL",club,player).first())throw new AppError(403,'Join the club before entering its ladder.');
 try{await db.batch([q(`UPDATE club_seasons SET revision=revision+1 WHERE id=? AND revision=? AND closed_at IS NULL AND ends_on>=? AND ((${leader}) OR (?=? AND EXISTS(SELECT 1 FROM memberships WHERE club_id=? AND player_id=? AND status='active')))`,id,season.revision,now.slice(0,10),club,user,player,user,club,user),q('INSERT INTO account_change_guards(changed) VALUES(changes())'),action==='join_season'?q("INSERT INTO season_players(season_id,player_id,created_at) SELECT ?,?,? WHERE EXISTS(SELECT 1 FROM profiles p JOIN memberships m ON m.player_id=p.id WHERE p.id=? AND p.deleted_at IS NULL AND m.club_id=? AND m.status='active' AND NOT EXISTS(SELECT 1 FROM account_deletions d WHERE d.auth_id=p.auth_id)) ON CONFLICT(season_id,player_id) DO UPDATE SET status='active'",id,player,now,player,club):q("UPDATE season_players SET status='withdrawn' WHERE season_id=? AND player_id=?",id,player),...(action==='join_season'?[q('INSERT INTO account_change_guards(changed) VALUES(changes())')]:[])]);}catch{throw new AppError(409,'Season or membership changed. Refresh and try again.');}return {ok:true};
}
