import type {Draw} from './tournament-engine';
import {registrationClosed} from './logistics';

type Source={me:{id:string;name:string}|null;clubs:{id:string;name:string;canManage:boolean}[];players:{id:string;name:string}[];memberships:{club_id:string;player_id:string;status:string}[];matches:{id:string;a:string;b:string;club_id:string;status:string;canConfirm:boolean}[];entries:{tournament_id:string;player_id:string}[];tournaments:{id:string;name:string;club_id:string;date:string;status:string;capacity:number;registration_closes_at?:string|null;starts_at?:string|null;check_in_open?:number;allow_visitors?:number;waitlist?:{player_id:string;position:number}[];waitlist_count?:number;checkedIn?:string[];state:Draw|null;fixturePlans?:{fixture_id:string;court:string;starts_at:string|null}[]}[]};
export function dashboardsFor(data:Source,now=new Date()){
 const me=data.me?.id,name=(id:string|null)=>data.players.find(p=>p.id===id)?.name??'Player',today=now.toISOString().slice(0,10);
 const managed=new Set(data.clubs.filter(c=>c.canManage).map(c=>c.id)),mine=new Set(data.memberships.filter(m=>m.player_id===me&&m.status==='active').map(m=>m.club_id));
 const events=data.tournaments.filter(t=>t.status!=='completed'&&(t.status==='active'||t.date>=today)).map(t=>{
  const entries=data.entries.filter(e=>e.tournament_id===t.id),entered=entries.some(e=>e.player_id===me),checked=new Set(t.checkedIn??[]);
  const ready=(t.state?.fixtures??[]).filter(f=>f.status==='ready').map(f=>{const plan=t.fixturePlans?.find(p=>p.fixture_id===f.id);return {id:f.id,a:f.a,b:f.b,label:`${name(f.a)} vs ${name(f.b)}`,court:plan?.court??'',startsAt:plan?.starts_at??null,mine:f.a===me||f.b===me,checkedIn:!!f.a&&!!f.b&&checked.has(f.a)&&checked.has(f.b)};});
  return {id:t.id,name:t.name,clubId:t.club_id,clubName:data.clubs.find(c=>c.id===t.club_id)?.name??'Club',date:t.date,startsAt:t.starts_at??null,status:t.status,waitlistPosition:t.waitlist?.find(w=>w.player_id===me)?.position??null,registrationOpen:!registrationClosed(t,now.toISOString()),entered,checkedIn:!!me&&checked.has(me),checkInOpen:!!t.check_in_open,entrants:entries.length,attendance:entries.filter(e=>checked.has(e.player_id)).length,capacity:t.capacity,canRegister:!!me&&(mine.has(t.club_id)||!!t.allow_visitors)&&!entered&&t.status==='registration'&&!registrationClosed(t,now.toISOString()),ready,finished:t.state?.fixtures.filter(f=>f.status==='played'||f.status==='forfeit').length??0,remaining:t.state?.fixtures.filter(f=>f.status==='ready'||f.status==='waiting').length??0};
 }).sort((a,b)=>(a.status==='active'?0:1)-(b.status==='active'?0:1)||(a.startsAt??a.date).localeCompare(b.startsAt??b.date)||a.id.localeCompare(b.id));
 return {player:{events:events.filter(t=>t.entered||t.canRegister||!!t.waitlistPosition).map(t=>({...t,ready:t.ready.filter(f=>f.mine)})),verification:data.matches.filter(m=>m.canConfirm&&(m.a===me||m.b===me)).map(m=>({id:m.id,clubId:m.club_id,label:`${name(m.a)} vs ${name(m.b)}`})),awaitingVerification:data.matches.filter(m=>m.status==='pending'&&(m.a===me||m.b===me)&&!m.canConfirm).length},organizer:{clubs:data.clubs.filter(c=>managed.has(c.id)).map(c=>({id:c.id,name:c.name})),events:events.filter(t=>managed.has(t.clubId)),verification:data.matches.filter(m=>m.canConfirm&&managed.has(m.club_id)).map(m=>({id:m.id,clubId:m.club_id,label:`${name(m.a)} vs ${name(m.b)}`})),approvals:data.clubs.filter(c=>managed.has(c.id)).map(c=>({id:c.id,name:c.name,count:data.memberships.filter(m=>m.club_id===c.id&&m.status==='pending').length})).filter(c=>c.count>0)}};
}
export type Dashboards=ReturnType<typeof dashboardsFor>;
