import {eventLogistics,optionalText,optionalInstant,registrationClosed} from './logistics';
import {defaultPreferences} from './notification-preferences';
import {seasonStandings,type SeasonView} from './club-seasons';
import {notificationsFor} from './notifications';
import type {RecordData} from '../app/match-record-sheet';
import type {Data} from '../app/rally-app';
import {clubs,players,initialMatches} from './rally';
import {scoreError} from './match-rules';
import {createDraw,recordFixture,resetFixture,withdrawPlayer,outcome,type Draw} from './tournament-engine';
import {suggestSeeds,tournamentWeight,ratingEstimates} from './seeding';

// Sample actions stay in memory and never call the production API.
function finish(draw:Draw){let d=draw;while(d.fixtures.some(f=>f.status==='ready')){const f=d.fixtures.find(f=>f.status==='ready')!;d=recordFixture(d,f.id,Array.from({length:Math.floor(d.bestOf/2)+1},()=>[11,7]));}return d;}
function derive(data:Data){
 for(const c of data.clubs)c.activeMemberCount=data.memberships.filter(m=>m.club_id===c.id&&m.status==='active').length;
 for(const t of data.tournaments){
  if(t.state){t.rating_weight??=tournamentWeight(data.entries.filter(e=>e.tournament_id===t.id).map(e=>e.player_id),data.memberships,data.clubs.filter(c=>c.approvalStatus==='approved').map(c=>c.id));t.status=outcome(t.state).status==='completed'?'completed':'active';data.matches=data.matches.filter(m=>m.tournament_id!==t.id);
   for(const f of t.state.fixtures.filter(f=>f.status==='played'))data.matches.push({id:`${t.id}-${f.id}`,club_id:t.club_id,a:f.a!,b:f.b!,games:f.games,best_of:t.state.bestOf,played_on:t.date,status:'confirmed',submitted_by:'alex',confirmed_by:'alex',canConfirm:false,canVoid:false,tournament_id:t.id,tournament_weight:t.rating_weight});}
 }
 for(const m of data.matches){m.a_initial_rating=data.players.find(p=>p.id===m.a)?.initial_rating;m.b_initial_rating=data.players.find(p=>p.id===m.b)?.initial_rating;}
 for(const t of data.tournaments)t.seedStats=suggestSeeds(data.entries.filter(e=>e.tournament_id===t.id).map(e=>e.player_id),data.matches.filter(m=>m.club_id===t.club_id),undefined,ratingEstimates(data.players));
 data.matches.sort((a,b)=>b.played_on.localeCompare(a.played_on));data.notifications=notificationsFor(data,data.notificationReads??[],true);return data;
}
export function createDemoData():Data{
 const data:Data={me:{id:'alex',name:'Alex Morgan'},account:{email:'alex@example.test',displayName:'Alex Morgan',emailVerified:true},signedIn:true,isSiteAdmin:true,
 players:players.map(p=>({id:p.id,name:p.name,is_guest:p.id==='riley'?1:0,bio:'',rally_id:'RLY-DEMO-'+p.id.toUpperCase(),initial_rating:({alex:1500,jordan:1400,sam:1250,riley:600,casey:1800,taylor:1600,morgan:1100,jamie:900} as Record<string,number>)[p.id],initial_rating_revision:1})),
 clubs:[...clubs.map(c=>({id:c.id,name:c.name,location:c.location,canManage:true,canAssignRoles:c.id==='harbor',bio:c.id==='harbor'?'Weekly club play and friendly tournaments in Baltimore. All skill levels welcome.':'Community table tennis in Columbia, with practice nights and club tournaments.',approvalStatus:'approved' as const,activeMemberCount:0})),{id:'campus',name:'Campus Table Tennis',location:'Towson, MD',canManage:false,approvalStatus:'pending',activeMemberCount:1}],
 memberships:players.map(p=>({club_id:p.club,player_id:p.id,role:p.id==='alex'?'owner':'member',status:'active'})),
 matches:initialMatches.map(m=>({id:m.id,club_id:m.club,a:m.a,b:m.b,games:m.games,best_of:3,played_on:m.date,status:m.status,submitted_by:m.a,confirmed_by:m.status==='confirmed'?'alex':null,canConfirm:m.status==='pending',canVoid:m.status==='confirmed',tournament_id:null})),tournaments:[],entries:[]};
 data.memberships.push({club_id:'metro',player_id:'alex',role:'admin',status:'active'},{club_id:'harbor',player_id:'casey',role:'member',status:'pending'},{club_id:'campus',player_id:'jamie',role:'owner',status:'active'});
 data.matches.unshift({id:'pending-sample',club_id:'harbor',a:'sam',b:'jordan',games:[[11,8],[11,9]],best_of:3,played_on:'2026-10-04',status:'pending',submitted_by:'sam',confirmed_by:null,canConfirm:true,canVoid:false,tournament_id:null});
 data.players.push({id:'visiting-guest',name:'Jamie (guest record)',is_guest:1});data.memberships.push({club_id:'harbor',player_id:'visiting-guest',role:'guest',status:'active'});
 data.ownership={claims:[{id:'sample-claim',guest_id:'visiting-guest',claimant_id:'jamie',club_id:'harbor',guestName:'Jamie (guest record)',claimantName:'Jamie Chen',evidence:'I visited the club last Tuesday and played as a guest.',status:'pending',canReview:true}],reviews:[{id:'sample-review',match_id:'pending-sample',note:'Please check the second game score.',proposed_games:null,status:'pending',resolution:'',requesterName:'Sam Rivera',canReview:true}]};
 const samples=[
 {id:'autumn',name:'Autumn Singles',date:'2026-10-10',club:'harbor',format:'Single elimination',state:null},
 {id:'live',name:'Harbor Open',date:'2026-10-05',club:'harbor',format:'Single elimination',state:createDraw(['alex','jordan','sam','riley'],'Single elimination',3,true)},
 {id:'summer',name:'Summer Singles Final',date:'2026-09-20',club:'harbor',format:'Single elimination',state:finish(createDraw(['alex','jordan','sam','riley'],'Single elimination',3,true))},
 {id:'interclub',name:'Interclub Open',date:'2026-09-22',club:'harbor',format:'Single elimination',state:finish(createDraw(['alex','jordan','casey','taylor'],'Single elimination',3))},
 {id:'league',name:'September Round Robin',date:'2026-09-13',club:'metro',format:'Round robin',state:finish(createDraw(['casey','taylor','morgan','jamie'],'Round robin',3))},
 {id:'double',name:'Metro Double Elimination',date:'2026-08-30',club:'metro',format:'Double elimination',state:finish(createDraw(['casey','taylor','morgan','jamie'],'Double elimination',3))}];
 for(const t of samples){data.tournaments.push({id:t.id,name:t.name,club_id:t.club,date:t.date,format:t.format,capacity:16,status:t.state?'active':'registration',best_of:3,revision:0,created_by:'alex',canDelete:true,state:t.state,seedStats:[]});for(const id of t.state?.seeds??['alex','jordan','sam'])data.entries.push({tournament_id:t.id,player_id:id});}
 data.tournaments.push({id:'visitors',name:'Visiting Player Open',club_id:'harbor',date:'2026-10-20',format:'Single elimination',capacity:2,status:'registration',best_of:3,revision:0,created_by:'alex',canDelete:true,state:null,seedStats:[],allow_visitors:1,waitlist_count:2,waitlist:[{player_id:'casey',position:1},{player_id:'taylor',position:2}]});data.entries.push({tournament_id:'visitors',player_id:'jordan'},{tournament_id:'visitors',player_id:'sam'});
 Object.assign(data.clubs[0],{venue:'Harbor Community Center, Baltimore, MD',meeting_schedule:'Tuesday and Thursday, 6–9 PM',contact:'harbor@example.test',joining_info:'Request membership on this page. Bring a paddle; beginners are welcome.'});Object.assign(data.tournaments.find(t=>t.id==='autumn')??{},{starts_at:'2026-10-10T18:00:00.000Z',registration_closes_at:'2026-10-10T16:00:00.000Z',check_in_open:1,checkedIn:['jordan']});data.preferences={...defaultPreferences};data.seasons=[{id:'fall-season',club_id:'harbor',name:'Fall Club Ladder',starts_on:'2026-09-01',ends_on:'2026-12-31',closed_at:null,revision:0,created_by:'alex',created_at:'2026-09-01'}];data.seasonPlayers=data.memberships.filter(m=>m.club_id==='harbor'&&m.status==='active').map(m=>({season_id:'fall-season',player_id:m.player_id,status:'active'}));data.feedback=[{id:'sample-feature',submitted_by:'alex',type:'feature',title:'Club season ladders',description:'Track club standings within a season.',page:'/clubs',status:'completed',revision:1,created_at:'2026-10-01',updated_at:'2026-10-06',updates:[{id:'sample-update',status:'completed',note:'Season ladders are included in release 4.',created_at:'2026-10-06'}]}];return derive(data);
}
export function demoSeasons(data:Data,club:string):SeasonView[]{const today=new Date().toISOString().slice(0,10),membership=data.memberships.find(m=>m.club_id===club&&m.player_id===data.me?.id&&m.status==='active');return (data.seasons??[]).filter(s=>s.club_id===club).sort((a,b)=>b.starts_on.localeCompare(a.starts_on)).map(s=>{const roster=(data.seasonPlayers??[]).filter(p=>p.season_id===s.id).map(p=>({...p,name:data.players.find(person=>person.id===p.player_id)?.name??'Deleted player'}));return {...s,...seasonStandings(s,roster,data.matches.filter(m=>m.club_id===club)),me:data.me?.id??null,canManage:!!data.clubs.find(c=>c.id===club)?.canManage,canJoin:!!membership&&!s.closed_at&&s.ends_on>=today&&!roster.some(p=>p.player_id===data.me?.id&&p.status==='active')};});}
export function demoMatchRecord(data:Data,id:string):RecordData|undefined{
 const m=data.matches.find(m=>m.id===id);if(!m)return;return {playerNames:[m.a,m.b].map(id=>data.players.find(p=>p.id===id)?.name??'Player'),match:{...m,games:JSON.stringify(m.games),revision:m.revision??0},canManage:!!data.clubs.find(c=>c.id===m.club_id)?.canManage,history:data.matchHistory?.filter(h=>h.match_id===id)??[],audit:[],reviews:data.ownership?.reviews.filter(r=>r.match_id===id)??[]};
}
export function applyDemoAction(current:Data,p:Record<string,unknown>):Data{
 const d=structuredClone(current),id=String(p.id??crypto.randomUUID()),clubId=String(p.clubId??''),playerId=String(p.playerId??''),action=String(p.action),text=(key:string)=>String(p[key]??'').trim();
 const addGuest=()=>{if(!text('name'))throw new Error('Enter a player name.');const guestId=crypto.randomUUID();d.players.push({id:guestId,name:text('name'),is_guest:1});d.memberships.push({club_id:clubId||d.tournaments.find(t=>t.id===id)!.club_id,player_id:guestId,role:'member',status:'active'});return guestId;};
 if(action==='save_notification_preferences'){d.preferences=Object.fromEntries(Object.keys(defaultPreferences).map(k=>{if(typeof p[k]!=='boolean')throw Error('Choose every preference.');return [k,p[k]];})) as typeof defaultPreferences;}
 else if(action==='set_initial_rating'){const p1=d.players.find(p=>p.id===playerId);if(!p1||!d.memberships.some(m=>m.player_id===playerId&&m.club_id===clubId&&m.status==='active')||!d.clubs.find(c=>c.id===clubId)?.canManage)throw Error('Only organizers can estimate active players.');if(p1.initial_rating!=null&&!d.isSiteAdmin)throw Error('Only a site administrator can correct an estimate.');if(p.revision!==(p1.initial_rating_revision??0))throw Error('The estimate changed.');if(!Number.isInteger(p.rating)||Number(p.rating)<200||Number(p.rating)>4000||!text('note'))throw Error('Enter an estimate from 200 to 4000 and a reason.');p1.initial_rating=Number(p.rating);p1.initial_rating_revision=(p1.initial_rating_revision??0)+1;}
 else if(action==='create_season'){if(!d.clubs.find(c=>c.id===clubId)?.canManage)throw Error('Only organizers can create seasons.');if(!text('name')||!/^\d{4}-\d{2}-\d{2}$/.test(text('startsOn'))||!/^\d{4}-\d{2}-\d{2}$/.test(text('endsOn'))||text('startsOn')>text('endsOn'))throw Error('Enter valid season dates and a name.');d.seasons??=[];if(d.seasons.some(s=>s.id===id))return derive(d);d.seasons.unshift({id,club_id:clubId,name:text('name'),starts_on:text('startsOn'),ends_on:text('endsOn'),closed_at:null,revision:0,created_by:d.me!.id,created_at:new Date().toISOString()});d.seasonPlayers??=[];for(const m of d.memberships.filter(m=>m.club_id===clubId&&m.status==='active'))d.seasonPlayers.push({season_id:id,player_id:m.player_id,status:'active'});}
 else if(['join_season','withdraw_season','close_season'].includes(action)){const s=d.seasons?.find(s=>s.id===id);if(!s||s.closed_at||s.revision!==p.revision)throw Error('Season changed or finished.');const admin=!!d.clubs.find(c=>c.id===s.club_id)?.canManage;if(action==='close_season'){if(!admin||p.confirmation!=='CLOSE')throw Error('An organizer must confirm closing.');s.closed_at=new Date().toISOString();}else{if(playerId!==d.me!.id&&!admin)throw Error('Only organizers can manage other ladder players.');if(!d.memberships.some(m=>m.club_id===s.club_id&&m.player_id===playerId&&m.status==='active'))throw Error('Join the club before its ladder.');d.seasonPlayers??=[];const row=d.seasonPlayers.find(sp=>sp.season_id===id&&sp.player_id===playerId);if(row)row.status=action==='join_season'?'active':'withdrawn';else if(action==='join_season')d.seasonPlayers.push({season_id:id,player_id:playerId,status:'active'});}s.revision++;}
 else if(action==='save_profile'){if(!text('name'))throw new Error('Enter a display name.');d.me!.name=text('name');d.players.find(x=>x.id===d.me!.id)!.name=text('name');if(p.bio!==undefined){if(typeof p.bio!=='string'||p.bio.trim().length>500)throw new Error('Bio must be text with at most 500 characters.');d.players.find(x=>x.id===d.me!.id)!.bio=p.bio.trim();}if(p.photo!==undefined)d.players.find(x=>x.id===d.me!.id)!.photo_url=p.photo===null?null:String(p.photo);}
 else if(action==='mark_notification_read'||action==='mark_notifications_read'){const notices=notificationsFor(d,d.notificationReads??[],true),ids=action==='mark_notifications_read'?notices.map(n=>n.id):notices.filter(n=>n.id===p.id).map(n=>n.id);if(action==='mark_notification_read'&&!ids.length)throw new Error('Notification not found.');d.notificationReads=[...new Set([...(d.notificationReads??[]),...ids])];}
 else if(action==='update_club'){const c=d.clubs.find(c=>c.id===clubId);if(!c?.canAssignRoles)throw new Error('Only the club owner can edit club information.');if(!text('name')||text('name').length>80||!text('location')||text('location').length>100||typeof p.bio!=='string'||p.bio.trim().length>1200)throw new Error('Enter valid club information.');c.name=text('name');c.location=text('location');c.bio=p.bio.trim();for(const key of ['venue','meeting_schedule','contact','joining_info'])if(p[key]!==undefined)Object.assign(c,{[key]:optionalText(p[key],key,key==='joining_info'?800:key==='meeting_schedule'?500:300)});}
 else if(action==='set_club_media'){const c=d.clubs.find(c=>c.id===clubId);if(!c?.canManage)throw new Error('Only club leaders can update images.');if(p.kind!=='photo'&&p.kind!=='banner')throw new Error('Choose a photo or banner.');c[p.kind==='photo'?'photo_url':'banner_url']=p.image===null?null:String(p.image);}
 else if(action==='submit_feedback'){
  if(!text('title')||text('title').length>120||!text('description')||text('description').length>3000||!['bug','feature'].includes(text('type')))throw new Error('Enter a title, details, and feedback type.');
  if(text('page').length>200||(text('page')&&(!text('page').startsWith('/')||text('page').startsWith('//')||/[?#\\]/.test(text('page')))))throw new Error('Enter a page path without a query or link.');
  d.feedback??=[];if(d.feedback.some(f=>f.id===id))return derive(d);
  if(d.feedback.filter(f=>f.submitted_by===d.me!.id&&Date.parse(f.created_at)>Date.now()-86400000).length>=5)throw new Error('You can send up to five reports or requests per day.');
  d.feedback.unshift({id,submitted_by:d.me!.id,type:text('type') as 'bug'|'feature',title:text('title'),description:text('description'),page:text('page'),status:'open',created_at:new Date().toISOString(),updated_at:new Date().toISOString()});
 }
 else if(action==='set_feedback_status'){const report=d.feedback?.find(f=>f.id===id);if(!d.isSiteAdmin||!report)throw new Error('Only site administrators can review feedback.');if(!['open','planned','in_progress','completed','closed'].includes(text('status')))throw new Error('Choose a valid status.');if(p.revision!==undefined&&p.revision!==(report.revision??0))throw Error('The request changed.');report.status=text('status');report.revision=(report.revision??0)+1;report.updated_at=new Date().toISOString();report.updates??=[];report.updates.push({id:crypto.randomUUID(),status:report.status,note:text('note'),created_at:report.updated_at});}
 else if(action==='set_member_role'){if(!d.clubs.find(c=>c.id===clubId)?.canAssignRoles)throw new Error('Only the club owner can appoint leaders.');const target=d.memberships.find(m=>m.club_id===clubId&&m.player_id===playerId&&m.status==='active');if(!target||target.role==='owner'||d.players.find(p=>p.id===playerId)?.is_guest||!['member','admin','board'].includes(text('role')))throw new Error('Choose an active member and role.');target.role=text('role');}
 else if(action==='create_club'){if(!text('name')||!text('location'))throw new Error('Enter a club name and location.');if(d.memberships.some(m=>m.player_id===d.me!.id&&m.role==='owner'))throw new Error('You already own a club.');d.clubs.push({id,name:text('name'),location:text('location'),canManage:true,canAssignRoles:true,approvalStatus:'pending',activeMemberCount:1});d.memberships.push({club_id:id,player_id:d.me!.id,role:'owner',status:'active'});}
 else if(action==='add_guest')addGuest();
 else if(action==='approve_club'||action==='decline_club')d.clubs.find(c=>c.id===clubId)!.approvalStatus=action==='approve_club'?'approved':'rejected';
 else if(action==='request_join')d.memberships.push({club_id:clubId,player_id:d.me!.id,role:'member',status:'pending'});
 else if(action==='approve_member'||action==='decline_member')d.memberships.find(m=>m.club_id===clubId&&m.player_id===playerId)!.status=action==='approve_member'?'active':'declined';
 else if(action==='request_guest_claim'){
 const guest=d.players.find(g=>g.id===p.guestId&&g.is_guest);if(!guest||!text('note'))throw Error('Choose a guest and explain your request.');d.ownership??={claims:[],reviews:[]};if(d.ownership.claims.some(c=>c.guest_id===guest.id&&c.claimant_id===d.me!.id&&c.status==='pending'))throw Error('You already requested this guest record.');d.ownership.claims.unshift({id,guest_id:guest.id,claimant_id:d.me!.id,club_id:clubId,guestName:guest.name,claimantName:d.me!.name,evidence:text('note'),status:'pending',canReview:!!d.clubs.find(c=>c.id===clubId)?.canManage});
 }else if(action==='review_guest_claim'){
 const claim=d.ownership?.claims.find(c=>c.id===id);if(!claim||claim.status!=='pending'||!claim.canReview||claim.claimant_id===d.me!.id)throw Error('Another organizer must review this claim.');if(p.status==='approved'){if(p.confirmation!=='MERGE')throw Error('Confirm merging records.');if(d.matches.some(m=>(m.a===claim.guest_id&&m.b===claim.claimant_id)||(m.b===claim.guest_id&&m.a===claim.claimant_id))||d.entries.some(e=>e.player_id===claim.guest_id&&d.entries.some(other=>other.tournament_id===e.tournament_id&&other.player_id===claim.claimant_id)))throw Error('Duplicate identities in the same match or event need organizer review.');const guest=claim.guest_id,target=claim.claimant_id;for(const row of (d.seasonPlayers??[]).filter(sp=>sp.player_id===guest))if(!d.seasonPlayers?.some(sp=>sp.season_id===row.season_id&&sp.player_id===target))d.seasonPlayers?.push({...row,player_id:target});d.seasonPlayers=d.seasonPlayers?.filter(sp=>sp.player_id!==guest);for(const m of d.matches){if(m.a===guest)m.a=target;if(m.b===guest)m.b=target;}for(const e of d.entries)if(e.player_id===guest)e.player_id=target;for(const t of d.tournaments){if(t.state)t.state=JSON.parse(JSON.stringify(t.state).replaceAll(JSON.stringify(guest),JSON.stringify(target)));if(t.waitlist)t.waitlist=t.waitlist.map(w=>({...w,player_id:w.player_id===guest?target:w.player_id}));}for(const m of d.memberships.filter(m=>m.player_id===guest))if(!d.memberships.some(other=>other.player_id===target&&other.club_id===m.club_id))d.memberships.push({...m,player_id:target,role:'member'});d.memberships=d.memberships.filter(m=>m.player_id!==guest);d.players=d.players.filter(p=>p.id!==guest);}else if(p.status!=='rejected')throw Error('Choose approval or rejection.');claim.status=String(p.status);
 }else if(['request_match_review','correct_match','resolve_match_review'].includes(action)){
 const match=d.matches.find(m=>m.id===p.matchId);if(!match)throw Error('Match unavailable.');d.ownership??={claims:[],reviews:[]};if(action==='request_match_review'){if(!text('note'))throw Error('Explain your request.');if(d.ownership.reviews.some(r=>r.match_id===match.id&&r.status==='pending'&&r.requesterName===d.me!.name))throw Error('You already requested a review.');d.ownership.reviews.unshift({id,match_id:match.id,note:text('note'),proposed_games:null,status:'pending',resolution:'',requested_by:d.me!.id,requesterName:d.me!.name,canReview:!!d.clubs.find(c=>c.id===match.club_id)?.canManage});}
 else {if(!d.clubs.find(c=>c.id===match.club_id)?.canManage)throw Error('Only an organizer can correct results.');if(!text('note'))throw Error('Explain the correction.');if(action==='correct_match'){if(match.tournament_id)throw Error('Correct tournament results through the draw.');if((match.revision??0)!==p.revision)throw Error('The result changed.');const error=scoreError(match.a,match.b,p.games,match.best_of);if(error)throw Error(error);const before=JSON.stringify({...match,games:JSON.stringify(match.games)});match.games=p.games as [number,number][];match.status='confirmed';match.revision=(match.revision??0)+1;d.matchHistory??=[];d.matchHistory.push({id:crypto.randomUUID(),match_id:match.id,action:'corrected',note:text('note'),actorName:d.me!.name,created_at:new Date().toISOString(),before_json:before,after_json:JSON.stringify({...match,games:JSON.stringify(match.games)})});}else{const r=d.ownership.reviews.find(r=>r.id===id);if(!r||r.status!=='pending')throw Error('Review unavailable.');if(p.status==='resolved'&&!d.matchHistory?.some(h=>h.match_id===match.id))throw Error('Correct the result before resolving the review.');r.status=String(p.status);r.resolution=text('note');}}
 }else if(action==='record_match'){
  const error=scoreError(text('a'),text('b'),p.games,p.bestOf);if(error)throw new Error(error);
  if(clubId==='unaffiliated'&&![text('a'),text('b')].includes(d.me!.id))throw Error('You can only submit your own matches.');
  const eligible=(pid:string)=>clubId==='unaffiliated'?d.players.some(p=>p.id===pid&&!p.is_guest):d.memberships.some(m=>m.club_id===clubId&&m.player_id===pid&&m.status==='active');if(!eligible(text('a'))||!eligible(text('b')))throw new Error('Choose two active club players.');
  d.matches.unshift({id,club_id:clubId,a:text('a'),b:text('b'),games:p.games as [number,number][],best_of:Number(p.bestOf),played_on:text('date'),status:clubId==='unaffiliated'?'pending':'confirmed',submitted_by:d.me!.id,confirmed_by:clubId==='unaffiliated'?null:d.me!.id,canConfirm:false,canVoid:true,tournament_id:null});
 }else if(action==='confirm_match'||action==='void_match'){const m=d.matches.find(m=>m.id===id)!;m.status=action==='confirm_match'?'confirmed':'voided';m.canConfirm=false;m.canVoid=m.status==='confirmed';m.confirmed_by=d.me!.id;}
 else if(action==='create_tournament'){if(!text('name'))throw new Error('Enter a tournament name.');if(!Number.isInteger(p.capacity)||Number(p.capacity)<2)throw new Error('Use a player limit of at least two.');d.tournaments.unshift({id,name:text('name'),club_id:clubId,date:text('date'),format:text('format'),capacity:Number(p.capacity),status:'registration',best_of:3,revision:0,created_by:d.me!.id,canDelete:true,state:null,seedStats:[]});}
 else{
  const t=d.tournaments.find(t=>t.id===id);if(!t)throw new Error('This sample event is unavailable.');if(p.revision!==undefined&&Number(p.revision)!==t.revision)throw new Error('The draw changed. Close and reopen it before trying again.');const entries=d.entries.filter(e=>e.tournament_id===id);
  if(action==='delete_tournament'){if(t.created_by!==d.me!.id)throw new Error('Only the tournament creator can delete it.');if(p.confirmation!=='DELETE')throw new Error('Confirm tournament deletion.');d.tournaments=d.tournaments.filter(e=>e.id!==id);d.entries=d.entries.filter(e=>e.tournament_id!==id);d.matches=d.matches.filter(m=>m.tournament_id!==id);}
  else if(action==='set_registration_policy'){if(t.status!=='registration')throw Error('Registration settings are locked.');t.allow_visitors=p.allowVisitors?1:0;}
  else if(action==='join_waitlist'){if(registrationClosed(t)||entries.some(e=>e.player_id===playerId))throw Error('Registration is closed or already entered.');if(entries.length<t.capacity&&!t.waitlist?.length)throw Error('Register for the available place.');t.waitlist??=[];if(!t.waitlist.some(w=>w.player_id===playerId))t.waitlist.push({player_id:playerId,position:t.waitlist.length+1});t.waitlist_count=t.waitlist.length;}
  else if(action==='leave_waitlist'){t.waitlist=(t.waitlist??[]).filter(w=>w.player_id!==playerId).map((w,i)=>({...w,position:i+1}));t.waitlist_count=t.waitlist.length;}
  else if(action==='set_event_logistics'){Object.assign(t,eventLogistics(p));}
  else if(action==='set_check_in'){if(!t.check_in_open||t.status==='completed'||!entries.some(e=>e.player_id===playerId))throw new Error('Check-in is closed or the player is not registered.');t.checkedIn=p.checkedIn?[...new Set([...(t.checkedIn??[]),playerId])]:(t.checkedIn??[]).filter(id=>id!==playerId);}
  else if(action==='set_fixture_plan'){const fixtureId=text('fixtureId');if(t.status!=='active'||!t.state?.fixtures.some(f=>f.id===fixtureId&&(f.status==='ready'||f.status==='waiting')))throw new Error('Choose an upcoming match.');t.fixturePlans=[...(t.fixturePlans??[]).filter(f=>f.fixture_id!==fixtureId),{fixture_id:fixtureId,court:optionalText(p.court,'Court',60),starts_at:optionalInstant(p.startsAt,'match time')}];}
  else if(action==='enter_tournament'||action==='add_tournament_guest'){if(registrationClosed(t)||entries.length>=t.capacity||t.waitlist?.length)throw new Error('Registration is closed or full.');const entrant=action==='add_tournament_guest'?addGuest():playerId;if(entries.some(e=>e.player_id===entrant))throw new Error('Player is already registered.');d.entries.push({tournament_id:id,player_id:entrant});}
  else if(action==='remove_entry'){if(t.status!=='registration')throw new Error('The draw is locked.');d.entries=d.entries.filter(e=>e.tournament_id!==id||e.player_id!==playerId);t.checkedIn=(t.checkedIn??[]).filter(id=>id!==playerId);}
  else if(action==='set_capacity'){if(!Number.isInteger(p.capacity)||Number(p.capacity)<Math.max(2,entries.length))throw new Error('The limit must fit the registered players.');t.capacity=Number(p.capacity);}
  else if(action==='start_tournament'){t.waitlist=[];t.waitlist_count=0;t.rating_weight=tournamentWeight(entries.map(e=>e.player_id),d.memberships,d.clubs.filter(c=>c.approvalStatus==='approved').map(c=>c.id));t.state=createDraw(p.seeds as string[],t.format,Number(p.bestOf),Boolean(p.thirdPlace));t.best_of=Number(p.bestOf);}
  else if(action==='score_fixture')t.state=recordFixture(t.state!,text('fixtureId'),p.games,p.forfeitWinner as string|undefined);
  else if(action==='reset_fixture')t.state=resetFixture(t.state!,text('fixtureId'));
  else if(action==='withdraw_player')t.state=withdrawPlayer(t.state!,playerId);
  else throw new Error('This sample action is unavailable.');
  if(['remove_entry','set_capacity'].includes(action)&&!registrationClosed(t)){while(t.waitlist?.length&&d.entries.filter(e=>e.tournament_id===id).length<t.capacity){const w=t.waitlist.shift()!;d.entries.push({tournament_id:id,player_id:w.player_id});}t.waitlist=t.waitlist?.map((w,i)=>({...w,position:i+1}));t.waitlist_count=t.waitlist?.length??0;}t.revision++;
 }
 return derive(d);
}

