import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,index,check,uniqueIndex,primaryKey,type AnySQLiteColumn} from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),authId:text('auth_id'),mergedInto:text('merged_into').references(():AnySQLiteColumn=>profiles.id),deletedAt:text('deleted_at'),bio:text('bio').notNull().default(''),rallyId:text('rally_id'),name:text('name').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('idx_profiles_auth').on(t.authId),uniqueIndex('idx_profiles_rally_id').on(t.rallyId)]);
export const clubs=sqliteTable('clubs',{venue:text('venue').notNull().default(''),meetingSchedule:text('meeting_schedule').notNull().default(''),contact:text('contact').notNull().default(''),joiningInfo:text('joining_info').notNull().default(''),bio:text('bio').notNull().default(''),id:text('id').primaryKey(),name:text('name').notNull(),location:text('location').notNull(),ownerId:text('owner_id').notNull().references(()=>profiles.id),createdAt:text('created_at').notNull()});
export const memberships=sqliteTable('memberships',{id:text('id').primaryKey(),clubId:text('club_id').notNull().references(()=>clubs.id),playerId:text('player_id').notNull().references(()=>profiles.id),role:text('role').notNull(),status:text('status').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('idx_membership_club_player').on(t.clubId,t.playerId),index('idx_membership_player').on(t.playerId)]);
export const matches=sqliteTable('matches',{revision:integer('revision').notNull().default(0),id:text('id').primaryKey(),clubId:text('club_id').notNull().references(()=>clubs.id),a:text('a').notNull().references(()=>profiles.id),b:text('b').notNull().references(()=>profiles.id),games:text('games').notNull(),bestOf:integer('best_of').notNull(),playedOn:text('played_on').notNull(),status:text('status').notNull(),submittedBy:text('submitted_by').notNull().references(()=>profiles.id),confirmedBy:text('confirmed_by').references(()=>profiles.id),tournamentId:text('tournament_id'),createdAt:text('created_at').notNull()},t=>[index('idx_matches_club_date').on(t.clubId,t.playedOn),index('idx_matches_a').on(t.a),index('idx_matches_b').on(t.b)]);
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),matchId:text('match_id').notNull().references(()=>matches.id),actorId:text('actor_id').notNull().references(()=>profiles.id),action:text('action').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_audit_match').on(t.matchId)]);
export const tournaments=sqliteTable('tournaments',{tableCount:integer('table_count').notNull().default(1),estimatedMatchMinutes:integer('estimated_match_minutes').notNull().default(20),estimatedEndsAt:text('estimated_ends_at'),claimWindowMinutes:integer('claim_window_minutes').notNull().default(1440),allowVisitors:integer('allow_visitors').notNull().default(0),registrationClosesAt:text('registration_closes_at'),startsAt:text('starts_at'),checkInOpen:integer('check_in_open').notNull().default(0),id:text('id').primaryKey(),name:text('name').notNull(),clubId:text('club_id').notNull().references(()=>clubs.id),date:text('date').notNull(),format:text('format').notNull(),capacity:integer('capacity').notNull(),status:text('status').notNull().default('registration'),createdBy:text('created_by').references(()=>profiles.id,{onDelete:'set null'}),deletedAt:text('deleted_at'),ratingWeight:integer('rating_weight').notNull().default(2),bestOf:integer('best_of').notNull().default(3),stateJson:text('state_json'),revision:integer('revision').notNull().default(0),lastOperation:text('last_operation'),createdAt:text('created_at').notNull()});
export const entries=sqliteTable('entries',{checkedInAt:text('checked_in_at'),id:text('id').primaryKey(),tournamentId:text('tournament_id').notNull().references(()=>tournaments.id),playerId:text('player_id').notNull().references(()=>profiles.id),createdAt:text('created_at').notNull()},t=>[uniqueIndex('idx_entries_event_player').on(t.tournamentId,t.playerId)]);

export const tournamentOperations=sqliteTable('tournament_operations',{id:text('id').primaryKey(),tournamentId:text('tournament_id').notNull().references(()=>tournaments.id),actorId:text('actor_id').notNull().references(()=>profiles.id),action:text('action').notNull(),payload:text('payload').notNull(),beforeState:text('before_state'),afterState:text('after_state'),revision:integer('revision').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_tournament_operations_event').on(t.tournamentId)]);

export const accountDeletions=sqliteTable('account_deletions',{authId:text('auth_id').primaryKey(),requestedAt:text('requested_at').notNull(),attempts:integer('attempts').notNull().default(0),lastAttemptAt:text('last_attempt_at')});

// Empty guard tables support transactional checks implemented by migration triggers.
export const deletionRevisionGuards=sqliteTable('deletion_revision_guards',{tournamentId:text('tournament_id').notNull(),expectedRevision:integer('expected_revision').notNull()});
export const accountChangeGuards=sqliteTable('account_change_guards',{changed:integer('changed').notNull()});
export const accountWriteBlocks=sqliteTable('account_write_blocks',{authId:text('auth_id').primaryKey(),expiresAt:text('expires_at').notNull()});
export const accountWriteGuards=sqliteTable('account_write_guards',{authId:text('auth_id').notNull()});

export const profilePhotos=sqliteTable('profile_photos',{playerId:text('player_id').primaryKey().references(()=>profiles.id,{onDelete:'cascade'}),imageData:text('image_data').notNull(),updatedAt:text('updated_at').notNull()});

export const clubMedia=sqliteTable('club_media',{clubId:text('club_id').notNull().references(()=>clubs.id,{onDelete:'cascade'}),kind:text('kind').notNull(),imageData:text('image_data').notNull(),updatedAt:text('updated_at').notNull()},t=>[primaryKey({columns:[t.clubId,t.kind]})]);
export const feedback=sqliteTable('feedback',{revision:integer('revision').notNull().default(0),id:text('id').primaryKey(),submittedBy:text('submitted_by').notNull().references(()=>profiles.id,{onDelete:'cascade'}),type:text('type').notNull(),title:text('title').notNull(),description:text('description').notNull(),page:text('page').notNull().default(''),status:text('status').notNull().default('open'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('idx_feedback_submitter_date').on(t.submittedBy,t.createdAt)]);

export const notificationReads=sqliteTable('notification_reads',{playerId:text('player_id').notNull().references(()=>profiles.id,{onDelete:'cascade'}),notificationId:text('notification_id').notNull(),readAt:text('read_at').notNull()},t=>[primaryKey({columns:[t.playerId,t.notificationId]})]);

export const tournamentFixturePlans=sqliteTable('tournament_fixture_plans',{endsAt:text('ends_at'),calledAt:text('called_at'),tournamentId:text('tournament_id').notNull().references(()=>tournaments.id,{onDelete:'cascade'}),fixtureId:text('fixture_id').notNull(),court:text('court').notNull().default(''),startsAt:text('starts_at')},t=>[primaryKey({columns:[t.tournamentId,t.fixtureId]})]);

export const tournamentWaitlist=sqliteTable('tournament_waitlist',{offeredAt:text('offered_at'),claimExpiresAt:text('claim_expires_at'),id:text('id').primaryKey(),tournamentId:text('tournament_id').notNull().references(()=>tournaments.id),playerId:text('player_id').notNull().references(()=>profiles.id),createdAt:text('created_at').notNull()},t=>[index('idx_waitlist_queue').on(t.tournamentId,t.createdAt,t.id)]);
export const guestClaims=sqliteTable('guest_claims',{id:text('id').primaryKey(),guestId:text('guest_id').notNull().references(()=>profiles.id),claimantId:text('claimant_id').notNull().references(()=>profiles.id),clubId:text('club_id').notNull().references(()=>clubs.id),evidence:text('evidence').notNull(),guestName:text('guest_name').notNull().default(''),status:text('status').notNull().default('pending'),reviewedBy:text('reviewed_by').references(()=>profiles.id),createdAt:text('created_at').notNull(),reviewedAt:text('reviewed_at')},t=>[index('idx_claim_club_status').on(t.clubId,t.status),uniqueIndex('idx_claim_pending').on(t.guestId,t.claimantId).where(sql`${t.status}='pending'`)]);
export const matchReviews=sqliteTable('match_reviews',{id:text('id').primaryKey(),matchId:text('match_id').notNull().references(()=>matches.id),requestedBy:text('requested_by').notNull().references(()=>profiles.id),note:text('note').notNull(),proposedGames:text('proposed_games'),matchRevision:integer('match_revision').notNull(),originalGames:text('original_games').notNull(),status:text('status').notNull().default('pending'),resolvedBy:text('resolved_by').references(()=>profiles.id),resolution:text('resolution').notNull().default(''),createdAt:text('created_at').notNull(),resolvedAt:text('resolved_at')},t=>[index('idx_review_match_status').on(t.matchId,t.status),uniqueIndex('idx_review_pending').on(t.matchId,t.requestedBy).where(sql`${t.status}='pending'`)]);
export const matchHistory=sqliteTable('match_history',{id:text('id').primaryKey(),matchId:text('match_id').notNull().references(()=>matches.id),actorId:text('actor_id').notNull().references(()=>profiles.id),action:text('action').notNull(),note:text('note').notNull(),beforeJson:text('before_json').notNull(),afterJson:text('after_json').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_history_match_time').on(t.matchId,t.createdAt)]);

export const clubSeasons=sqliteTable('club_seasons',{id:text('id').primaryKey(),clubId:text('club_id').notNull().references(()=>clubs.id),name:text('name').notNull(),startsOn:text('starts_on').notNull(),endsOn:text('ends_on').notNull(),closedAt:text('closed_at'),createdBy:text('created_by').references(()=>profiles.id,{onDelete:'set null'}),revision:integer('revision').notNull().default(0),createdAt:text('created_at').notNull()},t=>[index('idx_seasons_club_dates').on(t.clubId,t.startsOn,t.endsOn)]);
export const seasonPlayers=sqliteTable('season_players',{seasonId:text('season_id').notNull().references(()=>clubSeasons.id),playerId:text('player_id').notNull().references(()=>profiles.id),status:text('status').notNull().default('active'),createdAt:text('created_at').notNull()},t=>[primaryKey({columns:[t.seasonId,t.playerId]})]);
export const notificationPreferences=sqliteTable('notification_preferences',{playerId:text('player_id').primaryKey().references(()=>profiles.id,{onDelete:'cascade'}),matchUpdates:integer('match_updates').notNull().default(1),registrationUpdates:integer('registration_updates').notNull().default(1),tournamentUpdates:integer('tournament_updates').notNull().default(1),recordUpdates:integer('record_updates').notNull().default(1),feedbackUpdates:integer('feedback_updates').notNull().default(1),sessionReminders:integer('session_reminders').notNull().default(0),tournamentReminders:integer('tournament_reminders').notNull().default(0),verificationReminders:integer('verification_reminders').notNull().default(0),emailDelivery:integer('email_delivery').notNull().default(0),pushDelivery:integer('push_delivery').notNull().default(0)});
export const feedbackUpdates=sqliteTable('feedback_updates',{id:text('id').primaryKey(),feedbackId:text('feedback_id').notNull().references(()=>feedback.id,{onDelete:'cascade'}),status:text('status').notNull(),note:text('note').notNull().default(''),createdAt:text('created_at').notNull()},t=>[index('idx_feedback_updates_request').on(t.feedbackId,t.createdAt)]);
export const summaryEpoch=sqliteTable('summary_epoch',{id:integer('id').primaryKey(),version:integer('version').notNull()});
export const clubhouseSummaryCache=sqliteTable('clubhouse_summary_cache',{scopeKey:text('scope_key').primaryKey(),version:integer('version').notNull(),asOf:text('as_of').notNull(),summaryJson:text('summary_json').notNull(),createdAt:text('created_at').notNull()});

export const clubSessions=sqliteTable('club_sessions',{repeatWeekly:integer('repeat_weekly').notNull().default(0),recurrenceJson:text('recurrence_json'),seriesId:text('series_id').references(():AnySQLiteColumn=>clubSessions.id,{onDelete:'set null'}),occurrence:integer('occurrence').notNull().default(0),id:text('id').primaryKey(),clubId:text('club_id').notNull().references(()=>clubs.id),title:text('title').notNull(),location:text('location').notNull().default(''),notes:text('notes').notNull().default(''),startsAt:text('starts_at').notNull(),endsAt:text('ends_at').notNull(),capacity:integer('capacity'),status:text('status').notNull().default('scheduled'),createdBy:text('created_by').references(()=>profiles.id,{onDelete:'set null'}),revision:integer('revision').notNull().default(0),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),operationId:text('operation_id'),operationPayload:text('operation_payload')},t=>[uniqueIndex('idx_session_occurrence').on(t.seriesId,t.occurrence).where(sql`${t.seriesId} IS NOT NULL`),index('idx_sessions_club_time').on(t.clubId,t.startsAt),check('session_status',sql`${t.status} IN ('scheduled','cancelled')`),check('session_times',sql`${t.endsAt}>${t.startsAt}`),check('session_capacity',sql`${t.capacity} IS NULL OR ${t.capacity}>0`)]);
export const sessionRsvps=sqliteTable('session_rsvps',{guests:integer('guests').notNull().default(0),queuedAt:text('queued_at'),sessionId:text('session_id').notNull().references(()=>clubSessions.id,{onDelete:'cascade'}),playerId:text('player_id').notNull().references(()=>profiles.id,{onDelete:'cascade'}),status:text('status').notNull(),updatedAt:text('updated_at').notNull()},t=>[primaryKey({columns:[t.sessionId,t.playerId]}),index('idx_session_waitlist').on(t.sessionId,t.status,t.queuedAt),check('rsvp_guests',sql`${t.guests} IN (0,1)`),check('rsvp_status',sql`${t.status} IN ('going','not_going','maybe','waitlisted')`)]);

export const pushSubscriptions=sqliteTable('push_subscriptions',{id:text('id').primaryKey(),playerId:text('player_id').notNull().references(()=>profiles.id,{onDelete:'cascade'}),endpoint:text('endpoint').notNull().unique(),p256dh:text('p256dh').notNull(),auth:text('auth').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_push_player').on(t.playerId)]);
export const notificationDeliveryScans=sqliteTable('notification_delivery_scans',{playerId:text('player_id').primaryKey().references(()=>profiles.id,{onDelete:'cascade'}),scannedAt:integer('scanned_at').notNull().default(0),leaseUntil:integer('lease_until').notNull().default(0)});
export const notificationDeliveries=sqliteTable('notification_deliveries',{id:text('id').primaryKey(),playerId:text('player_id').notNull().references(()=>profiles.id,{onDelete:'cascade'}),notificationId:text('notification_id').notNull(),channel:text('channel').notNull(),deviceId:text('device_id').notNull().default(''),payload:text('payload').notNull(),status:text('status').notNull().default('pending'),attempts:integer('attempts').notNull().default(0),createdAt:integer('created_at').notNull(),retryAt:integer('retry_at').notNull().default(0)},t=>[uniqueIndex('idx_delivery_identity').on(t.playerId,t.notificationId,t.channel,t.deviceId),index('idx_delivery_player').on(t.playerId,t.status),check('delivery_channel',sql`${t.channel} IN ('email','push')`),check('delivery_status',sql`${t.status} IN ('pending','sent','skipped','failed')`)]);

export const tournamentScorekeepers=sqliteTable('tournament_scorekeepers',{tournamentId:text('tournament_id').notNull().references(()=>tournaments.id,{onDelete:'cascade'}),playerId:text('player_id').notNull().references(()=>profiles.id,{onDelete:'cascade'})},t=>[primaryKey({columns:[t.tournamentId,t.playerId]})]);
export const openPlay=sqliteTable('open_play',{id:text('id').primaryKey(),clubId:text('club_id').notNull().references(()=>clubs.id,{onDelete:'cascade'}),playerId:text('player_id').notNull().references(()=>profiles.id,{onDelete:'cascade'}),note:text('note').notNull().default(''),startedAt:text('started_at').notNull(),expiresAt:text('expires_at').notNull(),endedAt:text('ended_at')});

export const uiPreferences=sqliteTable('ui_preferences',{playerId:text('player_id').primaryKey().references(()=>profiles.id,{onDelete:'cascade'}),palette:text('palette').notNull().default('forest'),appearance:text('appearance').notNull().default('light'),onboardingHidden:integer('onboarding_hidden').notNull().default(0),updatedAt:text('updated_at').notNull()});

export const profilePhotoOriginals=sqliteTable('profile_photo_originals',{playerId:text('player_id').primaryKey().references(()=>profiles.id,{onDelete:'cascade'}),imageData:text('image_data').notNull(),updatedAt:text('updated_at').notNull()});

export const liveDrafts=sqliteTable('live_drafts',{playerId:text('player_id').primaryKey().references(()=>profiles.id,{onDelete:'cascade'}),draftId:text('draft_id').notNull(),draftJson:text('draft_json').notNull(),updatedAt:text('updated_at').notNull()});

export const doublesMatches=sqliteTable('doubles_matches',{id:text('id').primaryKey(),clubId:text('club_id').notNull().references(()=>clubs.id),a1:text('a1').notNull().references(()=>profiles.id),a2:text('a2').notNull().references(()=>profiles.id),b1:text('b1').notNull().references(()=>profiles.id),b2:text('b2').notNull().references(()=>profiles.id),games:text('games').notNull(),bestOf:integer('best_of').notNull(),playedOn:text('played_on').notNull(),status:text('status').notNull(),submittedBy:text('submitted_by').notNull().references(()=>profiles.id),confirmedBy:text('confirmed_by').references(()=>profiles.id),tournamentId:text('tournament_id').references(()=>tournaments.id),revision:integer('revision').notNull().default(0),createdAt:text('created_at').notNull()});
export const doublesAudit=sqliteTable('doubles_audit',{id:text('id').primaryKey(),matchId:text('match_id').notNull().references(()=>doublesMatches.id),actorId:text('actor_id').notNull().references(()=>profiles.id),action:text('action').notNull(),createdAt:text('created_at').notNull()});
