import {sqliteTable,text,integer,index,uniqueIndex,primaryKey} from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),authId:text('auth_id'),deletedAt:text('deleted_at'),bio:text('bio').notNull().default(''),rallyId:text('rally_id'),name:text('name').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('idx_profiles_auth').on(t.authId),uniqueIndex('idx_profiles_rally_id').on(t.rallyId)]);
export const clubs=sqliteTable('clubs',{bio:text('bio').notNull().default(''),id:text('id').primaryKey(),name:text('name').notNull(),location:text('location').notNull(),ownerId:text('owner_id').notNull().references(()=>profiles.id),createdAt:text('created_at').notNull()});
export const memberships=sqliteTable('memberships',{id:text('id').primaryKey(),clubId:text('club_id').notNull().references(()=>clubs.id),playerId:text('player_id').notNull().references(()=>profiles.id),role:text('role').notNull(),status:text('status').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('idx_membership_club_player').on(t.clubId,t.playerId),index('idx_membership_player').on(t.playerId)]);
export const matches=sqliteTable('matches',{id:text('id').primaryKey(),clubId:text('club_id').notNull().references(()=>clubs.id),a:text('a').notNull().references(()=>profiles.id),b:text('b').notNull().references(()=>profiles.id),games:text('games').notNull(),bestOf:integer('best_of').notNull(),playedOn:text('played_on').notNull(),status:text('status').notNull(),submittedBy:text('submitted_by').notNull().references(()=>profiles.id),confirmedBy:text('confirmed_by').references(()=>profiles.id),tournamentId:text('tournament_id'),createdAt:text('created_at').notNull()},t=>[index('idx_matches_club_date').on(t.clubId,t.playedOn),index('idx_matches_a').on(t.a),index('idx_matches_b').on(t.b)]);
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),matchId:text('match_id').notNull().references(()=>matches.id),actorId:text('actor_id').notNull().references(()=>profiles.id),action:text('action').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_audit_match').on(t.matchId)]);
export const tournaments=sqliteTable('tournaments',{id:text('id').primaryKey(),name:text('name').notNull(),clubId:text('club_id').notNull().references(()=>clubs.id),date:text('date').notNull(),format:text('format').notNull(),capacity:integer('capacity').notNull(),status:text('status').notNull().default('registration'),createdBy:text('created_by').references(()=>profiles.id,{onDelete:'set null'}),deletedAt:text('deleted_at'),ratingWeight:integer('rating_weight').notNull().default(2),bestOf:integer('best_of').notNull().default(3),stateJson:text('state_json'),revision:integer('revision').notNull().default(0),lastOperation:text('last_operation'),createdAt:text('created_at').notNull()});
export const entries=sqliteTable('entries',{id:text('id').primaryKey(),tournamentId:text('tournament_id').notNull().references(()=>tournaments.id),playerId:text('player_id').notNull().references(()=>profiles.id),createdAt:text('created_at').notNull()},t=>[uniqueIndex('idx_entries_event_player').on(t.tournamentId,t.playerId)]);

export const tournamentOperations=sqliteTable('tournament_operations',{id:text('id').primaryKey(),tournamentId:text('tournament_id').notNull().references(()=>tournaments.id),actorId:text('actor_id').notNull().references(()=>profiles.id),action:text('action').notNull(),payload:text('payload').notNull(),beforeState:text('before_state'),afterState:text('after_state'),revision:integer('revision').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_tournament_operations_event').on(t.tournamentId)]);

export const accountDeletions=sqliteTable('account_deletions',{authId:text('auth_id').primaryKey(),requestedAt:text('requested_at').notNull(),attempts:integer('attempts').notNull().default(0),lastAttemptAt:text('last_attempt_at')});

// Empty guard tables support transactional checks implemented by migration triggers.
export const deletionRevisionGuards=sqliteTable('deletion_revision_guards',{tournamentId:text('tournament_id').notNull(),expectedRevision:integer('expected_revision').notNull()});
export const accountChangeGuards=sqliteTable('account_change_guards',{changed:integer('changed').notNull()});
export const accountWriteBlocks=sqliteTable('account_write_blocks',{authId:text('auth_id').primaryKey(),expiresAt:text('expires_at').notNull()});
export const accountWriteGuards=sqliteTable('account_write_guards',{authId:text('auth_id').notNull()});

export const profilePhotos=sqliteTable('profile_photos',{playerId:text('player_id').primaryKey().references(()=>profiles.id,{onDelete:'cascade'}),imageData:text('image_data').notNull(),updatedAt:text('updated_at').notNull()});

export const clubMedia=sqliteTable('club_media',{clubId:text('club_id').notNull().references(()=>clubs.id,{onDelete:'cascade'}),kind:text('kind').notNull(),imageData:text('image_data').notNull(),updatedAt:text('updated_at').notNull()},t=>[primaryKey({columns:[t.clubId,t.kind]})]);
export const feedback=sqliteTable('feedback',{id:text('id').primaryKey(),submittedBy:text('submitted_by').notNull().references(()=>profiles.id,{onDelete:'cascade'}),type:text('type').notNull(),title:text('title').notNull(),description:text('description').notNull(),page:text('page').notNull().default(''),status:text('status').notNull().default('open'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('idx_feedback_submitter_date').on(t.submittedBy,t.createdAt)]);

export const notificationReads=sqliteTable('notification_reads',{playerId:text('player_id').notNull().references(()=>profiles.id,{onDelete:'cascade'}),notificationId:text('notification_id').notNull(),readAt:text('read_at').notNull()},t=>[primaryKey({columns:[t.playerId,t.notificationId]})]);
