import {env} from 'cloudflare:workers';
import {getAuthenticatedUser} from '@/lib/auth';
import {AppError} from '@/lib/rally-errors';
import {guardAccountWrites} from '@/lib/account-write-guard';
import {readAnnouncements,nextAnnouncement,claimAnnouncement,publishAnnouncement} from '@/lib/announcements';
export const dynamic='force-dynamic';
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store','Vary':'Cookie'}});
async function viewer(){const user=await getAuthenticatedUser();if(!user)throw new AppError(401,'Sign in to view announcements.');const profile=await env.DB.prepare('SELECT id FROM profiles WHERE auth_id=? AND deleted_at IS NULL').bind(user.id).first<{id:string}>();if(!profile)throw new AppError(403,'Create your player profile first.');return {id:profile.id,authId:user.id,siteAdmin:(env.RALLY_ADMIN_EMAILS??'').split(',').some(e=>e.trim().toLowerCase()===user.email.toLowerCase())};}
const failure=(e:unknown)=>{if(e instanceof AppError)return response({error:e.message},e.status);console.error('Announcements unavailable',e);return response({error:'Announcements are temporarily unavailable. Try again.'},503);};
export async function GET(request:Request){try{const user=await viewer(),query=new URL(request.url).searchParams;if(query.get('next')==='1')return response({announcement:await nextAnnouncement(env.DB,user.id)});return response({announcements:await readAnnouncements(env.DB,user.id,query.get('club')??undefined),isSiteAdmin:user.siteAdmin});}catch(e){return failure(e);}}
export async function POST(request:Request){try{if(request.headers.get('origin')!==new URL(request.url).origin)throw new AppError(403,'Request origin not allowed.');if(!request.headers.get('content-type')?.startsWith('application/json'))throw new AppError(415,'JSON required.');const text=await request.text();if(text.length>10000)throw new AppError(413,'Announcement is too large.');let body:Record<string,unknown>;try{body=JSON.parse(text);if(!body||typeof body!=='object'||Array.isArray(body))throw new Error();}catch{throw new AppError(400,'Invalid announcement request.');}const user=await viewer(),db=guardAccountWrites(env.DB,user.authId);if(body.action==='claim')return response(await claimAnnouncement(db,user.id,String(body.id??'')));if(body.action==='publish')return response(await publishAnnouncement(db,user.id,user.siteAdmin,body));throw new AppError(400,'Unknown announcement action.');}catch(e){return failure(e);}}
