import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,writeFileSync,mkdirSync,readdirSync} from 'node:fs';
import ts from 'typescript';
mkdirSync('.test-runtime',{recursive:true});
for(const name of ['announcements','rally-errors','notifications','notification-preferences'])writeFileSync(`.test-runtime/${name}.mjs`,ts.transpileModule(readFileSync(`lib/${name}.ts`,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/from ['"]\.\/([^'"]+)['"]/g,"from './$1.mjs'"));
const {readAnnouncements,nextAnnouncement,claimAnnouncement,publishAnnouncement}=await import('../.test-runtime/announcements.mjs');
const {notificationsFor}=await import('../.test-runtime/notifications.mjs');
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
const run=(q,...args)=>sql.prepare(q).run(...args);
function stmt(q,args=[]){return {bind(...a){return stmt(q,a)},async first(){return sql.prepare(q).get(...args)??null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:run(q,...args)}}}}
const db={prepare:stmt};
for(const id of ['owner','admin','board','member','outsider','pending'])run('INSERT INTO profiles(id,name,created_at) VALUES(?,?,?)',id,id,'2026-10-06');
run("INSERT INTO clubs(id,name,location,owner_id,created_at,approval_status) VALUES('club','Club','City','owner','2026-10-06','approved')");
for(const role of ['owner','admin','board','member'])run("INSERT INTO memberships(id,club_id,player_id,role,status,created_at) VALUES(?,'club',?,?,'active','2026-10-06')",role,role,role);
run("INSERT INTO memberships(id,club_id,player_id,role,status,created_at) VALUES('pending','club','pending','member','pending','2026-10-06')");
const post=(id,clubId='')=>({id,clubId,title:'Club update',body:'Practice at 7 PM.'});
await assert.rejects(publishAnnouncement(db,'member',false,post('no-site')),e=>e.status===403);
await assert.rejects(publishAnnouncement(db,'outsider',false,post('no-club','club')),e=>e.status===403);
await assert.rejects(publishAnnouncement(db,'member',false,post('member-club','club')),e=>e.status===403);
for(const role of ['owner','admin','board'])await publishAnnouncement(db,role,false,post(role+'-notice','club'));
await publishAnnouncement(db,'owner',true,post('site'));
assert.equal((await readAnnouncements(db,'member')).length,4);
assert.deepEqual((await readAnnouncements(db,'outsider')).map(a=>a.id),['site']);
assert.deepEqual((await readAnnouncements(db,'pending')).map(a=>a.id),['site']);
assert.equal((await readAnnouncements(db,'outsider','club')).length,0);
assert.equal((await claimAnnouncement(db,'outsider','admin-notice')).claimed,false);
const next=await nextAnnouncement(db,'member');const results=await Promise.all([claimAnnouncement(db,'member',next.id),claimAnnouncement(db,'member',next.id)]);assert.equal(results.filter(r=>r.claimed).length,1);
assert.notEqual((await nextAnnouncement(db,'member')).id,next.id);
assert.equal((await claimAnnouncement(db,'member',next.id)).claimed,false);
assert.equal((await readAnnouncements(db,'member')).length,4);
await publishAnnouncement(db,'owner',true,post('site'));assert.equal(sql.prepare('SELECT count(*) n FROM announcements').get().n,4);
await assert.rejects(publishAnnouncement(db,'owner',true,{...post('site'),body:'Different'}),e=>e.status===409);
run("UPDATE memberships SET status='declined' WHERE player_id='admin'");
await assert.rejects(publishAnnouncement(db,'admin',false,post('removed-admin','club')),e=>e.status===403);
assert.deepEqual((await readAnnouncements(db,'admin')).map(a=>a.id),['site']);
const announcements=await readAnnouncements(db,'member');const source={me:{id:'member',name:'Member'},players:[],matches:[],clubs:[],memberships:[],entries:[],tournaments:[],announcements,preferences:{match_updates:false,registration_updates:false,tournament_updates:false,record_updates:false,feedback_updates:false}};
const notices=notificationsFor(source,['announcement-site']);assert.equal(notices.length,4);assert.equal(notices.find(n=>n.id==='announcement-site').read,true);assert.ok(notices.every(n=>n.date&&n.kind==='announcement'));
console.log('Announcements passed site/club role permissions, audience privacy, pending/revoked membership exclusion, one-time concurrent claims, persistent archives/inbox, idempotency and read state.');
