param([string]$OutputPath = (Join-Path $PSScriptRoot "..\public\rally-share.png"))

Add-Type -AssemblyName System.Drawing
$bitmap = [System.Drawing.Bitmap]::new(1200, 630)
$graphics = [System.Drawing.Graphics]::FromImage($bitmap)
$graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
$graphics.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAliasGridFit
$dark = [System.Drawing.SolidBrush]::new([System.Drawing.ColorTranslator]::FromHtml('#203c36'))
$lime = [System.Drawing.SolidBrush]::new([System.Drawing.ColorTranslator]::FromHtml('#d9ed64'))
$cream = [System.Drawing.SolidBrush]::new([System.Drawing.ColorTranslator]::FromHtml('#f3f5ed'))
$muted = [System.Drawing.SolidBrush]::new([System.Drawing.ColorTranslator]::FromHtml('#bdd0c5'))
$wordmark = [System.Drawing.Font]::new('Segoe UI', 132, [System.Drawing.FontStyle]::Bold, [System.Drawing.GraphicsUnit]::Pixel)
$heading = [System.Drawing.Font]::new('Segoe UI', 38, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)
$detail = [System.Drawing.Font]::new('Segoe UI', 26, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)
$domain = [System.Drawing.Font]::new('Segoe UI', 28, [System.Drawing.FontStyle]::Bold, [System.Drawing.GraphicsUnit]::Pixel)
$ring = [System.Drawing.Pen]::new($dark.Color, 13)
$graphics.Clear($dark.Color)
$graphics.FillRectangle($lime, 0, 0, 1200, 9)
$graphics.DrawString('rally', $wordmark, $cream, 65, 95)
$graphics.DrawString('.', $wordmark, $lime, 352, 95)
$graphics.DrawString('Table tennis clubs', $heading, $cream, 76, 275)
$graphics.DrawString('Matches  /  Standings  /  Tournaments', $detail, $muted, 78, 342)
$graphics.DrawString('rallytt.net', $domain, $lime, 78, 514)
$graphics.FillEllipse($lime, 811, 159, 280, 280)
$graphics.DrawEllipse($ring, 868, 216, 166, 166)
$graphics.FillEllipse($dark, 950, 257, 34, 34)
$bitmap.Save($OutputPath, [System.Drawing.Imaging.ImageFormat]::Png)
$ring.Dispose(); $wordmark.Dispose(); $heading.Dispose(); $detail.Dispose(); $domain.Dispose()
$dark.Dispose(); $lime.Dispose(); $cream.Dispose(); $muted.Dispose(); $graphics.Dispose(); $bitmap.Dispose()
