import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import ts from 'typescript';
mkdirSync('.test-runtime',{recursive:true});
for(const name of ['live-score','seeding','match-rules'])writeFileSync(`.test-runtime/${name}.mjs`,ts.transpileModule(readFileSync(`lib/${name}.ts`,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);
const {addLivePoint,newLiveScore,undoLivePoint}=await import('../.test-runtime/live-score.mjs');
const {calculateRatings,compareRatedPlayers,ESTABLISHED_MATCHES,resultWeight,suggestSeeds,tournamentWeight}=await import('../.test-runtime/seeding.mjs');
const {scoreError}=await import('../.test-runtime/match-rules.mjs');
let score=newLiveScore();for(let i=0;i<10;i++){score=addLivePoint(score,0,3);score=addLivePoint(score,1,3);}score=addLivePoint(score,0,3);assert.equal(score.games.length,0,'11-10 is unfinished');score=addLivePoint(score,0,3);assert.deepEqual(score.games,[[12,10]]);assert.deepEqual(score.points,[0,0]);
score=undoLivePoint(score);assert.deepEqual(score.points,[11,10]);assert.equal(score.games.length,0);score=addLivePoint(score,0,3);for(let i=0;i<11;i++)score=addLivePoint(score,0,3);
assert.equal(score.complete,true);assert.equal(scoreError('a','b',score.games,3),null);assert.equal(addLivePoint(score,1,3),score);score=undoLivePoint(score);assert.equal(score.complete,false);assert.deepEqual(score.points,[10,0]);
for(const bestOf of [3,5,7]){let s=newLiveScore();for(let g=0;g<Math.floor(bestOf/2)+1;g++)for(let i=0;i<11;i++)s=addLivePoint(s,1,bestOf);assert.equal(s.complete,true);assert.equal(scoreError('a','b',s.games,bestOf),null);}
const match=(id,a,b,winner,status='confirmed')=>({id,a,b,games:winner===a?[[11,4],[11,5]]:[[4,11],[5,11]],status,played_on:'2026-10-06',created_at:id});
const history=Array.from({length:10},(_,i)=>({...match(String(i).padStart(2,'0'),'strong','weak','strong'),played_on:'2026-10-05'}));
const before=calculateRatings(history),upset=calculateRatings([...history,match('11','new','strong','new')]),easy=calculateRatings([...history,match('11','new','weak','new')]);
assert.ok(upset.get('new').rating>easy.get('new').rating,'beating stronger players earns more Elo');assert.equal(upset.get('new').played,1);assert.equal(ESTABLISHED_MATCHES,5);
assert.ok(compareRatedPlayers({rating:1300,played:1,wins:1},{rating:980,played:5,wins:2})>0,'one win does not outrank an established player');
assert.equal(calculateRatings([...history,match('12','new','strong','new','pending')]).has('new'),false);assert.equal(calculateRatings([...history,match('12','new','strong','new','voided')]).has('new'),false);
assert.deepEqual(calculateRatings([...history].reverse()),before,'ratings use deterministic chronological order');
assert.ok(Math.abs([...before.values()].reduce((sum,r)=>sum+r.rating,0)-800)<1e-8,'Elo updates conserve points');
console.log('Passed: live deuce scoring, game advancement, undo across game/match completion, all formats; opponent-weighted Elo, provisional threshold, deterministic replay, pending/voided exclusion.');
const dated={...match('dated','a','b','a'),played_on:'2024-10-06'};
assert.equal(resultWeight(dated.played_on,'2025-10-05'),1);
assert.equal(resultWeight(dated.played_on,'2025-10-06'),.5);
assert.equal(resultWeight(dated.played_on,'2026-10-05'),.5);
assert.equal(resultWeight(dated.played_on,'2026-10-06'),0);
assert.equal(resultWeight('2024-02-29','2025-02-28'),.5,'leap-day anniversary clamps to February end');
assert.equal(resultWeight('2026-10-07','2026-10-06'),0,'future matches excluded');
assert.equal(calculateRatings([dated],'2025-10-05').get('a').rating,408);
assert.equal(calculateRatings([dated],'2025-10-06').get('a').rating,404);
assert.equal(calculateRatings([dated],'2025-10-06').get('b').rating,396,'losses decay symmetrically');
assert.deepEqual(calculateRatings([dated],'2026-10-06').get('a'),{rating:400,played:0,wins:0});
assert.equal(calculateRatings([{...dated,tournament_id:'event'}],'2025-10-05').get('a').rating,416,'tournaments carry double weight');
assert.equal(calculateRatings([{...dated,tournament_id:'event',tournament_weight:3}],'2025-10-05').get('a').rating,424,'cross-club tournaments carry triple weight');
assert.equal(calculateRatings([{...dated,tournament_weight:3}],'2025-10-05').get('a').rating,408,'weight cannot boost a regular match');
const affiliations=[{player_id:'a',club_id:'one',status:'active',role:'member'},{player_id:'b',club_id:'two',status:'active',role:'member'}];
assert.equal(tournamentWeight(['a','b'],affiliations,['one','two']),3);
assert.equal(tournamentWeight(['a','b'],affiliations,['one']),2,'unapproved clubs do not qualify');
assert.equal(tournamentWeight(['a','b'],affiliations.map(m=>({...m,role:'guest'})),['one','two']),2,'guests do not qualify');
assert.equal(tournamentWeight(['a','b'],affiliations.map(m=>({...m,status:'pending'})),['one','two']),2,'pending affiliations do not qualify');
const afterExpiry={...match('after','a','b','a'),played_on:'2026-10-06'};
assert.equal(calculateRatings([dated,afterExpiry],'2026-10-06').get('a').rating,408,'expired results do not affect current expected scores');
const agedFive=Array.from({length:5},(_,i)=>({...dated,id:String(i)}));
assert.equal(calculateRatings(agedFive,'2026-10-06').get('a').played,0,'provisional threshold uses eligible recent matches');
assert.equal(suggestSeeds(['a','b'],[dated],'2026-10-06')[0].rating,400,'seeds use the same ageing model');
assert.equal(calculateRatings([{...dated,status:'voided'}],'2025-10-06').has('a'),false);
console.log('Passed: double tournament weight, exact 12/24-month boundaries, leap days, future exclusion, symmetric decay, expired opponent evidence and shared seeding.');
