import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import ts from 'typescript';
mkdirSync('.test-runtime',{recursive:true});
for(const name of ['live-score','live-draft'])writeFileSync(`.test-runtime/${name}.mjs`,ts.transpileModule(readFileSync(`lib/${name}.ts`,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace("'./live-score'","'./live-score.mjs'"));
const {newLiveScore,addLivePoint,undoLivePoint}=await import('../.test-runtime/live-score.mjs');
const {parseLiveDraft,loadLiveDraft,storeLiveDraft,clearLiveDraft,draftKey}=await import('../.test-runtime/live-draft.mjs');
const memory=new Map(),storage={getItem:key=>memory.get(key)??null,setItem:(key,value)=>memory.set(key,value),removeItem:key=>memory.delete(key)};
let state=newLiveScore();for(let i=0;i<10;i++){state=addLivePoint(state,0,3);state=addLivePoint(state,1,3);}state=addLivePoint(state,0,3);
const draft={version:1,owner:'owner',id:'stable-submission',clubId:'club',a:'player-a',b:'player-b',bestOf:3,date:'2026-10-06',updatedAt:new Date().toISOString(),state,swapped:true};
storeLiveDraft(storage,draft);let restored=loadLiveDraft(storage,'owner');assert.deepEqual(restored,draft);assert.deepEqual(undoLivePoint(restored.state).points,[10,10]);assert.equal(restored.id,'stable-submission');
state=addLivePoint(restored.state,0,3);for(let i=0;i<11;i++)state=addLivePoint(state,0,3);storeLiveDraft(storage,{...draft,state});restored=loadLiveDraft(storage,'owner');assert.equal(restored.state.complete,true);assert.deepEqual(restored.state.games,[[12,10],[11,0]]);assert.equal(undoLivePoint(restored.state).complete,false);
assert.equal(loadLiveDraft(storage,'another-owner'),null);assert.equal(loadLiveDraft(storage,'owner',true),null);assert.equal(parseLiveDraft(JSON.stringify(draft),'another-owner'),null);
clearLiveDraft(storage,'owner','different-submission');assert.ok(loadLiveDraft(storage,'owner'),'an unrelated/late acknowledgment must not erase this draft');clearLiveDraft(storage,'owner',draft.id);assert.equal(loadLiveDraft(storage,'owner'),null);
for(const invalid of [{...draft,version:2},{...draft,a:draft.b},{...draft,bestOf:4},{...draft,date:'2026-02-30'},{...draft,state:{...state,complete:false}},{...draft,state:{...state,points:[-1,0]}},{...draft,state:{...state,history:[null]}}])assert.equal(parseLiveDraft(JSON.stringify(invalid),'owner'),null);
assert.equal(parseLiveDraft('broken json','owner'),null);assert.equal(parseLiveDraft('x'.repeat(2_000_001),'owner'),null);
assert.throws(()=>storeLiveDraft({...storage,setItem:()=>{throw new Error('Quota exhausted')}},draft));
storeLiveDraft(storage,draft,true);assert.ok(memory.has(draftKey('owner',true)));assert.equal(loadLiveDraft(storage,'owner'),null);
console.log('Passed: deuce recovery, completion/undo recovery, stable retry ID, account/demo isolation, acknowledgment cleanup, corrupt-data rejection and storage failures.');

let singleState=newLiveScore();for(let i=0;i<11;i++)singleState=addLivePoint(singleState,0,1);
assert.ok(parseLiveDraft(JSON.stringify({...draft,clubId:'unaffiliated',bestOf:1,state:singleState}),'owner'));
