import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import ts from 'typescript';
mkdirSync('.test-runtime',{recursive:true});writeFileSync('.test-runtime/notifications.mjs',ts.transpileModule(readFileSync('lib/notifications.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);
const {notificationsFor}=await import('../.test-runtime/notifications.mjs');
const data={me:{id:'a',name:'A'},players:[{id:'a',name:'A'},{id:'b',name:'B'}],clubs:[{id:'club',name:'Club'}],memberships:[{club_id:'club',player_id:'a',status:'active'}],matches:[{id:'one',a:'a',b:'b',canConfirm:true}],entries:[],tournaments:[{id:'open',name:'Open',club_id:'club',date:'2026-10-10',capacity:4,status:'registration',revision:0,state:null}]};
assert.equal(notificationsFor(data,[],false,'2026-10-06').length,2);
assert.deepEqual(notificationsFor({...data,me:null},[],false,'2026-10-06'),[]);
assert.equal(notificationsFor({...data,memberships:[]},[],false,'2026-10-06').some(n=>n.kind==='registration'),false);
assert.equal(notificationsFor({...data,tournaments:[{...data.tournaments[0],capacity:0}]},[],false,'2026-10-06').some(n=>n.kind==='registration'),false);
assert.equal(notificationsFor({...data,matches:[]},[],false,'2026-10-06').some(n=>n.kind==='match'),false);
const active={...data,entries:[{tournament_id:'open',player_id:'a'}],tournaments:[{...data.tournaments[0],status:'active',state:{fixtures:[{id:'r1m1',status:'ready',a:'a',b:'b'}]}}]};
assert.ok(notificationsFor(active,[],false,'2026-10-06').some(n=>n.id==='fixture-open-r1m1'));
assert.ok(notificationsFor(active,['started-open'],false,'2026-10-06').find(n=>n.id==='started-open').read);
assert.equal(notificationsFor({...active,memberships:[]},[],false,'2026-10-06').some(n=>n.kind==='tournament'),false);
const completed={...active,tournaments:[{...active.tournaments[0],status:'completed',date:'2026-10-01',revision:3}]};
assert.ok(notificationsFor(completed,[],false,'2026-10-06').some(n=>n.id==='completed-open-3'));
assert.equal(notificationsFor(completed,[],false,'2026-12-06').some(n=>n.kind==='tournament'),false);
console.log('Inbox eligibility, pending match resolution, membership/fullness, starts, ready fixtures, read status and result ageing passed.');
