import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const listeners=new Map(),storage=new Map();let standalone=false,ios=false;
const media={get matches(){return standalone},addEventListener(name,fn){listeners.set('media-'+name,fn)},removeEventListener(){}};
const window={matchMedia:()=>media,addEventListener(name,fn){listeners.set(name,fn)},removeEventListener(){},dispatchEvent(event){listeners.get(event.type)?.()}};
const localStorage={getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value)};
const session=new Map(),sessionStorage={getItem:key=>session.get(key)??null,setItem:(key,value)=>session.set(key,value)};
const navigator={get standalone(){return ios}};
const react={useEffect:fn=>fn(),useSyncExternalStore:(subscribe,snapshot)=>{subscribe(()=>{});return snapshot()}};
const exports={};
const source=ts.transpileModule(readFileSync('app/onboarding-checklist.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;
vm.runInNewContext(source,{exports,window,localStorage,sessionStorage,navigator,Event,require:name=>name==='react'?react:name==='lucide-react'?{X:'X'}:{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})}});
const data={me:{id:'self',name:'Self',profileComplete:true},players:[],memberships:[],matches:[]};
const render=()=>exports.default({data,demo:false}),text=()=>JSON.stringify(render());
assert.match(text(),/Photo and bio added/,'compact metadata checks off profile');
assert.doesNotMatch(text(),/Rally added to your Home Screen/,'ordinary browser is not installed');
standalone=true;assert.match(text(),/Rally added to your Home Screen/);standalone=false;
assert.match(text(),/Rally added to your Home Screen/,'installation persists in this browser');
storage.clear();ios=true;assert.match(text(),/Rally added to your Home Screen/,'iOS standalone detected');ios=false;
storage.clear();render();listeners.get('appinstalled')();assert.match(text(),/Rally added to your Home Screen/,'installation event remembered');
data.me.profileComplete=false;assert.match(text(),/Add your photo and bio/);
delete data.me.profileComplete;data.players=[{id:'self',photo_url:'sample.jpg',bio:'Player'}];assert.match(text(),/Photo and bio added/,'sample profile uses player fields');
data.players[0].bio=' ';assert.match(text(),/Add your photo and bio/,'blank sample bio incomplete');
const findBy=test=>{const walk=node=>node&&typeof node==='object'?(test(node)?node:Object.values(node).map(walk).find(Boolean)):undefined;return walk};
const closeButton=()=>findBy(n=>n.props?.['aria-label']==='Close getting started checklist for now')(render());
const dismissBox=()=>findBy(n=>n.type==='input'&&n.props?.type==='checkbox')(render());
closeButton().props.onClick();assert.equal(render(),null,'X closes the checklist for this visit');
assert.equal(storage.get('rally-onboarding-self'),undefined,'X does not hide it permanently');
session.clear();assert.notEqual(render(),null,'checklist returns on the next visit after X');
dismissBox().props.onChange({target:{checked:false}});assert.notEqual(render(),null,'unchecking does nothing');
dismissBox().props.onChange({target:{checked:true}});assert.equal(render(),null,'Dont show again hides it');
session.clear();assert.equal(render(),null,'Dont show again persists across visits');
console.log('Passed: profile completion, browser/iOS install detection, persistence, install event, X close-for-now and Dont show again.');
