import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import ts from 'typescript';
mkdirSync('.test-runtime',{recursive:true});
for(const name of ['seeding','player-performance'])writeFileSync(`.test-runtime/${name}.mjs`,ts.transpileModule(readFileSync(`lib/${name}.ts`,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/from ['"]\.\/([^'"]+)['"]/g,"from './$1.mjs'"));
const {playerPerformance}=await import('../.test-runtime/player-performance.mjs');
const m=(id,date,a='a',extra={})=>({id,played_on:date,a,b:a==='a'?'b':'a',status:'confirmed',games:[[11,4]],...extra});
const matches=[m('3','2026-10-03','a',{tournament_id:'event',tournament_weight:3}),m('2','2026-10-02','b'),m('1','2026-10-01'),m('pending','2026-10-02','a',{status:'pending'}),m('void','2026-10-02','a',{status:'voided'}),m('future','2027-10-01'),m('old','2023-01-01')];
const original=JSON.stringify(matches),a=playerPerformance(matches,'a','2026-10-06'),b=playerPerformance(matches,'b','2026-10-06');
assert.deepEqual(a.points.map(p=>p.id),['old','1','2','3']);
assert.deepEqual(a.points.map(p=>p.matches),[1,2,3,4]);
assert.deepEqual(a.points.map(p=>p.winRate),[100,100,2/3*100,75]);
assert.equal(a.played,4);assert.equal(a.wins,3);assert.equal(a.losses,1);
assert.equal(b.wins,1);assert.equal(b.points.at(-1).winRate,25);
assert.equal(a.points.at(-1).elo-a.points.at(-2).elo,24,'the first five pair matches retain full cross-club weighting');assert.equal(a.distinctOpponents,1);assert.equal(playerPerformance([],'a','2026-10-06').distinctOpponents,0);
assert.deepEqual(playerPerformance([...matches].reverse(),'a','2026-10-06'),a);
assert.equal(JSON.stringify(matches),original);
assert.deepEqual(playerPerformance([],'a','2026-10-06').points,[]);
console.log('Player charts passed chronological ordering, lifetime cumulative rates, expired-match inclusion, result exclusions, opponent symmetry, Elo weighting, empty states and input isolation.');
